microsoft/botbuilder-js

package.json
Added npm postinstall scripts to automate lerna bootstrapping and make lerna transparent to the developer.
Added various npm run scripts to enable a single command to link botbuilder to the global node_modules folder to make it easier for developers to add their local cloned repo to a project.
The new developer workflow would look like this:
```bash
git clone git@github.com:Microsoft/botbuilder-js.git
cd botbuilder-js
git checkout m2
npm install 
npm run dev #ignore error messages
```
Any project that you would like to use your local clone botbuilder sdk, just go into that project and run `npm link botbuilder` to have it use the globally symlinked botbuilder module pointing to your local clone.
=> M2 Developer Workflow Tools Improvements

.travis.yml, package.json
you can now type:
npm test
And it will work (travis has a new target called test:travis).
The issue was that the coverall report doesn't work locally.
=> created a separate local test target in npm (distinct from travis)

libraries/botbuilder-dialogs/lib/prompts/oauthPrompt.d.ts, libraries/botbuilder-dialogs/lib/prompts/oauthPrompt.js, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder/lib/botFrameworkAdapter.d.ts, libraries/botbuilder/lib/botFrameworkAdapter.js, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botframework-connector/lib/auth/microsoftAppCredentials.js, libraries/botframework-connector/lib/oAuthApiClient.js, libraries/botframework-connector/src/auth/microsoftAppCredentials.ts, libraries/botframework-connector/src/oAuthApiClient.ts, samples/dialogs/echobot-ts/lib/app.js, samples/dialogs/echobot-ts/src/app.ts, samples/dialogs/oauthbot-ts/README.md, samples/dialogs/oauthbot-ts/lib/app.js, samples/dialogs/oauthbot-ts/package.json, samples/dialogs/oauthbot-ts/src/app.ts, samples/dialogs/oauthbot-ts/tsconfig.json, samples/oauth-prompt-bot-es6/app.js, samples/oauth-prompt-bot-es6/package.json
Fixing a few issues with OAuthCard support and added two samples:
- Fixed sending credentials on OAuthAPI calls
- Fixed parsing of result objects
- Added support for using 'emulateOAuthCards' with the emulator
- Added sample for using the basic OAuthPrompt
- Added sample for using OAuthPrompt's as part of dialogs
=> Adding samples and fixing bugs with OAuthCard support

libraries/botbuilder-azure/src/blobStorage.ts
After some discussion, we decided not to try to replicate and handle the concurrent large object upload since it is really an edge case scenario. Instead, we simply included a clarifying comment in the code with the same guidance we added to the C# version.
=> Added comment with guidance for edge case scenario 'InvalidBlobkList'

samples/luis-bot-es6/README.md
Fixed the link error in README.md. The link was configured to a non-existent file.
=> Fixed the link error in README.md

libraries/botbuilder-azure/tests/cosmosDbStorage.test.js, libraries/botframework-connector/package.json
Setting the ms-rest-js dependency in botframework-connector to `"0.2.8"` as per @ctstone's [comments](https://github.com/Microsoft/botbuilder-js/issues/279#issuecomment-397267427) in issue #279.
I tested several versions of ms-rest-js and found that the change breaking the build is present from 0.3.0 onward.
This PR is a replacement for #299 and should address issue #301 as well.
**Note:** I didn't change the required ms-rest in botframework-luis  because of these notes in the [changelog](https://github.com/Azure/ms-rest-js/commit/33ebf36cbfdeef70bb0603068669d2caca3d2824#diff-9b8fab691c00b9e5380b19ce882f3271). According to semver, we _should_ be fine.
=> fix ms-rest-js dependency to 0.2.8

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js
Currently BotFrameworkAdapter.continueConversation() mocks up an activity of type message and BotFrameworkAdapter.createConversation() mocks up an activity of type conversationUpdate. I'd argue that both of these are somewhat dangerous as they can easily trigger unexpected behavior in the bot and it might be safer to mock up an 'event' activity of some sort instead.
The potential issue with message is that it could cause the bot to call a service like LUIS unnecessarily or even worse it could cause a logger to log that the user sent a message with empty text when it was actually the bot initiating the flow.
For conversationUpdate the issue is it could cause a GreetingMiddleware to send an extra greeting to the user which on the surface doesn't sound too bad but what if the bot developer …
=> Create event types for continue/create #420

libraries/botbuilder-dialogs/src/choices/index.ts, libraries/botbuilder-dialogs/src/dialogContext.ts
Change import statement in dialogContext to reflect that `botbuilder-prompts` no longer exists.
=> update import in dialogContext.ts

libraries/botbuilder-azure/lib/cosmosDbSqlStorage.d.ts, libraries/botbuilder-azure/lib/cosmosDbStorage.d.ts, libraries/botbuilder-azure/package-lock.json, libraries/botbuilder-azure/src/cosmosDbStorage.ts
Changed import of DocumentDB classes and namespaces, because the actual imports does not match those on the Typescript typings, and provokes build errors.
=> Fix DocumentDB imports

libraries/botframework-schema/.gitignore, libraries/botframework-schema/.npmignore
Publish was not uploading the lib folder for botbuilder-schema because of the .gitignore. Adding the .npmignore overrode and fixed it.
=> Fix botbuilder-schema deploy

.travis.yml
- Travis had been caching the node_modules directory entirely, which means it didn't detect when a dependency change broke stuff from under us
- One of those dependency changes was an update to `ms-rest` which should be making the build fail.
- We might want to revisit the rationale to cache node_modules and try another tooling like [`yarn`](https://yarnpkg.com/en/)
We created this PR to start the discussion on how to better deal with caching and perf.
=> Remove travis caching of node_modules

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-connector/src/auth/channelValidation.ts
These were part of the v3 SDK and so adding them to V4.
The parameters are optional properties on the BotFrameworkAdapterSettings class. If they are not set, the default, constant values are used.
oAuthEndpoint - the endpoint to use for the OAuth API calls
openIdMetadata - the endpoint to use to get open id metadata
=> Adding OpenIdMetadataEndpoint and OAuthApiEndpoint parameters

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botframework-connector/src/auth/channelValidation.ts, libraries/botframework-connector/src/auth/claimsIdentity.ts, libraries/botframework-connector/src/auth/constants.ts, libraries/botframework-connector/src/auth/enterpriseChannelValidation.ts, libraries/botframework-connector/src/auth/governmentChannelValidation.ts, libraries/botframework-connector/src/auth/governmentConstants.ts, libraries/botframework-connector/src/auth/index.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts, libraries/botframework-connector/tests/auth.test.js
This supports bots built for Gov and custom channels.
Changes include:
1. New channel validators for Azure Government data centers (.us) and custom channels (called enterprise channels).
2. New constants for gov
=> Support for 'channelService' property

libraries/botbuilder-core/src/botAdapter.ts, libraries/botbuilder-core/tests/botAdapter.test.js
the property accessor function was called onTurnError, and the inner field was turnError.
The accessor was trying to replace itself instead of setting the inner field
=> fix onTurnError and add unit test for onTurnError

.editorconfig
Added in a default .editorConfig file to standardize settings such as tabs. 
The file here is taken directly from the VSCode repo.
=> Add .editorConfig. This file is taken from the VSCode repo

libraries/botframework-config/package-lock.json, libraries/botframework-config/package.json, libraries/botframework-config/src/encrypt.ts, libraries/botframework-config/tests/encryption.test.js
recipes can end up with empty strings which our encrypt routines blow up on. 
fix for https://github.com/Microsoft/botbuilder-tools/issues/510
=> make encrypt()/decrypt() do nothing with null or empty values

libraries/botbuilder-dialogs/src/mainDialog.ts, libraries/botbuilder-dialogs/tests/mainDialog.test.js
This is a small DCR that was internally approved by @sgellock and others to address a pitfall in the new `MainDialog` class we added last week. The MainDialog class derives from `ComponentDialog` and this tweak overrides a some behavior in that class which could cause the developer grief.  It also adds a new **required** `onRunTurn()` method which derived classes will override and add all of their bots routing logic.
=> Added onRunTurn() method to MainDialog

libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/tests/luisRecognizer.test.js
and shouldn't blow up on these errors!
=> LuisRecognizer.prepareErrorMessage() ignores errors without `response.statusCode`

libraries/botframework-connector/package-lock.json, libraries/botframework-connector/package.json
Fix https://www.npmjs.com/advisories/658 vulnerability in base64url before 3.0.0 used in [botframework-connector](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-connector/src/auth/openIdMetadata.ts#L97)
=> Fix vulnerability in base64url before 3.0.0

libraries/botbuilder/package-lock.json, libraries/botbuilder/package.json
Removed two obsolete unused dependencies
`request` and `request-promise-native` are not used as part of build.
they also depend on `cryptiles` which has a reported vulnerability.
more info: https://snyk.io/node-js/request
=> Fix npm package vulnerabilities in botbuilder

libraries/botbuilder-core/tests/cardFactory.test.js, libraries/botbuilder-core/tests/conversationState.test.js, libraries/botbuilder-core/tests/privateConversationState.test.js, libraries/botbuilder-core/tests/userState.test.js
- Add `CardFactory.oauthCard()` tests
- Add coverage tests for the `*State` classes.
=> add more tests for State classes and CardFactory

libraries/botframework-config/src/botRecipe.ts, libraries/botframework-config/tests/bot.recipe, libraries/botframework-config/tests/botRecipe.test.js
Found bug in BotRecipe.fromJSON where if no arg was passed in, the output's `version` and `resources` properties would be undefined. 
And [add test coverage for `BotRecipe`.](https://travis-ci.org/Microsoft/botbuilder-js/jobs/435057154#L1407)
=> BotRecipe.fromJSON to use default values if arg doesn't have expected values, add BotRecipe tests

libraries/botbuilder/src/botFrameworkAdapter.ts
Authorization was coming in empty because it was checking caps vs lowercase.
=> Fix for working with ServerlessFramework

Generator/package-lock.json, Generator/package.json
- Remove deprecated package 'nsp' ([more info](https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting))
- Fix 'cryptiles' vulnerability upgrading jest-cli (This action removes the 'cryptiles' dependency)
=> Fix npm packages vulnerabilities in Generator

libraries/botbuilder-core/src/transcriptLogger.ts, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js
- Convert `string` json props from `WebRequest.body` to `Date`.
- Change `cloneActivity` method to maintain the Date properties as Date.
----
These changes are needed to save the timestamp with `transcriptLogger`.
=> Fix activity timestamp string to Date.

libraries/botbuilder/tests/botFrameworkAdapter.test.js
=> add tests for BotFrameworkAdapter methods

libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts
- Change Dutch translation in confirmPrompt (‘niet’ to ‘nee’). 
Niet could be an option, but isn't the correct translation in this 'yes / no' context.
I will have a look if I can port the Dutch .NET `BooleanRecognizer` in Recognizers-Text also to JavaScript. At the moment I only created all Dutch recognizers for C#.
Related PR in .NET repo: https://github.com/Microsoft/botbuilder-dotnet/pull/1017
=> Change Dutch translation in confirmPrompt (‘niet’ to ‘nee’)

libraries/botbuilder-ai/src/luisRecognizer.ts
This will address #522 in that all of the LuisPredictionOptions are now passed in to the underlying autorest-generated client.
=> use object spread instead of explicit assigns in LuisRecognizer

libraries/botbuilder/src/botFrameworkAdapter.ts
The API endpoint for creating conversations requires a `Conversation` object parameter, and as such the SDK function requires additional parameters including `members` and potentially `topicName` and `activity` as well per:
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#create-conversation
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#conversation-object
=> Bugfix BotFrameworkAdapter.createConversation

libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts, libraries/botbuilder-dialogs/src/prompts/prompt.ts, libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
Fixes same bugs as in Microsoft/botbuilder-dotnet#1019 & Microsoft/botbuilder-dotnet#1022
=> fix ConfirmPrompt and Prompt.appendChoices() bugs, add tests

libraries/botbuilder-azure/src/cosmosDbStorage.ts
- Changed `SELECT * FROM root r WHERE r.id=@id` into `SELECT r._self FROM root r WHERE r.id=@id`
=> Fix #547: don't use select * in queries

libraries/botframework-connector/tests/auth.test.js
Cleanup around auth tests in the `botframework-connector` library.
1. Updates tests to be more ES6-like
2. Tests now use async/await syntax
3. When tests are expected to error, the errors are actually examined instead of simply seeing if an error exists
This PR does not:
- Address the issues in #533
- Fix the potential new issue in the `ChannelValidator` test: `validateIdentity should fail if no identity` (TypeError is thrown)
=> botframework-connector auth test cleanup

libraries/botbuilder-azure/package.json, libraries/botbuilder-azure/src/cosmosDbKeyEscape.ts, libraries/botbuilder-azure/src/cosmosDbStorage.ts, libraries/botbuilder-azure/src/index.ts, libraries/botbuilder-azure/tests/cosmosDbKeyEscape.test.js, libraries/botbuilder-azure/tests/cosmosDbStorage.test.js, package-lock.json
- Extracted Key Escaping into a dedicated class (with tests).
- Added numerous CTor exception tests.
- Fixed race condition around Initialization
Based on https://github.com/Microsoft/botbuilder-dotnet/pull/1014
=> Fixes and Updates to the CosmosDB Storage Provider

libraries/botbuilder-azure/src/cosmosDbKeyEscape.ts, libraries/botbuilder-azure/src/cosmosDbStorage.ts, libraries/botbuilder-azure/tests/cosmosDbKeyEscape.test.js, libraries/botbuilder-azure/tests/cosmosDbStorage.test.js
- Change `CosmosDbStorage.write(changes)` to not blowup with falsey or empty `changes`
- Change `CosmosDbStorage.delete(keys)` to not call Cosmos DB if `keys` are falsey or empty
- Setup **offline** CosmosDbStorage read/write/delete tests to always run
- Remove unused private method `CosmosDbStorage.sanitizeKey()`
- Add docstring to `CosmosDBKeyEscape.escapeKey()`
- Rename CosmosDBKeyEscape to Cosmos**Db**KeyEscape
=> update CosmosDbStorage and CosmosDbKeyEscape

.travis.yml, libraries/botbuilder-ai/package-lock.json, libraries/botbuilder-ai/package.json, libraries/botbuilder-azure/package-lock.json, libraries/botbuilder-core/package-lock.json, libraries/botbuilder-dialogs/package-lock.json, libraries/botbuilder-dialogs/package.json, libraries/botbuilder/package-lock.json, libraries/botframework-config/package-lock.json, libraries/botframework-connector/package-lock.json, libraries/botframework-schema/package-lock.json, package-lock.json, package.json, transcripts/package-lock.json, transcripts/package.json
- Cherry-picked pin of recognizers-text to version 1.1.2
- Remove downgrade of npm in .travis.yml
- update package-lock.json files
- update various dependencies and move `nock` from core dependency to devDependencies in `botbuilder-ai`
- add `/transcripts` to the root npm script: `"set-dependency-versions"`
=> pin recognizers dependencies to 1.1.2, clean build process, keep version travis npm at 6.4.1

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botframework-connector/src/auth/index.ts, libraries/botframework-connector/src/auth/microsoftAppCredentials.ts
Bots weren't able to communicate with Prod US Gov. 
The MicrosoftAppCredential had a fixed endpoint and scope, and these needed to change for US Gov.
=> Making bot code to work with prod gov

libraries/botbuilder-azure/package.json, libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts
Fixes #382
stop using string-literal notation in AzureBlobTranscriptStore.ts
- Bump dependency of `azure-storage` to a version with the updated .d.ts with `listBlobDirectoriesSegmentedWithPrefix()`
- Remove the tslint ignore comment from AzureBlobTranscriptStore.ts
=> stop using string-literal notation in AzureBlobTranscriptStore.ts

libraries/botbuilder-core/src/turnContext.ts
Fixes #611 
We had incorrectly used await in the place of async in some function declarations _in the comments_, which then get published in our docs.
=> Correct improper use of await in function declarations

libraries/botframework-config/src/models/endpointService.ts, libraries/botframework-config/tests/govTest.bot, libraries/botframework-config/tests/loadAndSave.test.js
Adding channelService to the bot configuration file which controls whether the bot is talking to public Azure or US Government Azure
Add the channelService property to the endpoint service model
Added a test to load and check the values.
=> Add channelService to endpoint service of bot configuration file

libraries/botframework-connector/package-lock.json, libraries/botframework-connector/package.json, libraries/botframework-connector/src/auth/microsoftAppCredentials.ts, libraries/botframework-connector/src/auth/openIdMetadata.ts, libraries/botframework-connector/src/emulatorApiClient.ts, libraries/botframework-connector/src/index.ts, package-lock.json
Fixes #600
This PR removes the `request` dependency in the `botframework-connector` library and instead uses `node-fetch` and `form-data` which _should_ allow `botframework-connector` to be used in the browser.
- EmulatorApiClient, MicrosoftAppCredentials, OpenIdMetadata classes no longer use `request`
- Reworked some of the private and internally called methods to use async syntax as opposed to Promises or worse, Promise-callback style
=> Remove request dependency from botframework-connector library

libraries/botframework-config/src/schema.ts, libraries/botframework-connector/src/auth/emulatorValidation.ts, libraries/botframework-connector/src/auth/governmentConstants.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts
When the emulator is configured (via the channelService property in the .bot file) to use the US Government Azure AAD endpoint, this causes a different set of issuers and a different open id metadata URL to be needed to validate the emulator's JWT token.
Because this involves testing JWT tokens which I cannot check-in, I validated with:
1. Emulator configured to use Gov talking connecting to a local JS bot configured to use Gov running locally 
2. Emulator configured to use Gov talking connecting to an Azure hosted JS bot configured to use Gov running locally 
3. DirectLine talking to the same bot (via US Gov)
=> Updates to validate emulator JWT tokens from US Gov

libraries/botframework-connector/package-lock.json, libraries/botframework-connector/package.json, libraries/botframework-schema/package.json, package-lock.json
Fixes #643
Breaking changes were introduced in a version of ms-rest-js greater than 1.0.455 (which is what the generated code was built to work with). The last (not deprecated) version of ms-rest-js (1.0.465) was not compatible with the generated code. 
Instead of ms-rest-js, they have deprecated it in favor of [@azure/ms-rest-js](https://www.npmjs.com/package/@azure/ms-rest-js). 
- Pin to ms-rest-js 1.0.455 in botframework-connector, botframework-schema
- Pin to ms-rest-azure-js 1.0.176 in botframework-connector
=> Pin ms-rest-js and ms-rest-azure-js in botframework-connector and botframework-schema

libraries/botbuilder-core/src/conversationState.ts, libraries/botbuilder-core/src/privateConversationState.ts, libraries/botbuilder-core/src/userState.ts, libraries/botbuilder-core/tests/conversationState.test.js, libraries/botbuilder-core/tests/privateConversationState.test.js, libraries/botbuilder-core/tests/userState.test.js
Fixes #610 
I have corrected the faulty `NO_KEY` messages in three files to more accurately represent the error. While the issue originally called for a simple change from `context.request` to `context.activity`, I took it upon myself to reword the messages based on the conditions I've discovered will trigger the error.
The new message `overridden getStorageKey method did not return a key` can be found in:
- userState.ts
- conversationState.ts
- privateConversationState.ts
The `NO_KEY` error messages can only be triggered if the `getStorageKey` methods are overridden because the current `getStorageKey` methods cannot return anything that evaluates to false. In order to test the messages you must override the `getStorageKey` methods and have them return `undefined` or an empty string.
=> Correct NO_KEY messages in State classes for issue #610

libraries/botbuilder-core/src/botStatePropertyAccessor.ts
Fixes: bug introduced in #566.
The implementation of BotStatePropertyAccessor was no longer matching the StatePropertyAccessor interface, which caused TypeScript users to run into build issues.
Example of error message:
```bash
node_modules/botbuilder-core/lib/botStatePropertyAccessor.d.ts:85:5 - error TS2416: Property 'get' in type 'BotStatePropertyAccessor<T>' is not assignable to the same property in base type 'StatePropertyAccessor<T>'.
Type '(context: TurnContext, defaultValue?: T | undefined) => Promise<T | undefined>' is not assignable to type '{ (context: TurnContext): Promise<T | undefined>; (context: TurnContext, defaultValue: T): Promise<T>; }'.
Type 'Promise<T | undefined>' is not assignable to type 'Promise<T>'.
Type 'T | undefined' is not assignable to type 'T'.
Type …
```
=> add overloads to BotStatePropertAccessor.get()

libraries/botframework-connector/src/auth/channelValidation.ts, libraries/botframework-connector/tests/auth.test.js
https://github.com/Microsoft/botbuilder-js/issues/533
- Verified that the removed tests were already covered by other tests.
- Fixed checking for undefined so the correct error was thrown.
- Added a missing case to the emulator path
=> Fixing auth tests that were using expired tokens

libraries/botbuilder-core/src/botStatePropertyAccessor.ts
Fixes bug introduced in #566 for 4.1.5 branch.
(See original PR #647 against master for more information)
=> cherry-pick: add overloads to BotStatePropertAccessor.get()

libraries/swagger/model_fixes.js
First fix for #639
Add `"channelData"` as an optional property for the CardAction interface.
Note: This doesn't fix #639 directly as the library needs to be regenerated. This PR sets it up so that then the library is properly regenerated (via the `generateClient` scripts), #639 will be fixed.
=> update model_fixes.js to set CardAction.channelData as an optional property

libraries/botbuilder-ai/package.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/package.json, libraries/botbuilder-dialogs/package.json, libraries/botbuilder/package.json, libraries/botframework-config/package.json, libraries/botframework-connector/package.json, libraries/botframework-schema/package.json
Fixes #652 
Update all the package files to change dependency on other Botbuilder libraries from any minor release (^4.0.0) to the specific minor release (~4.1.x)
This means a user installing version 4.1.7 will get all 4.1 updates, but will not automatically migrate to 4.2 which could break things.
=> Lock internal dependencies to patch version

lerna.json, libraries/botframework-schema/src/index.ts, libraries/swagger/generateClient.cmd, libraries/swagger/model_fixes.js, libraries/swagger/package-lock.json, libraries/swagger/package.json
Fixes #639 - Marks `CardAction.channelData` as optional
Fixes Microsoft/botbuilder#5187 for JS v4 - Marks `ChannelAccount` and `ConversationAccount` `aadObjectId` and `role` properties as optional.
Update process for generating connector and schema libraries, add package.json with autorest dependencies.
- Add package.json with autorest dependencies to `swagger/`
- Modify `generateClient.cmd` to specifically use the locally installed autorest package
- Update lerna.json to explicitly bootstrap --hoist actual published libraries and therefore not include `libraries/swagger`
- Improve UX in generateClient.cmd and uncomment connectorAPI-handling code
=> Improve swagger-generation process for bf-connector & bf-schema libraries

libraries/botbuilder-core/src/botState.ts, libraries/botbuilder-core/tests/botState.test.js
Fixes https://github.com/Microsoft/BotBuilder/issues/5175
Adds a new BotState.delete() method.
Added method and unit tests.
Included
=> Added BotState.delete() method and tests

.travis.yml
Update build number for master to 4.3.0. 
The 4.2.0 branch has already been cut and updated.
=> Update version number for 'master' to be 4.3.0-preview

README.md
Update the readme to show the Build / Package badges for the 4.2 release.
=> Update 'master' readme to reflect 4.2 branch builds

libraries/botbuilder-azure/src/cosmosDbStorage.ts
Fixes #691
`CosmosDbStorageSettings` currently _requires_:
- `databaseCreationRequestOptions` 
- `documentCollectionRequestOptions`
-- they should be _optional_
- changed properties `databaseCreationRequestOptions` & `documentCollectionRequestOptions` in `CosmosDbStorageSettings` interface
=> Made databaseCreationRequestOptions & documentCollectionRequestOptions optional in CosmosDbStorageSettings interface

libraries/botbuilder-ai/package.json, libraries/botbuilder-ai/tsconfig.json, libraries/botbuilder-applicationinsights/tsconfig.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-azure/tsconfig.json, libraries/botbuilder-core/tsconfig.json, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-dialogs/tsconfig.json, libraries/botbuilder/package.json, libraries/botbuilder/tsconfig.json, libraries/botframework-config/tsconfig.json, libraries/botframework-connector/package.json, libraries/botframework-connector/tsconfig.json, libraries/botframework-schema/package.json, libraries/botframework-schema/tsconfig.json, package-lock.json, transcripts/package.json
* Update NodeJS version for supporting RegExp related features natively, like `lookBehind assertions` and `named capture groups`. These changes are supported since the v.10.3.0 version, but we update the project's version to the v10.15.0 (v.10.12.18 in typescript) as it is the current LTS.
A PR for supporting these changes was also created in Recognizers-text project ([PR#1069](https://github.com/Microsoft/Recognizers-Text/pull/1069))
* Update the tsconfig.json files to target `ESNext` as Node JS v.10 has good native support for most ESNext language built-ins, which will reduce file size and improve the debugging experience and performance.
- Update `libraries/botbuilder-ai/package.json` `@types/node` to ^10.12.18.
- Update `libraries/botbuilder-azure/package.json` `@types/node` to …
=> Update @types/node to v10.12.18

libraries/botbuilder-ai/src/qnaMaker.ts
Turned on tslint and fixed linting errors from PR #704 
- got rid of trailing whitepsaces
- added types on variables missing typing
- moved deprecated methods to appear before `private` methods, as they are of `public` or `protected` accessibility
=> Made linting fixes to QnAMaker

libraries/botbuilder-dialogs/src/componentDialog.ts, libraries/botbuilder-dialogs/src/dialogContext.ts, libraries/botbuilder-dialogs/src/waterfallDialog.ts, libraries/botbuilder-dialogs/src/waterfallStepContext.ts, libraries/botbuilder-dialogs/tests/componentDialog.test.js
Implements [this DCR](https://github.com/Microsoft/BotBuilder/issues/5242)
Currently, dialogs can only start sibling dialogs that are defined within the same DialogSet. This PR adds the ability for a dialogs to also start dialogs that are defined in a parents dialog set.
- Added a public `DialogContext.parent` property which can be used to assign a parent DC. 
- Added a public `DialogContext.findDialog()` method which will first search the local DialogSet for a dialog and then search its parents DC if not found.
- Updated all dialog lookups in the DialogContext class to use new findDialog() method.
- Updated `ComponentDialog` to wire up a parent DC chain it works through the dialog stack.
- Updated `WaterfallStepContext` class to properly clone parent DC.
Added new Unit Tests to verify …
=> Added ability to call dialogs within a parent component.

libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts
Fixes https://github.com/Microsoft/botbuilder-dotnet/issues/1307
This pull request changes the default timeout in oauthPrompt.ts from 54000000 (15 hours in milliseconds) to 900000 (15 minutes in milliseconds). The comments always said it was 15 minutes so this change will make the actual value match the comments.
=> Change OAuthPrompt default timeout from 54000000 to 900000 ms

libraries/botbuilder-dialogs/src/choices/choiceFactory.ts, libraries/botbuilder-dialogs/tests/choices_choiceFactory.test.js
Fixes  https://github.com/Microsoft/botbuilder-dotnet/issues/1173
I have modified choiceFactory.ts by removing `hasMessageFeed` and `supportsCardActions` from the `if` condition so that now a channel _must_ support suggested actions in order for the SDK to automatically select them as the list style. I have also deleted those local variables for cleanliness since they aren't being used anywhere else.
=> Prevent Cortana from trying to use suggested actions in prompts

libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts, libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts
Fixes #655
These changes address @johnataylor 's concern about these static members:
* They are now private instead of public, as they shouldn't be used or modified by developers directly.  Devs who want to change these options can and should pass them in as paramters.
* Combining the options prevents the 2 objects from becoming out of sync with one another.  A single index is used to access both default choices and default options.
* Make defaultChoiceOptions a private member
* Combine defaultConfirmChoices and defaultChoiceOptions into a single object inside  Confirmprompt
* Mark defaultConfirmChoices as deprecated
=> Make defaultChoiceOptions private

libraries/botbuilder-dialogs/src/prompts/activityPrompt.ts
Fixes #703
Allow developers to use ActivityPrompt directly, rather than forcing them to derive a new class.
Remove the abstract keyword
=> Make ActivityPrompt a normal class - remove abstract

libraries/botbuilder-core/src/index.ts, libraries/botbuilder-core/src/testAdapter.ts, libraries/botbuilder-core/src/userTokenProvider.ts, libraries/botbuilder-core/tests/testAdapter.test.js, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/tests/oauthPrompt.test.js, libraries/botbuilder/src/botFrameworkAdapter.ts
Ability to mock the OAuth APIs on a BotAdapter
Implementation of mock in TestAdapter
Ensure OAuthPrompt uses the new interface
Sample unit tests for how to test OAuth APIs and the OAuthPrompt
Yes, tests on TestAdapter and OAuthPrompt
=> Ability to test OAuthPrompt and mock OAuth APIs

libraries/botbuilder-azure/package-lock.json, libraries/botbuilder-azure/src/cosmosDbKeyEscape.ts, libraries/botbuilder-azure/tests/cosmosDbKeyEscape.test.js
This is a Javascript port of the fix for [botbuilder-dotnet#1197](https://github.com/Microsoft/botbuilder-dotnet/issues/1197) as represented in [this PR] (https://github.com/Microsoft/botbuilder-dotnet/pull/1370)
Cosmos DB has a max key length of 255 chars. This was sometimes exceeded.  This change detects keys with a length of > 255 chars and truncates them, taking special care to create a unique key by appending a hash of the original value to the key.
Unit tests have been included.
=> Truncate length of CosmosDb key to max of 255 chars

transcripts/package-lock.json, transcripts/package.json
fix GH warnings due to outdated packages
=> Fixes 764: Outdated transcript-test package is causing GitHub warnings

libraries/swagger/generateClient.sh
Fixes #762 
macOS shell script to generate swagger generated clients was out of date with the windows version
update macOS `generateClient.sh` to be aligned to the windows version of `generateClient.cmd`
=> Fixes 762: libraries\swagger\generateClient.sh out of sync with generateClient.cmd

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js
Fixes #755 and provides better parity with .net [BotFrameworkAdapter.cs#L534](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L534)
=> Fixes #755 - null connection name should not be allowed

libraries/botbuilder-dialogs/src/choices/choiceFactory.ts, libraries/botbuilder-dialogs/src/prompts/prompt.ts, libraries/botbuilder-dialogs/tests/choices_choiceFactory.test.js
Fixes #737 
Also puts `ChoiceFactory.ts` at 100% coverage.
=> Fixes #737 - Add new HeroCard prompt style to ChoiceFactory

libraries/botbuilder-core/src/ActivityHandler.ts, libraries/botbuilder-core/tests/ActivityHandler.test.js
This is a Javascript port of the changes in [dot-net#1380](https://github.com/Microsoft/botbuilder-dotnet/pull/1380)
Remove all but message, event, and conversationupdate handlers, allow all other incoming activities to be handled by the unrecognizedactivity handler.
=> Remove events from ActivityHandler that are too channel specific

.gitattributes
Addresses #758 
I'm not sure if it will fix the issue, however it seems sensible to set either way. 
This PR defines how package.json and package-lock.json files are handled with respect to EOF markers. This area has all sorts of weird NPM bugs (see linked issue).
=> Set Line endings on pacakge.json

libraries/botbuilder-ai/package.json, libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/tests/luisRecognizer.test.js, package-lock.json
Fixes Microsoft/BotBuilder#5255
- Adds support for passing in a LUIS Application Endpoint as retrieved from the LUIS.ai portals
- Adds overload for passing in string instead of `LuisApplication` instance
- Adds unittests for new feature
This PR differs from the C# PR in that `LuisApplication` is an interface in TS, not a class. Therefore the parsing logic for the endpoint is performed inside of the constructor for `LuisRecognizer`.
C# parity PR is located here: Microsoft/botbuilder-dotnet#1378
=> add support for LUIS endpoint to LuisRecognizer, tests

libraries/botbuilder-ai/.npmignore, libraries/botbuilder-ai/package.json, libraries/botbuilder-applicationinsights/.npmignore, libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-azure/.npmignore, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/.npmignore, libraries/botbuilder-core/package.json, libraries/botbuilder-dialogs/.npmignore, libraries/botbuilder-dialogs/package.json, libraries/botbuilder/.npmignore, libraries/botbuilder/package.json, libraries/botframework-connector/.npmignore, libraries/botframework-connector/package.json, libraries/botframework-schema/.npmignore, libraries/botframework-schema/package.json
Fixes #777, #778 
Moved to an Include model to only pull in specific files. Initial cut is "/src/" and "/lib" added as a whitelist in the package.json.
=> Updates to Package formatting and layout

libraries/botbuilder-ai/tests/luisRecognizer.test.js
additional validation for:
- full path including appId, not just regex match for 'apps'
- query string
- subscription key in headers (twice)
- request content
=> add full nock validation for LUIS calls

libraries/botbuilder/tests/botFrameworkAdapter.test.js
Fixes #799 
The description of the test was modified to match the method it was testing. 
- Change 'signOutUser()' to 'getAadTokens()' in the test description 
No testing required
=> Change test description to match implementation

package.json
Fixes #774 
Even though it is necessary to have lerna installed globally to run commands such as `npm i` and `npm run build`, it is not listed on the devDependencies. This causes issues when trying to intall.
To avoid this, we added lerna as a devDependency on the `package.json` file.
- Add the `"lerna": "^3.2.1"` line to the `package.json`
Before adding the line:
After adding the line:
=> Add lerna to package.json devDependencies

libraries/botbuilder/package-lock.json, libraries/botbuilder/package.json, libraries/botbuilder/src/fileTranscriptStore.ts, libraries/botbuilder/tests/fileTranscriptStore.test.js, libraries/botframework-config/package-lock.json, package-lock.json
Fixes #786 
Replace async-file package with fs-extra.
These packages provide the same functionality with slightly different syntax.
Removing dependence on async-file reduces the packages we need to worry about.
* replaced dependence in package file
* replaced calls to .delete with .remove
* replaced calls to .exists with .pathExists
Run existing tests
=> Replace async-file with fs-extra to match other packages

libraries/botbuilder-ai/package.json
Bump to luis-runtime without the misleading deprecate message.
=> Bump to latest LUIS SDK package

libraries/botbuilder-ai/package.json
Adds Telemetry support to QnAMaker
Shares same pattern as Luis and TelemetryMiddleware.
Enables setting properties during GetAnswersAsync
Enables deriving from class and adding properties
https://github.com/daveta/analytics/blob/master/telemetry_enhancements/TelemetryEnhancements.md#telemetry-qna-recognizer
C# Version: https://github.com/Microsoft/botbuilder-dotnet/pull/1430
=> QnA Telemetry Support 

libraries/botbuilder-ai/package.json
Updates the Luis Runtime SDK to point at v1.2.2.
There's no functional difference, but the npm package install won't emit a misleading message for Bot Framework users (about deprecation).
=> [4.3] Update the LUIS SDK to point at v1.2.2 of Luis Runtime SDK

libraries/botbuilder-ai/package.json
Cherry pick bump of LUIS runtime version to remove deprecation message
- bump azure-cognitiveservices-luis-runtime to 1.2.2
=> [4.3 cherry-pick]: Bump to latest luis SDK package

libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts, libraries/botbuilder-azure/tests/azureBlobTranscriptStore.test.js
Fixes #808 
- Removed 'Async' keyword from createBlobService's Proxy
- Fixed methods that weren't being awaited and were overlapping
- Fixed tests that were calling callback methods as a promise
=> Fix AzureBlobTranscriptStore

libraries/botbuilder-ai/package.json, libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/tests/luisRecognizer.test.js, libraries/botbuilder-ai/tests/luisSdk.test.js
Update the LUIS SDK to upgrade to new Typescript-generated-autorest thing.
=> Upgrade LUIS to new SDK - this time with feeling

libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/tests/luisRecognizer.test.js
Matching changes to [C# PR for binary compat with LUIS recognizer](https://github.com/Microsoft/botbuilder-dotnet/pull/1561) which moves TelemetryClient into options class.
Also fix broken test and make hook async.
=> Parity with c# - binary compat changes for LuisRecognizer

libraries/botbuilder-dialogs/src/choices/channel.ts, libraries/botbuilder-dialogs/tests/choices_channel.test.js
Fixes https://github.com/Microsoft/BotBuilder/issues/5316
and
https://github.com/Microsoft/BotBuilder/issues/5313
OAuthPrompt (line works with OAuthPrompt)
Dialogs Channel: added LIne 
- SupportsSuggestedActions: 13
- SupportsCardActions: 99
Channel Constant: added Line
Add tests for Line, and fixed other choices_channel tests.
=> Line channel updates

package.json
This lets us run coveralls in the BotBuilder-JS-master-CI build.
Script "test" would no longer be run in the build, as "test:coveralls" covers it.
=> Restore the deleted script "test:travis" as "test:coveralls"

libraries/botbuilder-dialogs/src/prompts/prompt.ts, libraries/botbuilder-dialogs/tests/numberPrompt.test.js
Fixes https://github.com/Microsoft/BotBuilder-Samples/issues/1257
Adds a numberOfAttempts property to the promptOptions
=> added numberOfAttempts to promptOptions

libraries/botbuilder-ai/package-lock.json, libraries/botbuilder-ai/package.json, libraries/botbuilder-dialogs/src/prompts/activityPrompt.ts, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/src/prompts/prompt.ts, libraries/botbuilder-dialogs/tests/numberPrompt.test.js, package-lock.json
- moves the numberOfAttempts property into the state from the options
- adds a typed/named property to the top level for parity with the typing/discovery C# implementation
=> move numberOfAttempts to state from options

libraries/botbuilder-ai/package-lock.json, libraries/botbuilder-ai/package.json
The Cognitive Services project allows the Azure@MS-Rest-Json package version to float. This means when a new version of that package is published (as it was today), our build breaks with Typescript errors. 
Allowing this to float should *help* keep them in sync.
=> Allow patch version of ms-rest to float.

libraries/botbuilder-expression-parser/src/expressionEngine.ts, libraries/botbuilder-expression-parser/src/index.ts, libraries/botbuilder-lg/src/templateEngine.ts
There are a few instances where the case of the included file is incorrect, which breaks the library on some operating systems.
As a result, the nightly build version of `botbuilder-lg` and `botbuilder-expression-parser` don't work on Macs!
=> Fix case of imported files for 4.next botbuilder-lg and botbuilder-expression-parser

libraries/botbuilder-ai/src/luisRecognizer.ts
Fixes #916
Autorest introduced a breaking change to their credentials interface.  We're hitting this at build time because lerna hoists all packages to the root and we can only have one version of autorest from a build perspective.
I casted the credentials to `any` just to get things to build. This shouldn't be an issue at runtime so no patch is needed.
=> Fixed build break

libraries/botbuilder/src/inspectionMiddleware.ts
This makes the '/INSPECT attach {etc etc}' a trace activity.
=> make attach command a Trace activity

libraries/botbuilder-core/src/botState.ts, libraries/botbuilder-core/tests/botState.test.js
=> remove property name existance check from botstate

libraries/botbuilder-lg/src/evaluator.ts
Fixes #
- change caseNode.switchCaseStat().DEFAULT()  to caseNode.switchCaseStat().DEFAULT() !== undefine.
makes code more readable.
-
-
=> change a boolean expr in evaluator/switchcasebody

libraries/botbuilder-expression-parser/src/expressionEngine.ts, libraries/botbuilder-expression-parser/tests/badExpression.test.js, libraries/botbuilder-expression-parser/tests/expression.test.js
Previously Expression support such format: 'hello'.length(), which is same as length('hello'), but in the future, this kind of Expression will be deprecated.
=> [Expression] Obsolete special format

libraries/botbuilder/src/inspectionMiddleware.ts
The activity, even if it a message activity, can have null text. For example if it just contains an attachment.
This brings the Node repo inline with the C# implementation.
=> dotnet issue 1860 activity.text can be null

libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/tests/luisRecognizer.test.js
Fixes #964 
Add ability for Recognizer.recognize method to accept user-defined luis prediction options and use the properties present in that particular request, defaulting to the options set by the class constructor otherwise.
1) botbuilder-js\libraries\botbuilder-ai\src\luisRecognizer.ts
-- Added additional parameter to 'recognize' method to accept user-defined luis prediction options.
-- Added private method 'setLuisPredictionOptions' to merge the user-defined and default options objects (and to make it testable).
Tests added to:
libraries/botbuilder-ai/tests/luisRecognizer.test.js
=> Add ability to pass LUIS prediction options into Recognizer.recognize method

libraries/botbuilder-lg/src/analyzer.ts, libraries/botbuilder-lg/src/mslgTool.ts, libraries/botbuilder-lg/src/templateEngine.ts, libraries/botbuilder-lg/tests/lg.test.js
origin issue: https://github.com/microsoft/botbuilder-dotnet/issues/2093
Originally `analyzeTemplate(templateName: string)` would return a list of variables. 
From now , this function will reture a structure dat, including a list of variables and list of templateref names.
=> [LG WIP] new analyzer

libraries/testbot/.env, libraries/testbot/index.js, libraries/testbot/package-lock.json, libraries/testbot/package.json
Inspection middleware will not function properly unless MicrosoftAppCredentials are provided.  Modified TestBot to provide this during construction.
=> add credentials to inspection middleware for test bot

.editorconfig, README.md, libraries/botbuilder-testing/README.md, libraries/botbuilder-testing/src/dialogTestClient.ts, libraries/botbuilder-testing/tests/dialogTestClient.test.js
* Removed callback from constructor (we don't want to expose that one for now).
* Removed adapterOptions from constructor.
* Refactored constructor to take a channeldId or a TestAdapter (required).
* Added optional conversationState parameter to constructor
* Added conversationUpdate property to allow devs to manipulate state during tests.
Updated Readme to match current changes
Updated tests to pass.
Updated .editorconfig to enforce spaces instead of tabs
=> DialogTestClient updates

libraries/botframework-config/src/models/qnaMakerService.ts, libraries/botframework-config/tests/service.test.js
Fixes #939 
* Issue 1: URL built for hostname would _always_ append "`/qnamaker`" to `QnAMakerService.hostname`, even when the `hostname` already had `/qnamaker` in the hostname string
* **QnAMakerService will now only append `/qnamaker` to hostname, if it does not end in `/qnamaker` already**
* Ex 1: `https://myservice.azurewebsites.net` => `https://myservice.azurewebsites.net/qnamaker`
* Ex 2: `https://MyServiceThatDoesntNeedAppending.azurewebsites.net/qnamaker` remains the same
* Issue 2: previously if `QnAMakerService`'s first parameter receives a `source` that does not have a `hostname`, in the URL class's logic, it would throw invalid URL error when constructing URL + base to create `QnAMakerService.hostname`
* As per Steven's advice, **QnAMakerService now throws an error, clearly …
=> QnAMakerService correctly builds hostname URL & throws error w/o URL

libraries/botbuilder/package-lock.json, libraries/botbuilder/package.json, package-lock.json
Removes the NPM warning about filenamify already including types (added in [3.0.0](https://github.com/sindresorhus/filenamify/releases/tag/v3.0.0))
The breaking change from 2.0.0 to 3.0.0 is that Node.js 6 and up is required for 3.0.0. 
Breaking change from 3.0.0 to 4.0.0 is that Node.js 8 is required for 4.0.0.
- Bump `"filenamify"` dependency from `^2.0.0` to `^4.1.0` in `"botbuilder"`.
- Remove `"@types/filenamify"` dependency from `"botbuilder"`
Successfully rebuilt library and re-ran tests locally
=> upgrade filenamify to ^4.1.0 in botbuilder

libraries/botbuilder-ai/package.json, libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/package.json, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-testing/package.json, libraries/botbuilder/package.json, libraries/botframework-connector/package.json, libraries/testbot/package.json
The dependencies across our packages previously had "^" dependencies. 
```
dependencies": {
"botbuilder-core": "^4.5.0-RC1",
"botframework-connector": "^4.5.0-RC1",
},
```
This PR makes these *exact* dependencies, as we always version the set of BotBuilder packages together. 
```
dependencies": {
"botbuilder-core": "4.5.0-RC1",
"botframework-connector": "4.5.0-RC1",
},
```
The *actual* version number (4.4.0, 4.5.0, 4.5.1, etc) is stamped by the Build System.
=> Lock exact versions across dependencies

libraries/testbot/package.json
Version 4.1.6 does not exist. 
This is a regression from PR "Lock exact versions across dependencies"  https://github.com/microsoft/botbuilder-js/pull/1040 which broke the Run-JS-Functional-Tests-Linux build.
This fix should immediately fix the build. However, there are a lot of other dependencies specifying an exact version match of 4.1.6 instead of 4.5.0, which forces the code to run on 8-month-old packages.
I guess that means we will have to get good at rolling all dependencies every time new package versions are released. (I recall there is a tool to do this.)
=> Version fix: "botbuilder-testing": "4.5.0" from invalid version 4.1.6

libraries/testbot/package.json
This reverts PR https://github.com/microsoft/botbuilder-js/pull/1052 which turned out not to fix the build break in Run-JS-Functional-Tests-Linux #70275.
=> Revert dependency version change

libraries/botbuilder-lg/src/ImportResolver.ts, libraries/botbuilder-lg/src/lgResource.ts, libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/src/templateEngine.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/importExamples/import.lg, libraries/botbuilder-lg/tests/testData/examples/importExamples/import/import3.lg
Fix: https://github.com/microsoft/botbuilder-dotnet/issues/2233
Add source property in  `ImportResolverDelegate(string resourceId)` interface.
C# version: https://github.com/microsoft/botbuilder-dotnet/pull/2232
=> Fix ImportResolverDelegate bug

libraries/botbuilder-expression-parser/tests/badExpression.test.js, libraries/botbuilder-expression-parser/tests/expression.test.js, libraries/botbuilder-expression/src/extensions.ts
Before the change, the accessProperty function is case sensitive. After the change, the accessProperty function is case insensitive, which means getProperty(A, 'name') equals to getProperty(A, 'name'). This change is to alige with the C# version which is a key issue there.
=> [Expression] Change accessProperty to case insensitive

package.json
This fixes the versioning of dependencies. Bad dependency versions were breaking the BotBuilder-JS-4.future-daily build in the npm run postinstall step. 
Now that's fixed, the build makes it to the npm test step where 16 tests are failing.  See https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=71008
=> Fix versioning in 4.future

libraries/botbuilder-dialogs/src/componentDialog.ts, libraries/testbot/tests/dialogs/cancelAndHelpDialog.test.js, libraries/testbot/tests/dialogs/testData/bookingDialogTestCases.js
Reverted changes in https://github.com/microsoft/botbuilder-js/pull/1002 to componentDialog and updated TestBotTests.
It is not possible in the current implementation to return cancelled status from a componentDialog
=> Reverts changes PR #1002

libraries/botbuilder-lg/src/ImportResolver.ts, libraries/botbuilder-lg/src/templateEngine.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/templateEngineThrowException.test.js
fix: https://github.com/microsoft/botbuilder-dotnet/issues/2249
=> TemplateEngine.addText should require fullPath as id when using default fileResolver

libraries/botbuilder-expression-parser/tests/badExpression.test.js
Fixes #
- Due to the changes of moment package, the exception throwing of incorrect timestamp format was removed. The corresponding tests in js are removed. 
-
-
=> fix exception throwing of datetime format

libraries/botbuilder-core/src/internal.ts
Fixes #1073.
Corrected the capability check for `Proxy` object.
- Updated `internal.ts` to fix the `Proxy` object check by using `typeof Proxy !== 'undefined'`
=> Fix `Proxy` object capability check

libraries/botbuilder-expression/src/builtInFunction.ts
It looks like we are using newer node.js syntax stile for catching errors.
On 8.11 you are not allowed to catch without (e)
this doesn't work
'''
}
some code 
}  
catch { 
}
'''
@donglixp  we need to add test that include older versions of node.js
version 8 is still in LTS until April 2020.
I ran no testing.
=> added (e) to catch statements to work with older version of node.js

libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/TemplateRef.lg, libraries/botbuilder-lg/tests/testData/exceptionExamples/TemplateParamsNotMatchArgsNum.lg
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2344
We have a validation function in static checker period which is validating whether the parameters number from template definition is same with the number from the actual template call function. This PR is to make the validation always pass if the actual parameter number is zero. This is by design that no parameters mean parameters are inherited from caller's the scope.
=> [LG] Fix lg reference parameter issue

libraries/botbuilder-ai/package.json, libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/package.json, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-testing/package.json, libraries/botbuilder/package.json, libraries/botframework-config/package.json, libraries/botframework-connector/package.json, libraries/botframework-schema/package.json, libraries/functional-tests/functionaltestbot/package.json, libraries/testbot/package.json, package.json, tools/util/updateDependenciesInPackageJsons.js, transcripts/package.json
Implements #1084. 
Summary of changes:
- Updated packages.json files to set the versions of the modules to 4.0.0-local.
- Updated packages.json to reference 4.0.0-local (strict)
- Updated workspace packages.json "set-dependency-versions" to apply strict version dependencies rather than ^ versions to ensure we use the packages that are part of the build.
- Also, "set-dependency-versions" had references to packages that don't exist (like botbuilder-choices) and was missing other packages (like botbuilder-ai), I removed the packages that don't exist and added the missing ones.
Manually test daily and functional test builds (windows and linux) against the branch and they all passed.
=> Changed library versions to "4.0.0-local"

libraries/botbuilder-core/src/transcriptLogger.ts, libraries/botbuilder-core/tests/transcriptMiddleware.test.js
Fixes #1101
When sending an activity, a resource response id is returned from the service.  This PR adds that id to the activity being logged (if one is not present).
Added a unit test, and tested manually with a local bot.
=> Add Resource Response Id to cloned activities when logging

libraries/botbuilder-core/src/activityHandler.ts
Attempting to create an TeamsActivityHandler by extending the ActivityHandler was not possible, because of the inability to add a new handler since `ActivityHandler.on` is private. Additionally, creating `TeamsActivityHandler.run` was not possible because `ActivityHandler.handle` is private.
This PR makes those two methods protected, which allows for developers to meaningfully extend the ActivityHandler.
- Make `ActivityHandler.on` and `ActivityHandler.handle` protected methods instead of private.
FYI @johnataylor, @EricDahlvang, @Virtual-Josh
=> make on and handle in ActivityHandler protected for subclassing

libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts
Add type assertion BlobServiceAsync.
The error: src/azureBlobTranscriptStore.ts(338,26): error TS2345: Argument of type '{}' is not assignable to parameter of type 'BlobService'.
The broken build: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=77050&view=results
The broken commit: https://github.com/microsoft/botbuilder-js/commit/91453777fabe865be81717f9a244ac9c92324c85
=> Fix break in build BotBuilder-JS-master-CI

libraries/botbuilder-core/src/activityHandler.ts, libraries/botbuilder-core/src/transcriptLogger.ts, libraries/botbuilder-core/tests/transcriptMiddleware.test.js
cherry-picks #1117 and #1114 into the `4.5` branch for a patch release
These PRs are also for the ongoing Teams work. 
- `ActivityHandler.on()` and `ActivityHandler.handle()` are now `protected` instead of `private` which allows for meaningful subclassing of the ActivityHandler in JS.
- TranscriptLoggerMiddleware logs cloned activities with the actual `activity.id` returned from the service (via `ResourceResponse`)
- This helps address the issue that prompted microsoft/BotBuilder-Samples#1713
=> 4.5 cherry-pick ActivityHandler updates and TranscriptLoggerMiddleware bug fix

package.json
Using ESLint now lets TSLint deprecated, and can be easily removed.
**package.json**: removed references:
-  `tslint` 
- `tslint-microsoft-contrib`
All the tests run successfully.
=> Remove references to TSLint

libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts, libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts, libraries/botbuilder-dialogs/tests/choicePrompt.test.js, libraries/botbuilder-dialogs/tests/confirmPrompt.test.js, package.json
Currently, Confirm and Choice Prompts use an object with all-lowercase keys for localization:
```js
{
'es-es': { inlineSeparator: ', ', inlineOr: ' o ', inlineOrMore: ', o ', includeNumbers: true },
[...]
};
```
The locale used for the prompt is determined with something like this:
```js
ChoicePrompt.defaultChoiceOptions[locale]
```
If the `locale` is not all-lowercase, it defaults to `en-us`. This can be problematic because:
1. [`activity.locale` uses ISO 3166](https://github.com/microsoft/botbuilder-js/blob/5b8b7efef63d31dc32fe99050aa15e42378e832d/libraries/botframework-schema/src/activityInterfaces.ts#L115), which I believe [is normally recognized as all-caps](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
2. [WebChat sends the capitalized country-code …
=> Use Recognizers Cultures in Choice & Confirm Prompt

libraries/functional-tests/functionaltestbot/index.js
Fixes #1115, "Docs: InspectionMiddleware example code has a bug"
Updates how credentials are passed into InspectionMiddleware when added to the adapter. Also, removed unnecessary BotFramework-Connector dependency, following change.
- Changed:
`adapter.use(new InspectionMiddleware(inspectionState, userState, conversationState, new MicrosoftAppCredentials(process.env.MicrosoftAppId, process.env.MicrosoftAppPassword)));`  
to
`adapter.use(new InspectionMiddleware(inspectionState, userState, conversationState, { appId: process.env.MicrosoftAppId, appPassword: process.env.MicrosoftAppPassword }));`
- Removed:
`const { MicrosoftAppCredentials } = require('botframework-connector');`
=> Updated credentials passed into InspectionMiddleware

libraries/botbuilder-dialogs/src/choices/choiceFactory.ts, libraries/botbuilder-dialogs/src/prompts/prompt.ts, libraries/botbuilder-dialogs/tests/choicePrompt.test.js
This PR contains 2 separate foxes for choicePrompt:
1) Related to https://github.com/microsoft/botbuilder-js/issues/1175
- When a choicePrompt is sent with 'heroCard' styling and has an attacment, the attachment is not being sent. This fix ensures that both the hero card and attachment are sent back from the bot.
2) Discovered while testing the first fix - when choices are specified as an array of strings, they do not render in the hero card. The fix is to convert the string array to a Choice[] array in the ChoiceFactory class.
=> Choice prompt fixes 1175

libraries/botframework-schema/src/index.ts
Adding openApp action type to JS to keep C# parity
=> adding openApp card action type

libraries/botframework-streaming-extensions/src/HttpContentStream.ts, libraries/botframework-streaming-extensions/src/Interfaces/IHttpContentHeaders.ts, libraries/botframework-streaming-extensions/src/StreamingRequest.ts, libraries/botframework-streaming-extensions/src/StreamingResponse.ts
The C# implementation expects the content-type to be called "type".
=> Fix the content type on the wire to be consistent with the C# implemetation.

libraries/botbuilder-dialogs/tests/choicePrompt.test.js
Update to unit test for sending a choice prompt styled as a hero card and an attachment.
- Prior to this change, hero card and attachment were being sent back as two separate responses, one after another
- After adding type: ActivityTypes.Message to the attachment, both the attachment and hero card are contained in the same response, as expected.
=> Update choice prompt unit test for hero card prompt with attachment

libraries/botbuilder-core/package.json, libraries/botbuilder-testing/package.json, libraries/botbuilder/package.json, package.json
The lerna-build process found two vulnerabilities related to the `typedoc` package. Those vulnerabilities were fixed.
In addition, references to the old `botbuilder-core-extensions` package were deleted.
- `typedoc@^0.14.2` ==> `typedoc@^0.15.0`
- `typedoc-plugin-markdown@^2.0.6` ==> `typedoc-plugin-markdown@^2.2.10`
- `botbuilder-core-extensions` docs deleted from `botbuilder-core`, `botbuilder-testing`, and `botbuilder` packages.
Running `npm run build-docs` after changes
=> Fix typedoc vulnerability

libraries/botframework-streaming-extensions/src/WebSocket/WebSocketClient.ts, libraries/botframework-streaming-extensions/tests/WebSocket.test.js
WebSocketClient does not give an opportunity for the caller to handle disconnects. This PR changes the constructor to accept a callback thats invoked by WebSocketClient upon disconnect. This allows the caller decide the reconnect policy.
=> Let WebSocketClient take in a disconnection callback

libraries/botframework-connector/package.json
Leaking a testing lib in dependencies. Moved to devDependency.
- moved `nock` to `devDependencies` in botframework-connector
N/A - This does not add or change functionality. No new test coverage is needed.
=> move nock to devDependency

libraries/botframework-streaming-extensions/src/Payloads/HeaderSerializer.ts, libraries/botframework-streaming-extensions/tests/HeaderSerializer.test.js
The previous regex pattern used to determine if a header's identifier GUID was well formed enforced the timestamp based UUID rules as laid out in RFC 4122. The dotnet standard library used in C# bots only requires a GUID to match the 8-4-4-4-12 pattern to be valid, making them less restrictive. 
This change relaxes the regex matching to match any GUID following the 8-4-4-4-12 pattern for parity with the C# library.
=> Relax the rules for what counts as a well formed GUID.

libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts, libraries/botbuilder-azure/tests/TestData/expectedCalls.json, libraries/botbuilder-azure/tests/azureBlobTranscriptStore.test.js
fix for  https://github.com/microsoft/botbuilder-dotnet/issues/2120
js code was storing as number of seconds since 1970, and C# was using iso 1806
changed to use Date().toJSON() which is iso 1806
updated tests
=> normalize azure blob timestamp properties to be iso1806 format

libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/actionBasedMessagingExtensionFetchBot.ts, libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/actionBasedMessagingExtensionBot.ts, libraries/botbuilder/tests/teams/messagingExtensionAuth/src/messagingExtensionAuthBot.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js
- Update signature `onTeamsMessagingExtensionFetchTask()`
- Add more Tests for TeamsActivityHandler
- Change `onTeamsMessagingExtensionFetchTask()` signature **(Hackathon Feedback)**
From:
`protected async onTeamsMessagingExtensionFetchTask(context: TurnContext, query: MessagingExtensionQuery): Promise<MessagingExtensionActionResponse> {`
to:
`protected async onTeamsMessagingExtensionFetchTask(context: TurnContext, action: MessagingExtensionAction): Promise<MessagingExtensionActionResponse> {`
- Update scenarios with new signature for onTeamsMessagingExtensionFetchTask
- Add Teams-specific ConversationUpdate tests for TeamsActivityHandler
- Add final BadRequest tests for TeamsActivityHandler
- Add more NotImplemented tests for TeamsActivityHandler
=> [Teams] Update onTeamsMessagingExtensionFetchTask() & add tests for TeamsActivityHandler

libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/src/teamsInfo.ts, libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/actionBasedMessagingExtensionFetchBot.ts, libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/actionBasedMessagingExtensionBot.ts, libraries/botbuilder/tests/teams/adaptiveCards/src/adaptiveCardsBot.ts, libraries/botbuilder/tests/teams/fileUpload/src/fileUploadBot.ts, libraries/botbuilder/tests/teams/link-unfurling/src/linkUnfurling.ts, libraries/botbuilder/tests/teams/messagingExtensionAuth/src/messagingExtensionAuthBot.ts, libraries/botbuilder/tests/teams/messagingExtensionConfig/src/messagingExtensionConfigBot.ts, libraries/botbuilder/tests/teams/office365Card/src/office365CardsBot.ts, libraries/botbuilder/tests/teams/roster/src/rosterBot.ts, libraries/botbuilder/tests/teams/searchBasedMessagingExtension/src/teamsSearchExtensionBot.ts, libraries/botbuilder/tests/teams/taskModule/src/taskModuleBot.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js, libraries/botbuilder/tests/teamsInfo.test.js
- Rename the JavaScript non-event events as necessary to “handleTeams…”
- Refactor TeamsInfo, add TeamsInfo.getTeamMembers()
- TeamsInfo.getTeam*-methods optionally take a `teamId` parameter so users no longer need to mutate the `turnContext.activity.channelData.team` to get information for a specific team.
- Rename onTeams*-Invoke methods to handleTeams*
- Refactor TeamsInfo, add `TeamsInfo.getTeamMembers(context: TurnContext, teamId?: string)`
- TeamsInfo.getMembers() now calls TeamsInfo.getTeamMembers() if a teamId is detected off of the turnContext.
- TeamsInfo.getTeamDetails(), TeamsInfo.getTeamChannels() now optionally take a string in addition to the context parameter.
- Added tests for TeamsInfo changes
- Renamed methods in teamsActivityHandler.test.js
- Rebuilt all scenarios in …
=> [Teams] Rename onTeams*-Invoke methods to handleTeams*, add TeamsInfo.getTeamMembers

libraries/botbuilder-expression/src/builtInFunction.ts, libraries/botbuilder-lg/src/templateEngine.ts
Issue was that static check did not include custom function lookup.  This is correct in the dotnet repo.
Also fixed issue with the type for verification.
Fixes #1330
=> Fix for issue #1330.

libraries/botframework-streaming/package.json, package.json
- Add botframework-streaming to the  npm scripts
- Remove watershed dependency from the root of the repo
Build successfully ran, results are here: https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.6.0-preview.84994
=> Fix daily CI build after adding botframework-streaming to packages

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-streaming/src/webSocket/nodeWebSocket.ts, libraries/botframework-streaming/src/webSocket/wsNodeWebSocket.ts
- Add the ServiceUrl value from the claims in `BotFrameworkAdapter.authenticateConnection()` to have the bot call getToken() to refresh (or cache) a token.
- Refactor some code in `BotFrameworkAdapter.processRequest()` (streaming entrypoint)
- Move `ws` and `Watershed` Server/"WaterShed" construction into the WsNodeWebSocket and NodeWebSocket methods so the botframework-streaming library is browser compat (thanks for the report @ckkashyap!)
- Linting
=> [Streaming] Auth and browser compatibility fixes, linting, refactoring

libraries/botbuilder-ai/src/qnamaker-utils/activeLearningUtils.ts
Active learning low score variation multiplier value
- PreviousLowScoreVariationMultiplier to 0.7
- MaxLowScoreVariationMultiplier to 1.0
Fixes #
- 
-
-
=> [QnAMaker] Active learning low score variation multiplier value

libraries/botframework-expressions/package.json
Fixes #1369 
Add lru-cache as dependency since it's been exposed in expression library. 
Otherwise we will hit 
```
node_modules/botframework-expressions/lib/commonRegex.d.ts:9:27 - error TS7016: Could not find a declaration file for module 'lru-cache'. 
'C:/Users/donglei/code/testg/node_modules/lru-cache/index.js' implicitly has an 'any' type.
Try `npm install @types/lru-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'lru-cache';`
9 import * as LRUCache from 'lru-cache';
~~~~~~~~~~~
```
=> Fix @types/lru-cache missing in dependency

libraries/botframework-streaming/package.json
**Fixes:** 
Fixes build breaks in botframework-streaming caused by using devDependency of `typescript@3.1.1` and using Node.js 10.17.0.
Also removed `"engines"` from package.json, which should be used in applications, not libraries.
Got a repro working on local machine, and [build 88744](https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=88744).
=> [Engineering] Remove typescript devDependency from botframework-streaming

libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts, libraries/botbuilder-dialogs/src/prompts/promptCultureModels.ts, libraries/botbuilder-dialogs/tests/choicePrompt.test.js, libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
Parity with: https://github.com/microsoft/botbuilder-dotnet/pull/2943
* `ChoicePrompt`: Ensures that locale defaults to English and handles mapping to the nearest locale more gracefully
* `PromptCultureModels`: Implements our own version of [Recognizers-Text's `MapToNearestLanguage`](https://github.com/microsoft/Recognizers-Text/blob/7b20c1bbbfdebc3a801fbc61b094706ceebd7acf/.NET/Microsoft.Recognizers.Text/Culture.cs#L66) -- They added a bunch of other supported languages that will break this without doing this.
* `ChoicePromptTests`: Added a test to specifically set the Locale to null
* ConfirmPrompt already handled this fine and had tests for it
* I'll also work on some tests for PromptCultureModels, but I figured this should get out the door, first.
* Since Recognizers-Text added a …
=> Parity ChoicePrompt fix with dotnet

.gitignore
Revert [changes](https://github.com/microsoft/botbuilder-js/pull/1351/commits/e92608c8e5eacc239101d76088db5f334dd3a0e3) to root `.gitignore` that prevent developers from moving or creating `.ts` and `.js` files and adding them to git.
This PR does **not** require a new RC for 4.6.
=> [4.6, Engineering] Remove .js and .ts from .gitignore, change *.map to *.js.map

libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js, libraries/botframework-streaming/package.json
For 4.6.1
- Cherry-picks the `TeamsActivityHandler` not calling `defaultNextEvent` fix from #1390 
- Cherry-picks the `botframework-streaming` package.json fixes from #1392
Local tests are passing, `botframework-streaming` is building locally
=> [4.6.1] Manually Cherry-pick #1392 & #1390 to 4.6 branch

libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts, libraries/botbuilder-dialogs/src/prompts/promptCultureModels.ts, libraries/botbuilder-dialogs/tests/choicePrompt.test.js, libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
Per standup, this is a cherry pick against 4.6 of [this already-merged-with-master PR](https://github.com/microsoft/botbuilder-js/pull/1400)
---
Parity with: https://github.com/microsoft/botbuilder-dotnet/pull/2943
* `ChoicePrompt`: Ensures that locale defaults to English and handles mapping to the nearest locale more gracefully
* `PromptCultureModels`: Implements our own version of [Recognizers-Text's `MapToNearestLanguage`](https://github.com/microsoft/Recognizers-Text/blob/7b20c1bbbfdebc3a801fbc61b094706ceebd7acf/.NET/Microsoft.Recognizers.Text/Culture.cs#L66) -- They added a bunch of other supported languages that will break this without doing this.
* `ChoicePromptTests`: Added a test to specifically set the Locale to null
* ConfirmPrompt already handled this fine and had tests for it …
=> Choice prompt null locale fix [Cherry-pick against 4.6]

libraries/botbuilder/src/botFrameworkAdapter.ts
Fixes #1408 
Reverts a regression causing the botFrameworkAdapter to await websocket sessions for their duration, causing the adapter to act as a singleton shared by multiple sessions, which it does not have the logic to support.
=> Don't await for the duration of websocket sessions.

libraries/botbuilder/src/botFrameworkAdapter.ts
This reverts commit 3aea9c03bc5f12ce078630eda75ed624e45457ab.
Related to https://github.com/microsoft/botbuilder-js/issues/1408. The fix turned out to be in the creation of the BotFrameworkAdapter for each Upgrade request.
=> [Streaming] Revert "Don't await for the duration of websocket sessions. (#1412)"

libraries/botbuilder-ai/package.json, libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/package.json, libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-testing/package.json, libraries/botbuilder/package.json, libraries/botframework-config/package.json, libraries/botframework-connector/package.json, libraries/botframework-schema/package.json, libraries/botframework-streaming/package.json, package.json, transcripts/package.json
Fixes #1436
Pins `typescript` as devDependency in each library to fix bug of transpiling 4.6.1 libraries with 3.7.2.
- Remove `typescript@^3.5.2` devDependency from root package.json
- Create `typescript@3.5.3` devDependency in each library
- Change botbuilder, botbuilder-ai and botbuilder-dialogs dependencies in `transcripts/` to instead be `4.1.6`, not `^4.2.1` which led to `4.6.1` botbuilder-js libraries being hoisted at the root
- Fix uncaught import bug in `botbuilder-core` `SkypeMentionNormalizeMiddleware`
- The class was importing from `botbuilder-core`, the library it is in
=> [4.6.x] Pin TypeScript devDependency in each library. (Fixes #1436)

package.json
- Update root package.json "**set-dependency-versions**" script to use `${Version}` instead of `^${Version}`
- Update first half of "**set-dependency-versions**" script: 
- Replace `botbuilder-choices` & `botbuilder-prompts` with `botbuilder-ai` & `botbuilder-applicationinsights`
- Remove unnecessary packages from second half of `"set-dependency-versions"` script.
=> [4.6.x] Fix set-dependency-versions script

libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs-adaptive/src/sequenceContext.ts, libraries/botbuilder-dialogs/src/dialogContext.ts, libraries/botbuilder-dialogs/src/waterfallStepContext.ts
We were losing the configured memory scopes when AdaptiveDialog tried to convert a DialogContext into a SequenceContext.  These changes fix the issue by moving the task of cloning a DC into the DC class itself.
I also cleaned up the SequenceContext by adding a couple of static methods to seperate the logic for creating vs. cloning a SequenceContext.
Fixes #
- 
-
-
=> Fix issue with state manager not being clonned

libraries/botbuilder-ai/package.json, libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/package.json, libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-lg/package.json, libraries/botbuilder-testing/package.json, libraries/botbuilder/package.json, libraries/botframework-config/package.json, libraries/botframework-connector/package.json, libraries/botframework-expressions/package.json, libraries/botframework-schema/package.json, libraries/botframework-streaming/package.json, package.json, transcripts/package.json
Fixes #1436
- Cherry picks #1437, and #1438 to master
- Add `typescript@3.5.3` devDependency to `botbuilder-lg` and `botframework-expressions`
See #1437, #1438 for more information
=> [R7, Cherry-pick] Cherry-pick TypeScript 3.5.3 pin from 4.6 branch

libraries/botbuilder-ai/package.json, libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/package.json, libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-testing/package.json, libraries/botbuilder/package.json, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/streaming/botFrameworkAdapterStreaming.test.js, libraries/botbuilder/tests/streaming/mockHttpRequest.js, libraries/botbuilder/tests/streaming/mockNetSocket.js, libraries/botframework-config/package.json, libraries/botframework-connector/package.json, libraries/botframework-schema/package.json, libraries/botframework-streaming/package.json, libraries/botframework-streaming/src/index.ts, libraries/botframework-streaming/src/interfaces/INodeBuffer.ts, libraries/botframework-streaming/src/interfaces/INodeIncomingMessage.ts, libraries/botframework-streaming/src/interfaces/INodeSocket.ts, libraries/botframework-streaming/src/interfaces/index.ts, libraries/botframework-streaming/src/webSocket/factories/nodeWebSocketFactory.ts, libraries/botframework-streaming/src/webSocket/factories/nodeWebSocketFactoryBase.ts, libraries/botframework-streaming/src/webSocket/nodeWebSocket.ts, package.json, transcripts/package.json
Fixes #1386
Change entry point for WebSocket Streaming connections from `processActivity()` to only `useWebSocket()`.
useWebSocket() also no longer relies on `restify` to expose the socket and head for WebSocket consumption. As such, it is now a method that should be called in a handler for the ['upgrade'](https://nodejs.org/api/http.html#http_event_upgrade_1) event. (See **Testing** for more information)
useWebSocket() continues to perform the authentication of the WebSocket Upgrade request from the client, and will send back the correct status code and close the socket connection if the `authenticateConnection()` call fails.
- BotFrameworkAdapter.useWebSocket() signature change
- **from** `public async useWebSocket(req: WebRequest, res: WebResponse, logic: (context: TurnContext) => …
=> [Streaming, Preview] rewrite useWebSocket for low-level usage, remove from processActivity

libraries/botbuilder/src/inspectionMiddleware.ts, libraries/botbuilder/tests/inspectionMiddleware.test.js
=> allows Inspection to attach anywhere within a Teams Team

libraries/botbuilder-dialogs/src/prompts/skillsHelpers.ts, libraries/botbuilder-dialogs/tests/internalSkillHelpers.test.js, libraries/botframework-connector/src/auth/emulatorValidation.ts, libraries/botframework-connector/src/auth/index.ts, libraries/botframework-connector/src/auth/jwtTokenExtractor.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts, libraries/botframework-connector/src/auth/microsoftAppCredentials.ts, libraries/botframework-connector/src/auth/skillValidation.ts, libraries/botframework-connector/tests/appCredentials.test.js, libraries/botframework-connector/tests/auth.test.js, libraries/botframework-connector/tests/skillValidation.test.js
Fixes #1310 
- Add SkillValidation 
-
-
Need to finish porting Python tests for SkillValidation
=> [Skills] Add SkillValidation class

libraries/botframework-connector/src/auth/channelValidation.ts, libraries/botframework-connector/src/auth/emulatorValidation.ts, libraries/botframework-connector/src/auth/enterpriseChannelValidation.ts, libraries/botframework-connector/src/auth/governmentChannelValidation.ts, libraries/botframework-connector/src/auth/jwtTokenExtractor.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts
Fixes #
Use AuthenticationConfiguration in the `botframework-connector` library.
- 
-
-
=> [Skills] Use AuthenticationConfiguration

libraries/botbuilder/src/botFrameworkAdapter.ts
Refactoring around BotFrameworkAdapter to add Skill support
- ClaimsIdentity and a ConnectorClient are now cached in the `context.turnState` in `processActivity()`
- **BotFrameworkAdapter.createConnectorClient()**
- returns result from createConnectorClientInternal()
- **private createConnectorClientInternal(serviceUrl: string, credentials: AppCredentials)**
- Contains logic formerly in createConnectorClient()
- If the serviceUrl is a streaming URL, it uses the StreamingHttpClient instead of the default HttpClient from ms-rest. (#1464)
- **public async createConnectorClientWithIdentity(serviceUrl: string, identity: ClaimsIdentity)**
- Creates a ConnectorClient and uses the ClaimsIdentity to determine if the request was a Skills request
- **private async getAppCredentials(appId: string, …
=> [Skills] add skill support in BotFrameworkAdapter

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/channelServiceRoutes.ts
- Add `params?: any` and `query?: any` to WebRequest interface.
- Improve error handling in `ChannelServiceRoutes`
=> [Skills] Better exception handling and typing

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-connector/src/auth/appCredentials.ts, libraries/botframework-connector/src/auth/skillValidation.ts
Fixes #1310
- BotFrameworkAdapter caches a ConnectorClient via the processActivity() method with the correct scopes for skills on the TurnContext.turnState.
- BotFrameworkAdapter also caches the received ClaimsIdentity on TurnContext.turnstate via the processActivity().
- AppCredentials static Token Cache is used now additionally uses the scope to store the adal TokenResponse
- AppCredentials sets the version explicitly for the AAD API Version to `'1.5'` instead of the default `'1.0'`
Tested multiple streaming connections
Tested with JS parent to JS Skill.
=> [Skills] Refactor BFAdapter for Skills with Auth

libraries/botframework-streaming/src/interfaces/ITransport.ts, libraries/botframework-streaming/src/namedPipe/namedPipeTransport.ts, libraries/botframework-streaming/src/webSocket/webSocketTransport.ts, libraries/botframework-streaming/tests/NamedPipe.test.js, libraries/botframework-streaming/tests/WebSocket.test.js
Fixes #1427
Convert `isConnected` function into getter.
Touched up unit tests to not call isConnected, tested with multiple DLS connections to a bot.
=> [Streaming] change isConnected() to a getter

package.json, tools/util/updateDependenciesInPackageJsons.js
Adjusted dependency updater to take a preview version for a hardcoded list of preview packages.
This is not ideal and is a spot fix for 4.7 release.
- update ./tools/utils/updateDependenciesInPackageJsons.js to take in an env var for preview version and conditionally use that version for a fixed set of packages
None. Will test via CI pipeline. 🤡
=> build: add preview package support

libraries/botbuilder-dialogs/package.json
The cldr-data files were not included in the `npm pack` which meant the `botbuilder-dialogs` library would fail at runtime.
Manually packed and inspected contents which contained the `vendor/` folder as expected.
=> [Dialogs] add vendor/ to botbuilder-dialogs incl. files

libraries/botframework-streaming/src/namedPipe/namedPipeClient.ts, libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts
Fixes duplicate https://github.com/Microsoft/TypeScript/issues/18678 for NamedPipeTransport in Streaming library.
- Fix incorrect relative imports of NamedPipeTransport. 
Build and manually inspected code for irregularities
=> fix casing on relative import references for NamedPipeTransport

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botbuilder/src/skills/skillHandler.ts, libraries/botbuilder/src/streaming/streamingHttpClient.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-connector/src/auth/appCredentials.ts, libraries/botframework-connector/src/auth/certificateAppCredentials.ts, libraries/botframework-connector/src/auth/microsoftAppCredentials.ts, libraries/botframework-connector/tests/appCredentials.test.js, libraries/botframework-streaming/package.json
- Fix setting of OAuthScope in AppCredentials.
- Add Setter and Getter to AppCredentials for _oAuthScope (via OAuthScope)
- Setter now reconfigures the tokenCacheKey for the AppCreds instance.
- Fix import in StreamingHttpClient
- Fix not including @types/ws as dependency in botframework-streaming
Manually tested auth piece for skills, added tests for AppCredentials and refactor in BotFrameworkAdapter.
@Batta32, @lzc850612 FYI
=> fix auth bug, streaming dependencies, add tests

libraries/botbuilder-lg/src/customizedMemory.ts, libraries/botframework-expressions/src/builtInFunction.ts, libraries/botframework-expressions/src/memory/composedMemory.ts, libraries/botframework-expressions/src/memory/memoryInterface.ts, libraries/botframework-expressions/src/memory/simpleObjectMemory.ts
ref: https://github.com/microsoft/botbuilder-dotnet/issues/3162
=> Make IMemory interface follow the convention instead of returning tuple

libraries/botframework-expressions/package.json
close: #1553
We have already fixed this issue in this pr: #1368
But for some merging issue, we lost it.
=> move @types/lru-cache from devdependency to dependency

libraries/botframework-streaming/src/interfaces/IBrowserFileReader.ts, libraries/botframework-streaming/src/interfaces/IBrowserWebSocket.ts, libraries/botframework-streaming/src/interfaces/index.ts, libraries/botframework-streaming/src/utilities/doesGlobalFileReaderExist.ts, libraries/botframework-streaming/src/utilities/doesGlobalWebSocketExist.ts, libraries/botframework-streaming/src/utilities/index.ts, libraries/botframework-streaming/src/utilities/isBrowser.ts, libraries/botframework-streaming/src/webSocket/browserWebSocket.ts, libraries/botframework-streaming/src/webSocket/webSocketClient.ts, libraries/botframework-streaming/tests/InternalUtilities.test.js, libraries/botframework-streaming/tsconfig.json
Fixes #1565 in `4.7` branch.
For the 4.7.0 release, botbuilder and bf-streaming shipped with an inadvertent requirement for TypeScript developers to include the `"dom"` lib in the developer's own `tsconfig.json`.
This problem arises for users even when they don't take a direct dependency on botframework-streaming. Building a library that uses only botbuilder fails without including `"dom"`. (https://github.com/howdyai/botkit/issues/1894)
Additionally, another side effect of relying on WebSocket and FileReader types and definitions via TypeScript leads us to potential breaking changes in the future. The `"dom"` types included are also tightly coupled with the version of TypeScript, so relying on these types could allow the code to successfully transpile, but not actually work at runtime.
- …
=> remove "dom" from bf-streaming tsconfig and refactor code

libraries/botframework-streaming/src/interfaces/IBrowserFileReader.ts, libraries/botframework-streaming/src/interfaces/IBrowserWebSocket.ts, libraries/botframework-streaming/src/interfaces/index.ts, libraries/botframework-streaming/src/utilities/doesGlobalFileReaderExist.ts, libraries/botframework-streaming/src/utilities/doesGlobalWebSocketExist.ts, libraries/botframework-streaming/src/utilities/index.ts, libraries/botframework-streaming/src/webSocket/browserWebSocket.ts, libraries/botframework-streaming/src/webSocket/webSocketClient.ts, libraries/botframework-streaming/tests/InternalUtilities.test.js, libraries/botframework-streaming/tsconfig.json
Fixes #1565 in `master` by cherry-picking #1575
___
For the 4.7.0 release, botbuilder and bf-streaming shipped with an inadvertent requirement for TypeScript developers to include the `"dom"` lib in the developer's own `tsconfig.json`.
This problem arises for users even when they don't take a direct dependency on botframework-streaming. Building a library that uses only botbuilder fails without including `"dom"`. (https://github.com/howdyai/botkit/issues/1894)
Additionally, another side effect of relying on WebSocket and FileReader types and definitions via TypeScript leads us to potential breaking changes in the future. The `"dom"` types included are also tightly coupled with the version of TypeScript, so relying on these types could allow the code to successfully transpile, but not …
=> [Cherry-pick to master] remove "dom" from bf-streaming tsconfig and refactor code

libraries/botbuilder/src/skills/skillHandler.ts, libraries/botbuilder/tests/skills/skillHandler.test.js
Fixes #1580 in `4.7`
Add `AppCredentials.trustServiceUrl()` call in SkillHandler to trust serviceUrl that was received in message from channel.
This allows for all instances of the parent bot to fetch a token when it attempts to forward the activity from the Skill to the User (via the use of the SkillHandler class).
- Issue: https://github.com/microsoft/botbuilder-dotnet/pull/3244
- PR: https://github.com/microsoft/botbuilder-dotnet/issues/3245
Manually tested by having one parent bot use the endpoint of the **second** parent bot as the serviceUrl for activities sent to the skill.
Added specific unit test for verifying the serviceUrl is trusted after SkillHandler.processActivity() is run.
=> [Skills] TrustServiceUrl from original conversationReference in SkillHandler

libraries/botbuilder/src/skills/skillHandler.ts, libraries/botbuilder/tests/skills/skillHandler.test.js
=> [Skills] TrustServiceUrl from original conversationReference in SkillHandler 

libraries/botbuilder-ai/tsconfig.json, libraries/botbuilder-applicationinsights/tsconfig.json, libraries/botbuilder-azure/tsconfig.json, libraries/botbuilder-core/tsconfig.json, libraries/botbuilder-dialogs/tsconfig.json, libraries/botbuilder-lg/tsconfig.json, libraries/botbuilder-testing/tsconfig.json, libraries/botbuilder/tsconfig.json, libraries/botframework-config/tsconfig.json, libraries/botframework-connector/tsconfig.json, libraries/botframework-expressions/tsconfig.json, libraries/botframework-schema/tsconfig.json, libraries/botframework-streaming/tsconfig.json
Enables `"go to definition"` from supporting editors (e.g. VS Code) to go straight to the source code instead of the `.d.ts` files.
[TypeScript Compiler Options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
Thanks for the tip @a-b-r-o-w-n 🚀 
- Add `"declarationMap": true,` to libraries' tsconfig.json files.
=> [QoL] add declarationMap to tsconfig.json in libraries

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botbuilder/src/channelServiceRoutes.ts, libraries/botbuilder/src/index.ts, libraries/botbuilder/src/interfaces/index.ts, libraries/botbuilder/src/interfaces/invokeResponse.ts, libraries/botbuilder/src/interfaces/webRequest.ts, libraries/botbuilder/src/interfaces/webResponse.ts, libraries/botbuilder/src/skills/skillHttpClient.ts, libraries/botbuilder/src/streaming/constants.ts, libraries/botbuilder/src/streaming/index.ts, libraries/botbuilder/src/teamsActivityHandler.ts
Cleanup in `botbuilder`
- https://github.com/microsoft/botbuilder-js/commit/1380be6b2a93e8e107673d52db4b363a0f4dfcc5
- Move `InvokeResponse`, `WebRequest`, `WebResponse` into individual files in new `interfaces/` folder.
- https://github.com/microsoft/botbuilder-js/commit/ec07d7eee9663a1b09b5f764d868a1daf45f3dc7
- Move **INTERNAL** streaming constants out of BotFrameworkAdapter and into `streaming/constants.ts`
Rebuilt libraries and locally re-ran tests.
=> Cleanup in botbuilder

libraries/botbuilder-dialogs/src/waterfallDialog.ts
See files for small fixes
Edit: My second commit fixes an actual bug rather than just cleaning up code. If you cancelled a waterfall during a named step (a step not defined by an anonymous function), the telemetry logger would treat it as an unnamed step. I noticed that by reading the code. The bug is not in the other repos though it may have originated by copying code from Python and not adapting it correctly.
=> Declare return types in waterfallDialog.ts

libraries/browser-functional-tests/package.json
The Browser Functional Test build pipeline is falling due to the chrome driver version. 
Google Chrome updated to version 79.0.0 a few days ago. 
This pull request updates the version of the `chromedriver` dependency to the current stable version `79.0.0`
- Update chrome driver version
=> Fix Browser Functional Test Build Pipeline

libraries/botbuilder-dialogs/scripts/gen-cldr-data.js, libraries/botbuilder-dialogs/src/i18n.ts, libraries/botbuilder-dialogs/src/prompts/numberPrompt.ts, libraries/botbuilder-dialogs/vendor/cldr-data/main/fr/numbers.json
Fixes #1484 
Adds French language support to NumberPrompt. This is already supported in Confirm and Choice prompts, as well as the C# SDK.
=> Fresh French Number PR

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/streaming/streamingHttpClient.ts, libraries/botbuilder/tests/streaming/botFrameworkAdapterStreaming.test.js, libraries/botbuilder/tests/streaming/streamingHttpClient.test.js, libraries/botframework-streaming/src/interfaces/IStreamingTransportServer.ts, libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts, libraries/botframework-streaming/src/webSocket/webSocketServer.ts, libraries/botframework-streaming/tests/NamedPipe.test.js, libraries/botframework-streaming/tests/WebSocket.test.js
* add `IStreamingTransportServer.isConnected?: boolean`
* add isConnected to WebSocketServer
* add isConnected to NamedPipeServer
* expose `isConnected` via `BotFrameworkAdapter.isStreamingConnectionOpen`
* this should be used used in `onTurnError` to avoid throwing an error due to socket closures
* add check to verify socket connection is open in sendActivities
* add falsy check tests
To repro, setup an JS Echo bot with the following code in the onMessage handler:
```js
constructor() {
super();
this.onMessage(async (context, next) => {
const replyText = `Echo: ${ context.activity.text }`;
const promisifyTimeout = (delay) => {
return new Promise(resolve => setTimeout(resolve, delay));
};
await promisifyTimeout(5000);
await context.sendActivity(MessageFactory.text(replyText, replyText)); …
```
=> [Streaming] add generic socket closure handling

libraries/botframework-expressions/src/builtInFunction.ts, libraries/botframework-expressions/tests/badExpression.test.js, libraries/botframework-expressions/tests/expression.test.js
Split function now can take one or two parameters.
=> Parity of split function with C# in Expression

libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/IsTemplate.lg
port https://github.com/microsoft/botbuilder-dotnet/issues/2904
=> add isTemplate function

libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/StructuredTemplate.lg
=> treat everything after first '=' as value for the property

libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botbuilder/tests/botFrameworkHttpClient.test.js
=> return http state

libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/src/memory/simpleObjectMemory.ts, libraries/adaptive-expressions/tests/expression.test.js, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/MemoryAccess.lg
=> [Port] Add tests around memory access path

libraries/botbuilder-core/src/showTypingMiddleware.ts
Fixes #726 
Typing indicator works as normal, unless an error is thrown, in which case it is now re thrown to the adapter.
=> Updated ShowTypingMiddleware to re throw errors

libraries/botframework-streaming/.gitignore, libraries/botframework-streaming/package.json, libraries/botframework-streaming/src/index-browser.ts, libraries/botframework-streaming/src/webSocket/index-browser.ts, libraries/botframework-streaming/tsconfig-browser.json
Fixes #1669 
Fixes #1670
Creates a browser/es5 output of botframework-streaming
- Stop exporting Node.js-specific bits in the browser packages.
@ckkashyap?
=> create browser (es5) output in botframework-streaming

libraries/adaptive-expressions/src/parser/expressionEngine.ts, libraries/botbuilder-lg/package.json, libraries/botbuilder-lg/src/lgFile.ts, libraries/botbuilder-lg/src/lgParser.ts, libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/CustomFunction.lg
Plumb expression engine throughout to enable custom functions.
Includes custom function unit test.
=> Plumb custom functions throughout.

libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/tests/expression.test.js
Parity the result of lastIndexOf  function when either arg is null
lastIndexOf(hello, null) will return 4
lastIndexOf(null, null) will return 0
=> [Expression] Fix result when the second arg is null in lastIndexOf function

libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/src/expressionType.ts, libraries/adaptive-expressions/tests/expression.test.js
Enable indicesAndValues to work over objects.
Add flatten(array, [depth]) which will flatten all arrays or to optional depth.
Add unique(array) which will remove duplicate items from array.
Fixes #
Tests for all three fesatures.
=> Initial check-in of flatten, unique and

libraries/botframework-config/src/botConfiguration.ts, libraries/botframework-config/src/botConfigurationBase.ts, libraries/botframework-config/src/schema.ts
Fixes #1559
Marked bot config classes as deprecated. We will need to manually run `npm deprecate botframework-config` after these changes are published to NPM.
=> Marked config classes as deprecated

libraries/botbuilder-core/src/telemetryLoggerMiddleware.ts
Fixes #1791 
Add null check for activity.from in telemetryLoggerMiddleware.
=> Add null check for from

libraries/botbuilder-ai/src/qnamaker-interfaces/qnamakerOptions.ts
Fixes #1808
JS repo doesn't explicitly let users know that the valid `scoreThreshold` range is from 0.0 to 1.0, unlike the C# repo.
Updated the `QnAMakerOptions.scoreThreshold` doc to specify range explicitly, in line with the docs on the dotnet side
n/a -- it's a comment change
=> Update docs on valid scoreThreshold range for QnAMakerOptions

libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botbuilder/tests/botFrameworkHttpClient.test.js
=> add protected method to allow injection of cert by overriding

libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts, libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
Fixes #1798 
If the user sends an attachment in response to the ConfirmPrompt, an exception is thrown and the retry prompt is not shown.
```js
TypeError: Cannot read property 'toLowerCase' of undefined
```
`toLowerCase` is called within a `Recognizers-Text` package, so before calling it, we just return `{ succeeded: false }` if `activity.text` is null
Added:
```js
if (utterance == null) {
return result;
}
```
Added a test.
Before:
After:
=> Added null check for activity.text in ConfirmPrompt

libraries/botbuilder-dialogs/src/skillDialog.ts, libraries/botbuilder-dialogs/tests/skillDialog.test.js
Increase test coverage and fix bugs for Skill-related classes (e.g. SkillDialog)
- `SkillDialog.postToSkill()` bugfix: `skillEndpoint` was being used instead of `skillHostEndpoint`
- Add tests for **SkillDialog**
- `validateBeginDialogArgs()`
- `postToSkill()`
=> Add tests for SkillDialog

libraries/botbuilder-dialogs/src/dialog.ts, libraries/botbuilder-dialogs/src/dialogHelper.ts, libraries/botbuilder-dialogs/src/index.ts, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/src/prompts/skillsHelpers.ts, libraries/botbuilder-dialogs/src/skillDialog.ts, libraries/botbuilder-dialogs/tests/skillDialog.test.js
Fixes #1860
- Add new public helper method **runDialog** (C# parity method is [DialogExtensions.RunAsync](https://github.com/microsoft/botbuilder-dotnet/blob/276ffeadd77e2b34a6bbaa64bc4d72f1ff7d748f/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs#L31))
- `runDialog(dialog: Dialog, context: TurnContext, accessor: StatePropertyAccessor<DialogState>): Promise<void>`
- Add resumeDialog, repromptDialog to SkillDialog
- add tests for new methods
=> Add interruption support to SkillDialog and runDialog helper method

libraries/botbuilder-dialogs/src/dialogHelper.ts, libraries/botbuilder-dialogs/tests/dialogHelper.test.js, libraries/botbuilder/src/botFrameworkHttpClient.ts
Fixes #1895,
Fixes #1897
Port of https://github.com/microsoft/botbuilder-dotnet/pull/3540 to JS
- Follow spec for `callerId`
- Inspect EndOfConversation activities for routing in `runDialog()`
- Add parameter validation checks and tests to `runDialog()`
=> fix runDialog helper, fix callerId generation in BotFrameworkHttpClient

libraries/botbuilder-core/src/index.ts, libraries/botbuilder-core/src/skills/botFrameworkClient.ts, libraries/botbuilder-dialogs/src/dialogHelper.ts, libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botbuilder/src/skills/skillHttpClient.ts
Fixes breaking changes caused by adding `<T>` to BotframeworkClient and its subclasses
Adds overloads to BotFrameworkHttpClient and SkillHttpClient
**Those using the base implementation of the class should not have to change any code.** 
____
- **BotFrameworkClient is now an interface with a Union-type for the postActivity() property.**
- The only difference in the union type is that one of the subtypes takes a template (`T`) for its return value
- The implementation of the interface would look like this: `postActivity<T>(...): Promise<InvokeResponse<T>>`
- The union type is for enabling future implementations of BotFrameworkClient to not have to implement an unused abstract method while not breaking current implementations of BotFrameworkClient
- Fix bug in `runDialog()`
<details> …
=> Revert breaking changes around BotFrameworkClient implementations

libraries/botbuilder/src/interfaces/webRequest.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/1589
Make `on(...` optional on `WebRequest`
=> make WebRequest.on optional

.gitignore, consumer-test/test.ts, libraries/botbuilder-core/src/appCredentials.ts, libraries/botbuilder-core/src/coreAppCredentials.ts, libraries/botbuilder-core/src/extendedUserTokenProvider.ts, libraries/botbuilder-core/src/index.ts, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/botFrameworkHttpClient.ts, package.json, run-consumer-test.js
Fixes #1901
@Batta32
- 
- loosen Cache requirements in BFHttpClient
-
=> Fix AppCredentials compilation error in BotFrameworkAdapter

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js
Fixes #1890
Mirror changes in C# by conditionally trusting a serviceUrl in ` BotFrameworkAdapter.continueConversation()`.
If `BotFrameworkAdapter.credentials.appId` is truthy, trust the serviceUrl.
Added tests
Port of https://github.com/microsoft/botbuilder-dotnet/pull/3532
=> trust reference.serviceUrl if credentials.appId is truthy

.gitignore, consumer-test/test.ts, libraries/botbuilder-core/src/coreAppCredentials.ts, libraries/botbuilder-core/src/extendedUserTokenProvider.ts, libraries/botbuilder-core/src/index.ts, libraries/botbuilder-core/src/skills/botFrameworkClient.ts, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botbuilder/src/skills/skillHttpClient.ts, package.json, run-consumer-test.js
=> Cherry-picks #1902 and #1894 to master

libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts
Fixes #
When OAuthAppCredentials is passed in as part OAuthPromptSettings, do not set SignInLink to be empty as Emulator/other first party channels will ignore this and get a SignInLink without the additional OAuthAppCredentials setting.
- 
-
-
=> [OAuth]do not set signInLink to empty when OAuthAppCredentials is set

libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/src/templateExtensions.ts, libraries/botbuilder-lg/src/templateParser.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tsconfig.json, libraries/botbuilder/src/interfaces/webRequest.ts
1. Update LG tsconfig file
- remove unused tslint plugin
- change target from 'ESNext' to 'es6'
2. Migrate C#-style comments to js-stype comments
=> update lg tsconfig and comments

libraries/botbuilder-testing/src/dialogTestClient.ts, libraries/botbuilder-testing/tests/dialogTestClient.test.js
Fixes #1891
- Expose `public dialogContext` getter, add `private _dialogContext` with initial value of `null`.
- Minor linting fixes
Added a new test for inspecting`DialogTestClient.dialogContext`.
=> port dotnet DialogTestClient DialogContext changes

libraries/adaptive-expressions/src/extensions.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
=> [port] fix index access bug 

libraries/adaptive-expressions/src/expressionFunctions.ts
some small fixes.
close: #1943
=> [port] remove dynamic

libraries/botbuilder-ai/src/luisRecognizerOptionsV3.ts
Fixes #1946
If LUIS is not configured correctly, calls to the service will sometimes return an .error result. This should be checked and properly raised,
Throw the error, if it exists.
All tests pass.
Does not need a C# Port](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs#L125)
Also doesn't need a Python port. I can't seem to find where in the code this is covered, but I tested and the error thrown is appropriately, `Operation returned an invalid status code 'PermissionDenied'`
=> added LUIS error handling

libraries/botbuilder-lg/src/template.ts, libraries/botbuilder-lg/src/templateExtensions.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tests/lg.test.js
close: #1954
Originally, we treat LG file as the combination of templates and use empty string as the separator.
From now on separator "\r\n" would be used.
So, if we update a template with the body "- A", we would always get the body "- A" but not "-A\r\n" in any case. This idempotent relationship will greatly increase robustness and consistency
=> Make the CRUD of the template consistent

libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/src/templatesParser.ts
Fixes #1955
The import chain of LG file is like a graph, there may be various reference logic.
Antlr's parse takes a lot of time in it, If LG SDK can cache the results of Antlr parse(single call life cycle), the performance will be greatly improved.
After experiments, it can save more than half of time for complex lg call chain.
issue link: https://github.com/microsoft/BotFramework-Composer/issues/2374
=> [PORT] cache Antlr parse result

libraries/adaptive-expressions/src/expression.ts, libraries/adaptive-expressions/src/expressionEvaluator.ts, libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/src/index.ts, libraries/adaptive-expressions/src/memory/simpleObjectMemory.ts, libraries/adaptive-expressions/src/options.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
fixes: #1966 
Add an optional parameter options in tryEvaluate.
Inside options, we allows user to set a callback function which been called whenever there is a null found in memory path, except for those in boolean context.
=> [PORT] Update IMemory interface and tryEvaluate for expression

libraries/adaptive-expressions/src/parser/expressionParser.ts, libraries/botbuilder-lg/src/LGFileParser.g4, libraries/botbuilder-lg/src/generated/LGFileParser.ts, libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/tests/lgDiagnostic.test.js, libraries/botbuilder-lg/tests/testData/examples/StructuredTemplate.lg, libraries/botbuilder-lg/tests/testData/exceptionExamples/ErrorStructuredTemplate.lg
Close: #1973 
1. Support newline in structure lg content
```
> this is executable
[Activity
text = hi
speak = hi
]
```
2. Add more catchable errors
for example:
```
[Activity]
- hi
```
Originally, it would throw a syntax error, but now, some readable errors would be thrown.
=> [PORT]Loose grammar to make Structure LG more torren

libraries/adaptive-expressions/src/expression.ts, libraries/adaptive-expressions/src/functionTable.ts, libraries/adaptive-expressions/src/index.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/customFunction2.lg
Fixes #1931 
Make customized function in LG and expression easier by accepting just a lambda.
At the cost of expose FunctionTable instead of a generic IDictionary.
Now you can do
```JavaScript
Expression.functions.add('contoso.sqrt', (args) => {
let result = null;
if (args[0] !== undefined ) {
const inputFloat = parseFloat(args[0]);
result = Math.sqrt(inputFloat);
}
return result;
});
```
to add a new function
=> [Port] make custom function easier

libraries/botbuilder-lg/package.json, libraries/botbuilder-lg/tests/ActivityFactory.test.js
Originally LG depends on "botbuilder-core" to achieve the bot schema to build the Activity througth `ActivityFactory`.
But now, `ActivityFactory` has been moved to "botbuilder-core" library, so, there is no need to depends on any bot library in LG. Which would keep LG as a pure and independent library.
=> Remove "botbuilder-core" dependency from LG

libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/src/templateErrors.ts, libraries/botbuilder-lg/tests/lgDiagnostic.test.js
close: #1988
1. Originally LG use the end white space of error message to separate the error layer to make it more readable.
But it is strange to have such message. So, we concat the error stack at runtime with white space.
2. There are many duplicate code to build the stack error message,  extract them make the code clean and pure.
=> [PORT]Refine Error message and remove duplicate code

libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/Expand.lg
Fixes #3523 https://github.com/microsoft/botbuilder-dotnet/issues/3523
Fixes #2014 
Refactor lg expander to support full functions of LG and fix several issues such as excape, double quotation. Also change the return type from string array to object array.
Corresponding test cases are added in lg.test.js
=> refactor expander

libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
close: #1776
At first, LG `ActivityFactory` use `MessageFactory.Text()` to generate message activity result from LG output, but `MessageFactory.Text()` would inject `inputhint = expectingInput ` into activity, and the prompt of input relies on this feature.
Then we found there is no reason to add `inputhint` into pure text activity, so we removed it.
At the same time, we should update adaptive inputs to set `inputHint = expectingInput` whenever we are issuing a prompt or reprompt (unrecognized/ invalid prompt).
=> [PORT] update adaptive inputs to set inputHint = expectingInput

libraries/browser-functional-tests/package.json
Fixes broken browser-functional-tests
e.g. https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=122521&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=05a7d88e-decf-5c29-7849-5d16879a64a4&l=32
- bump devDependency chromedriver to `"^81.0.0"` in `browser-functional-tests` package
=> bump chromedriver to ^81.0.0

libraries/botbuilder-dialogs-adaptive/tests/LGGenerator.test.js
Split up monolithic tests into individual test cases in LGLanguageGenerator which were causing non-deterministic CI failures.
=> Refactor LGLanguageGenerator tests to address timeout failures

libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #2056
Fix checking null value in expression
=> [PORT][Expression] fix null check in expression

libraries/botbuilder-dialogs-adaptive/tests/LGGenerator.test.js
Fixes [test timeout](https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=125615&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=9a2d4836-1661-5df9-4d60-5f662004d588&l=3311) that caused Build 1255615's failure for commit https://github.com/microsoft/botbuilder-js/commit/18cb9822fe4f1a745158ae532872c9db4f3f6e29
Same refactoring as https://github.com/microsoft/botbuilder-js/pull/2076
=> refactor TestMultiLangImport tests

libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/tests/oauthPrompt.test.js, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/interfaces/connectorClientBuilder.ts, libraries/botbuilder/src/interfaces/index.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/1991
- Create `ConnectorClientBuilder` in botbuilder package with property `createConnectorClientWithIdentity`
- `createConnectorClient` is a synchronous method on the BotFrameworkAdapter, hence the change in name
- `createConnectorClientWithIdentity` is a property, not a function so that we can deprecate it (and make it optional) if we want to continue using the `ConnectorClientBuilder` interface
- Port OAuthPrompt changes (https://github.com/microsoft/botbuilder-dotnet/pull/3822) to differentiate between regular and skill mode when receiving tokens
- The Prompt casts `context.adapter` to `any` instead of `ConnectorClientBuilder` for browser compatibility; but does a property check to see if the adapter contains a …
=> Skills use correct ConnectorClient in OAuthPrompt, add ConnectorClientBuilder

libraries/adaptive-expressions/package.json, libraries/adaptive-expressions/src/commonRegex.ts, libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/tsconfig.json, libraries/botbuilder-ai/package.json, libraries/botbuilder/package.json
Fix CI and align versions of moment and moment-timezone
- Align moment and moment-timezone versions
- Change imports for moment, moment-timezone and LRUCache
- Added esModuleInterop flag to adaptive-expressions tsconfig.json
- Removed `"strict": false` from adaptive-expressions tsconfig.json
- Removed disabling of eslint rule in `expressionFunctions.ts`
Ran `lerna bootstrap` to test the ability to build adaptive-expressions without relying on hoisted dependencies.
=> Fix CI and align versions of moment and moment-timezone

libraries/botbuilder-dialogs-adaptive/src/adaptiveDialogComponentRegistration.ts, libraries/botbuilder-dialogs-adaptive/src/index.ts, libraries/botbuilder-dialogs-adaptive/src/luis/index.ts, libraries/botbuilder-dialogs-adaptive/src/luis/luisAdaptiveRecognizer.ts, libraries/botbuilder-dialogs-adaptive/src/recognizers/recognizer.ts
Fixes #1637
Added missing LuisAdaptiveRecognizer class
=> Added LuisAdaptiveRecognizer

libraries/botbuilder-core/tests/turnContext.test.js, libraries/botbuilder-dialogs/src/skillDialog.ts, libraries/botbuilder-dialogs/tests/skillDialog.test.js, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-schema/src/index.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/2139
- Add `StatusCodes.MULTIPLE_CHOICES = 300`
- Add protected method `SkillDialog.onValidateActivity()`
- `SkillDialog` now forwards all `ActivityTypes` to the Skill.
- Add new C# SkillDialog tests and refactor old tests
- Add missing test for TurnContext when deliveryMode === 'expectReplies'
- Fix error message in `BotFrameworkAdapter.createConnectorClientWithIdentity()`
- Add tests for `BotFrameworkAdapter.createConnectorClientWithIdentity()`
- Add test for `BotFrameworkAdapter.processActivity()` when deliveryMode === 'expectReplies', type is `Invoke` and reply activities have type `invokeResponse`
=> Update SkillDialog to handle all activity types (e.g. set DeliveryMode for Invokes)

libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/src/expressionType.ts, libraries/adaptive-expressions/tests/badExpression.test.js, libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #2165 
Fixes #2169
Add 7 timex builtin functions:
- isDefinite
- isTime
- isDuration
- isDate
- isTimeRange
- isDateRange
- isPresent
=> [PORT] [Expression] Add more timex builtin functions

libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts, libraries/botbuilder-core/src/botTelemetryClient.ts, libraries/botbuilder-core/tests/botTelemetryClient.test.js, libraries/botbuilder-dialogs-adaptive/src/skills/adaptiveSkillDialog.ts, libraries/botbuilder-dialogs-adaptive/tests/adaptiveSkillDialog.test.js, libraries/botbuilder-dialogs/src/componentDialog.ts, libraries/botbuilder-dialogs/src/dialogManager.ts, libraries/botbuilder-dialogs/src/waterfallDialog.ts, package.json, tools/util/updateDependenciesInPackageJsons.js
Fixes #2197
Fixes #2191
Fixes #2185
- Add Dialog / PageView telemetry #2145
- move botbuilder-lg and adaptive-expressions out of preview #2190
- Fixed issues with AdaptiveSkillDialog #2196
=> Cherry-pick #2145, #2190 and #2196 to master

libraries/botbuilder-dialogs-adaptive-tests/resources/InjectLGTests/inject.test.dialog, libraries/botbuilder-dialogs-adaptive-tests/resources/lg/inject.lg, libraries/botbuilder-dialogs-adaptive-tests/src/injectLG.test.ts, libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/injectionTest/common.lg, libraries/botbuilder-lg/tests/testData/examples/injectionTest/inject.lg
close: #2129 
In this PR, users can register namespace for a lg file. Also, they can register some templates as a expression functions, which can be applied easily in dialog. 
Here is an example to use these options,
> !# @registerNamespace = foo
> !# @registerAsFunctions = template1, template2
After registration,  in a dialog file, such usage `"property": "=foo.template1()"` is enabled, foo.template1() just behaves like a customized function.
The limitation is this kind of 'LG template function' can not read any scope from dialogStateManager, which is the same as prebuilt functions. 
For example, 
we have a memory in dialogStateManager:
`user.tasks: [ "car", "washing", "food", "laundry" ]`
if you to join the list of user.tasks, you have to define the LG file as 
```
> !# …
```
=> [Port]  [LG] Inject LG templates as a global expression function

libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/src/expressionType.ts, libraries/adaptive-expressions/tests/badExpression.test.js, libraries/adaptive-expressions/tests/expressionParser.test.js, libraries/adaptive-expressions/tsconfig.json
Fixes #2189
Refers to the first question in https://github.com/microsoft/botbuilder-dotnet/issues/3873
formatNumber(num1, num2), takes two arguments, the first one should be a numeric value, and the second one should be an integer. The returned value is a string
Examples
formatNumber(12.123, 2) =  "12.12"
formatNumber(20, 2) =  "20.00"
formatNumber(1.555, 2) = "1.56"
formatNumber(12.123, 4) = "12.1230"
Added formatEpoch and formatTicks. 
formatEpoch(1521118800) -> 2018-03-15T13:00:00.000Z
formatTicks(637243624200000000) -> 2020-05-06T11:47:00.000Z
Removed ticks functionality from formatDateTime.
=> Add formatNumber, parseEpoch and parseTicks.

libraries/adaptive-expressions/package.json, libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/tests/expressionParser.test.js, libraries/adaptive-expressions/tsconfig.json, libraries/botbuilder-dialogs-adaptive-tests/tsconfig.json, libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-adaptive/tsconfig.json, libraries/botbuilder-dialogs-declarative/tsconfig.json
Fixes #2207
- Updated packages to target ES6 (#2204)
- Switch adaptive-expressions to es6 (#2205)
=> Cherry-pick ES6 targeting and big-integer addition to master

libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts, libraries/botframework-streaming/src/utilities/index.ts
Fixes #2224
Per offline discussion, Chris M. asked that we do the PR against master
See https://github.com/microsoft/botbuilder-js/pull/2223 for PR against 4.9 counterpart
=> (AGAINST MASTER) Remove node exports from utilities

libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js
Fixes: https://github.com/microsoft/botbuilder-js/issues/2233
=> Do NOT call TeamsInfo.getMember for the bot

libraries/botbuilder/src/teamsActivityHandler.ts
Fixes #2222
The teams handler had a switch statement that was falling through.
=> Missing break/return statements.

libraries/botbuilder-ai/package.json, libraries/botbuilder-ai/src/luisSchema.d.ts
Fixes #2181
`moment` is imported but unused. Verified via search within `botbuilder-ai` package.
Remove `moment` from import statement and `package.json`
=> Remove moment from botbuilder-ai

libraries/botbuilder-core/tests/ActivityHandler.test.js, libraries/botbuilder-dialogs-adaptive/tests/beginSkill.test.js, libraries/botbuilder-dialogs/tests/skillDialog.test.js
Fixes #2231
Fixes #1227
SkillConversationIdFactory is now properly implemented in the SkillDialog and BeginSkill tests.
Adds ActivityHandler tests.
It's all tests.
=> Refactor tests for SkillDialog/BeginSkill scenarios, add ActivityHandler tests

libraries/botbuilder-lg/src/templateErrors.ts, libraries/botbuilder-lg/src/templatesParser.ts, libraries/botbuilder-lg/tests/lgDiagnostic.test.js, libraries/botbuilder-lg/tests/testData/exceptionExamples/ErrorTemplateName.lg
Original issue: https://github.com/microsoft/botbuilder-dotnet/issues/3942
close: #2258
The function name's format cannot cover all template name's formats. 
The valid format of template name is 
```
start with letter/number/_ and can only contains letter/number/./_
```
And the valid format of function name should meet
```
foreach(var part in expression.split('.')) 
{
// part should start with letter/_ and can only contains letter/number/_
}
```
So, in some cases, user use template evaluation in expression with the "gap" format would throw exception.
Here is the remedy that disables the name that begins with number in each part of the split result from dot(.).
Now, the valid format of template name should be :
```
foreach(var part in expression.split('.')) 
{
// part should start with …
```
=> [PORT]Make template name format consistent with function name format

libraries/adaptive-expressions/README.MD, libraries/adaptive-expressions/package.json, libraries/botbuilder-dialogs-adaptive/tests/LGGenerator.test.js, libraries/botbuilder-lg/README.MD, libraries/botbuilder-lg/package.json
We added `antlr4ts-cli` into dependency and would auto build g4 grammar when `build` and `test` script is executed. But `antlr4ts-cli` script depends on JAVA environment. the reference is here:
https://www.npmjs.com/package/antlr4ts-cli
So, remove the auto build of antlr, and instead, keep the antlr script, user can still run the script manually with local JAVA environment.
=> Remove antlr auto build with build/test script

libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts, libraries/botframework-streaming/src/utilities/index.ts
Fixes #2224 
loading bf-streaming in browser yields error:
`browserWebSocket.ts` imports `utilities`, which included `createNodeServer`
Removed reference to this node export in `utilities`
=> Remove node exports from utilities

libraries/browser-functional-tests/package.json
This fixes build [Run-JS-Functional-Tests-BrowserBot-yaml](https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=731&_a=summary) which has been failing.
=> Upgrade to Chrome ^83.0.0

libraries/botbuilder-dialogs/src/dialogContainer.ts, libraries/botbuilder-dialogs/tests/componentDialog.test.js
We added a new feature in 4.9 to automatically detect dialog changes. Some customers are complaining about the fallback logic we have to automatically throw an exception if the bot doesn't handle the new event we added.  We've decided to remove the fallback exception and make the feature entirely opt-in.
=> Removed fallback exception from version change logic.

libraries/botbuilder-dialogs/src/dialogContainer.ts, libraries/botbuilder-dialogs/tests/componentDialog.test.js
* Removed fallback exception from version change logic.
* Removed un-needed unit test
* Removed console log
Co-authored-by: Steven Gum <14935595+stevengum@users.noreply.github.com>
Fix #2295
=> Removed fallback exception from version change logic. (#2283)

libraries/adaptive-expressions/src/memory/simpleObjectMemory.ts, libraries/botbuilder-lg/src/customizedMemory.ts, libraries/botbuilder-lg/src/evaluationTarget.ts, libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/lgDiagnostic.test.js, libraries/botbuilder-lg/tests/testData/examples/RecursiveTemplate.lg, libraries/botbuilder-lg/tests/testData/exceptionExamples/LoopDetected.lg
Issue link: https://github.com/microsoft/botbuilder-dotnet/issues/4004
close: #2308
Modify the template loop detection to enable the recursive functions.
The loop exception will only be triggered if both the template name and the parameters are same.
=> [PORT]Refine template loop detection to enable recursive functions

libraries/botbuilder-lg/src/diagnostic.ts, libraries/botbuilder-lg/src/errorListener.ts, libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/src/templateErrors.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/src/templatesParser.ts, libraries/botbuilder-lg/tests/lgDiagnostic.test.js, libraries/botbuilder-lg/tests/testData/exceptionExamples/ErrorStructuredTemplate.lg, libraries/botbuilder-lg/tests/testData/exceptionExamples/ErrorTemplateName.lg
close: #2324
issue link: https://github.com/microsoft/botbuilder-dotnet/issues/3906
- Add more context info into some diagnostic errors.
- Add file path info into diagnostic errors.
|Item | Before | After|
|-- | -- | --|
|Invalid template name | Invalid template name. Template names can only contain letter... | Invalid template name: '{invalidName}'. Template names can only contain letter...|
|Invalid structure body | Invalid structure body. Body can include... | Invalid structure body: '{invalidBody}'. Body can include...|
|Syntax Error | Unexpected Content. Expecting a comment, template def... | {unexpectedContent}. Expecting a comment, template def...|
|Invalid Parameter | Invalid parameter name. Parameter names can ... | Invalid parameter name: '{invalidParameter}'. Parameter names …
=> [PORT]Enrich LG error message

.eslintignore, build/yaml/botbuilder-js-api-check.yaml, libraries/botbuilder-ai/etc/botbuilder-ai.api.md, libraries/botbuilder-applicationinsights/etc/botbuilder-applicationinsights.api.md, libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-dialogs/etc/botbuilder-dialogs.api.md, libraries/botbuilder/etc/botbuilder.api.md, libraries/botframework-config/etc/botframework-config.api.md, libraries/botframework-schema/etc/botframework-schema.api.md
Fixes #2320
- Create Azure DevOps .yaml pipeline for API check.
- Regenerates API documentation (`*.api.md`) in supported libraries
- Add generated adaptive-expressions code to .eslintignore
Latest run of pipeline for this branch: [link](https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=136792&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9)
=> [Engineering] Create .yaml pipeline for API check 

CODE_OF_CONDUCT.md, Contributing.md
Fixes #2351
- Adds contribution details aligned with https://github.com/microsoft/botframework-sdk/blob/master/Contributing.md
- Add code of conduct (linking to MS open source code of conduct)
=> Add community docs as per guidance

libraries/botframework-schema/src/teams/index.ts
Fixes #2381
- Add the **linkToMessage** property to the [MessageActionsPayload ](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-schema/src/teams/index.ts#L766)interface.
- Unit tests are not necessary for **MessageActionsPayload** properties since it is an interface.
In the image below we can see the [TeamsMessagingExtensionsAction](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/51.teams-messaging-extensions-action) sample displaying the new property's value in the action card.
=> Add linkToMessage to the MessageActionsPayload interface

libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/tests/badExpression.test.js, libraries/adaptive-expressions/tests/expressionParser.test.js
issue link: https://github.com/microsoft/botbuilder-dotnet/issues/4029
Fixes #2448
Originally, `getProperty` accepts two parameters, the first parameter is an instance, and the second parameter is the property name which user wants to access the value from. In this mode, the user can not access the top-level memory from dynamic/special string property.
After this change, `getProperty` accepts only one parameter, that presents the root property from the memory.
Example: 
Scope is :
```
{
"a:b": "value"
}
```
`getProperty('a:b')` would get string "value",
=> [PORT]Extend 'getProperty' builtin function to support accessing top memory

libraries/botbuilder-dialogs-adaptive-tests/resources/ActionTests/Action_RepeatDialogLoop.test.dialog, libraries/botbuilder-dialogs-adaptive-tests/src/action.test.ts, libraries/botbuilder-dialogs-adaptive/src/actions/repeatDialog.ts, libraries/botbuilder-dialogs-adaptive/src/adaptiveDialogComponentRegistration.ts
Fixes #2134 
add allowloop to repeat dialog and test
- botbuilder-js/libraries/botbuilder-dialogs-adaptive
- botbuilder-js/libraries/botbuilder-dialogs-adaptive-tests
=> Fix issue2134: add allowloop to repeat dialog and test

libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs/src/componentDialog.ts, libraries/botbuilder-dialogs/src/dialogContainer.ts
Fixes #2454 
Move TelemetryClient onto DialogContainer (implementation the same in AdaptiveDialog and ComponentDialog).
- Move TelemetryClient onto DialogContainer
- remove TelemetryClient from AdaptiveDialog and ComponentDialog
N/A
=> Move TelemetryClient property to DialogContainer

libraries/botframework-connector/src/auth/openIdMetadata.ts, libraries/botframework-connector/tests/openIdMetadata.test.js
=> Open id metadata cache refresh if key is missing

libraries/botframework-connector/src/auth/openIdMetadata.ts, libraries/botframework-connector/tests/openIdMetadata.test.js
* openIdMetadata cache updates and tests
* revert whitespace change
* copyright header for openIdMetadata.test.js
=> cherry-pick to 4.9: Open id metadata cache refresh if key is missing (#2466)

libraries/botframework-connector/src/connectorApi/models/index.ts
=> Make ConnectorClientOptions.baseUri optional

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts
=> Unionize TaskModuleResponse.task type definition

libraries/botbuilder/tests/teamsActivityHandler.test.js
Fixes #1393
This PR adds catching errors to the [TeamsActivityHandler tests](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/tests/teamsActivityHandler.test.js), so they can fail properly when an error occurs.
- Adds missing catching errors for every test in the [teamsActivityHandler.test.js](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/tests/teamsActivityHandler.test.js) file.
- Repaced the `async` keyword with a `done` callback for each `it` function test.
In the image below shows the test list that were passing before and after this changes.
=> [Teams] Fix broken TeamsActivityHandler tests

libraries/botbuilder/tests/statusCodeError.test.js
Addresses #2432
This PR adds unit tests for the [StatusCodeError](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/statusCodeError.ts) class increasing the code [coverage](https://coveralls.io/builds/31822744/source?filename=libraries/botbuilder/src/statusCodeError.ts) from **33%** to **100%**.
- Added **statusCodeError.test.js** file with unit tests for the constructor.
The following images show the new tests passing.
=> Increase code coverage in botbuilder library - StatusCodeError class

libraries/botbuilder/tests/botFrameworkHttpClient.test.js
Addresses #2432
This PR adds unit tests for the [BotFrameworkHttpClient](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkHttpClient.ts) class.
- Updated [botFrameworkHttpClient.test.js](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/tests/botFrameworkHttpClient.test.js) with unit tests to cover the following methods:
- PostActivity
-  buildCredentials
The following image shows the new tests passing:
=> Increase code coverage in botbuilder library - BotFrameworkHttpClient class

libraries/botframework-streaming/src/interfaces/INodeSocket.ts
All JS builds are breaking I believe due to a linting or pipeline update(?); I didn't really see any other relevant recent commits. INodeSocket needs to implement `readableFlowing` so I added it as a property that does nothing. It can't be optional or the build will still break. It uses the same typing and scope as `Socket` defined in Node globals:
[Here's the failure](https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=145306&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=df8dc50d-985d-501e-ee67-7f805e7e444c&l=49):
```cmd
src/webSocket/nodeWebSocket.ts(39,69): error TS2345: Argument of type 'INodeSocket' is not assignable to parameter of type 'Socket'.
> botframework-config@4.4.0-preview.145306 build /Users/runner/work/1/s/libraries/botframework-config
Property …
```
=> add readableFlowing property to INodeSocket

libraries/teams-scenarios/searchBasedMessagingExtension/src/index.ts, libraries/teams-scenarios/searchBasedMessagingExtension/src/teamsSearchExtensionBot.ts
Addresses #1314
This PR fixes how the [teamsSearchExtensionBot](https://github.com/microsoft/botbuilder-js/blob/master/libraries/teams-scenarios/searchBasedMessagingExtension/src/teamsSearchExtensionBot.ts) handles the _onSelectedItem_ event so it returns a hero card for every result selected by the user.
- Updated [teamsSearchExtensionBot.ts](https://github.com/microsoft/botbuilder-js/blob/master/libraries/teams-scenarios/searchBasedMessagingExtension/src/teamsSearchExtensionBot.ts) file adding a tap event to all the result card' previews.
The images below show the bot running on Teams.
=> [Teams] Fix onSelectedItem in Teams Search Extension Bot

libraries/botframework-connector/tests/openIdMetadata.test.js
Related to: https://github.com/microsoft/botbuilder-js/issues/2563
Core issue is that the `-connector` metadata tests break after running `npm run test` multiple times. This is band-aid fix that addresses the symptom but not the real problem, which I believe is nock cross-pollution between tests. Tracking that in the issue above to fix tomorrow.
=> Restore and activate nock

libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-core/src/activityHandler.ts, libraries/botbuilder-core/src/activityHandlerBase.ts, libraries/botbuilder-core/tests/ActivityHandler.test.js, libraries/botbuilder-core/tests/activityHandlerBase.test.js
Fixes https://github.com/microsoft/botbuilder-js/issues/2546
=> Add installation update to activity handler

libraries/botbuilder-dialogs-declarative/README.md
Indicate on README for `botbuilder-dialogs-declarative` that it is a preview library and only works for Node.js v10, v12.
The following line  is derived from the description of [Microsoft.Bot.Builder.Dialogs.Declarative](https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs.Declarative/):
> "This **preview** library implements Node.js support Declarative definition of dialogs assets."
@JonathanFingold, @Kaiqb FYI
=> Update botbuilder-dialogs-declarative README

libraries/adaptive-expressions/tests/expressionParser.test.js
Occasionally, one of the `adaptive-expressions` tests would fail with something like:
```cmd
AssertionError [ERR_ASSERTION]: actual is: 07-27-20 17, expected is 07-27-20 16
+ expected - actual
-07-27-20 17
+07-27-20 16
```
I believe this is because:
* Test loads at say, 9:58am which [would give expected data of `07-27-20 09'](https://github.com/microsoft/botbuilder-js/blob/master/libraries/adaptive-expressions/tests/expressionParser.test.js#L467)
* Test actually runs two minutes later at 10:00, so the actual data would be `07-27-20 10'. 
Have the test refresh the expected time based off of the current time.
=> Fix intermittent expressions test error due to hour change

libraries/botbuilder/tests/inspectionMiddleware.test.js, libraries/botbuilder/tests/skills/skillHandler.test.js
Address #2338
Removed duplicated tests for missing `conversationIdFactory` in `skillHandler` tests and moved variables to be reused in `skillHandler` and `inspectionMiddleware` tests.
Changes in `skillHandler.tests.js`
- Removed validation for error when creating a `SkillHandler` without a `conversationIdFactory` because that's already tested in another it.
- Moved the variables `adapter`, `bot`, `factory`, `creds` and `authConfig` to the top of the describe to be reused by all the tests instead of creating new ones without modification for each one.
Changes in `inspectionMiddleware.tests.js`
- Moved variables `storage`, `inspectionState`, `userState` and `conversationState` to the top of the describe to be reused in all the tests instead of creating new ones without modification for each …
=> [Engineering] Lower time for botbuilder tests

libraries/botframework-config/tests/connect.test.js, libraries/botframework-config/tests/encryption.test.js
Addresses #2338
This PR optimizes the time for the [botframework-config](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-config) tests having no impact in the code coverage and reducing the execution time approximately from **184ms** to **135ms**.
`connect.test.js`
- Moved multiple `BotConfiguration` instances to a single one at the top of the file to be reused.
- Created the _mapServices_ function to reduce duplicated code in the tests.
- Fixed eslint warnings.
`encryption.test.js`
- Moved  `secret` and `value` variables as constants outside the tests to be reused.
- Created the _encriptDecriptString_ function to reduce duplicated code.
Total coverage has not been affected.
The execution time was reduced.
=> [Engineering] Lower time for botframework-config tests

libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts, libraries/adaptive-expressions/src/expressionProperties/valueExpression.ts, libraries/adaptive-expressions/tests/expressionProperty.test.ts
Fixes #2443 
When encoding a string as an expression we need to properly handle slash.
* AdaptiveExpressions
* AdaptiveExpressions.Tests
tests updated to validate round-trip slashes
=> [Port] properly escape slashes in constant strings with StringExpression/ValueExpression

libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
Fixes #2672 
* Added code to BeginSkill.BeginDialog() that stores DialogOptions in state.
* Added overrides for ContinueDialogAsync, RepromptDialogAsync, ResumeDialogAsync and EndDialogAsync that pull the stored DialogOptions from the dialog state and regenerate the property .
Unit tests will be added after they're added in Dotnet as part of [#3879](https://github.com/microsoft/botbuilder-dotnet/issues/3879), I am just trying to fix the P0 issue for R10 right now.
=> BeginSkillDialog: store DialogOptions in state and regen for methods

libraries/botbuilder-dialogs-adaptive-testing/tests/crossTrainedRecognizerSet.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/CrossTrainedRecognizerSetTests/CrossTrainedRecognizerSetTests_Empty.test.dialog, libraries/botbuilder-dialogs-adaptive/src/recognizers/crossTrainedRecognizerSet.ts
Fixes #2438 
Added empty recognizer support in crosstrained recognizer set.
- If recognizers are empty, return none intent in cross trained recognizer set.
-
-
Added corresponding test.
=> Empty recognizer support in crosstrained recognizer set

libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts
Fixes #2307 
Calling an event driven dialog did not work because passed in options would override the initial setup of dialog memory.
- Adjusted beginDialog() in AdaptiveDialog
-
-
=> Allow calling an event driven dialog

libraries/adaptive-expressions/src/builtinFunctions/index.ts, libraries/adaptive-expressions/src/builtinFunctions/jsonStringify.ts, libraries/adaptive-expressions/src/constant.ts, libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/src/expressionType.ts, libraries/adaptive-expressions/src/parser/expressionParser.ts, libraries/adaptive-expressions/tests/badExpression.test.js, libraries/adaptive-expressions/tests/expressionParser.test.js
issue ref: https://github.com/microsoft/botbuilder-dotnet/issues/4528
Add function `jsonStringify` to convert objects into json string.
Cases:
jsonStringify({a:'b'}) =>  '{"a":"b"}'
jsonStringify('a') => '"a"'
jsonStringify(null) => 'null'
jsonStringify(undefined) => undefined
=> Add "jsonStringify" builtin function

libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_SendActivity.test.dialog, libraries/botbuilder-dialogs-adaptive/src/actions/sendActivity.ts, libraries/botbuilder-dialogs-adaptive/src/converters/activityTemplateConverter.ts
Fixes #2346
```
{
"$kind": "Microsoft.SendActivity",
"activity": {
"$kind": "Microsoft.StaticActivityTemplate",
"activity": {
"type": "message",
// only channel data property, no text and speak.
// This one should be valid and be sent to the channel.
"channelData": {xxxx}
}
}
}
```
=> [PORT] Allow the activity only with channelData property in sendActivity action

libraries/botbuilder-core/src/showTypingMiddleware.ts, libraries/botbuilder-core/tests/showTypingMiddleware.test.js
Fixes #2527
This fixes the bug described in the linked issue. In particular, errors are now caught and passed to the error handler registered on the adapter, if it exists.
* Small refactoring to leverage more idiomatic Typescript and Javascript (inline class constructor params, leverage inferred types, use proper `setTimeout` type, arrow functions for `this` propagation, etc)
* Catch errors in ShowTypingMiddleware `setTimeout` function
* Add a test to verify this behavior
* Added a test to verify behavior.
=> Catch errors in ShowTypingMiddleware

libraries/botbuilder/src/teamsActivityHelpers.ts, libraries/botbuilder/tests/teamsHelpers.test.js, libraries/botframework-connector/src/teams/models/mappers.ts, libraries/botframework-schema/src/teams/index.ts
Fixes #2836
- Adds alertInMeeting and externalResourceUrl fields to teams notifications
- Slightly cleans up validation logic and makes use of type guards for type inference
- Removes unused code from related test
Unit testing to validate side effect of notify helper.
=> Add fields to teams notifications

libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/injectionTest/injectWithoutNamespace.lg
Issue: https://github.com/microsoft/BotFramework-Composer/issues/3982
C# pr: https://github.com/microsoft/botbuilder-dotnet/pull/4724
Originally, the injection of LG function into Expression require a namespace option. If there is no namespace option, a absolute path is require. It is too strict.
Loose the namespace fallback policy. The priority order is:
1. If there is a namespace option, use it
2. If there is an un-empty id, parse the file name from the id, and get the namespace
3. If the Id is empty, just drop the namespace and use the template name as the expression name directly.
For example:
If there is an option in LG file, like:
```
> !# @Namespace = general
```
`general` is the namespace, the export function could be presented as `general.xxx`
If there does not exist a namespace …
=> [PORT][LG] Redo the default fallback of namespace

libraries/botbuilder-ai/package.json, libraries/botbuilder/package.json, libraries/botframework-connector/package.json, package.json
Supports the following adapter configuration:
```typescript
const httpAgent = new Agent({ maxSockets: 10 });
const httpsAgent = new HttpsAgent({ maxSockets: 10 });
const adapter = new BotFrameworkAdapter({
appId: process.env.MicrosoftAppId,
appPassword: process.env.MicrosoftAppPassword,
clientOptions: {
agentSettings: {
http: httpAgent,
https: httpsAgent,
},
},
});
```
Fixes #183
=> Bump @azure/ms-rest-js to 1.9.0

libraries/botbuilder/src/teamsActivityHandler.ts
Fixes #2897 (except for docs)
Per discussion w/ @stevengum, there's two different ways that developers can handle Teams Activities:
1. Use the older callback chaining by passing in callbacks, or
2. Use inheritance and override the methods in `TeamsActivityHandler`
The methods in [`TeamsActivityHandler`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts) are *supposed* to fit the following scheme:
* Methods **starting with `handle`** (e.g. `handleTeamsTaskModuleFetch()`) must be overridden by the developer, if the developer wants the bot to handle Invoke activities, and
* Methods **ending with `Event`** (e.g. `onTeamsMembersAddedEvent()`) can be used by passing in callbacks, however
* Methods **starting with `on` and *not* ending in …
=> adjusted override/callback docstrings

libraries/botbuilder-dialogs/package.json, libraries/botbuilder-dialogs/src/i18n.ts, libraries/botbuilder-dialogs/src/prompts/numberPrompt.ts, libraries/botbuilder-dialogs/tests/numberPrompt.test.js
This fixes a case where looking up a locale not registered in Globalize
throws a module not found exception.
Also refactors the test slightly, installs and uses @types/globalize,
and fixes locale registration.
Fixes #2911
=> dialogs: fall back to defaultLocale Globalize parser if locale is not found

libraries/botbuilder-dialogs/src/dialogHelper.ts, libraries/botbuilder-dialogs/src/dialogManager.ts, libraries/botbuilder-dialogs/src/skillDialog.ts, libraries/botbuilder-dialogs/tests/dialogManager.test.js
=> port: remove unnecessary verbose trace logging

libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botbuilder/tests/skills/skillHandler.test.js, libraries/botbuilder/tests/teamsInfo.test.js, libraries/botframework-connector/src/auth/appCredentials.ts, libraries/botframework-connector/tests/auth.test.js
Ports changes from https://github.com/microsoft/botbuilder-dotnet/pull/4827
=> port: remove trusted URL logic

build/yaml/botbuilder-js-api-check.yaml, build/yaml/botbuilder-js-ci-node12.yml, build/yaml/botbuilder-js-ci.yml, build/yaml/botbuilder-js-daily.yml, build/yaml/js-build-steps.yml
Reverting to vmImage macOS-10.15.
OrchestratorAdaptiveRecognizer tests were failing when running in ubuntu-18.04 and in ubuntu-20.04.
This reverts commit ac08692132e0cf3ce21661f5626591b3af312c4f.
=> Revert "Change vmImage to ubuntu for all JS pipelines (#2931)"

libraries/botbuilder-ai/tests/luisRecognizer.test.js
There were a few issues with this test -
1. Throttle code sprinkled unnecessarily throughout
2. Inconsistent promise rejection/async/done handling
3. Code style issues
This commit cleans up all these issues and ensures that TestJson
failures are properly logged as test failures rather than unhandled
promise rejections.
```
(node:2921) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: 
Returned JSON
/Users/runner/work/1/s/libraries/botbuilder-ai/tests/TestData/LuisRecognizer/SingleIntent_SimplyEntityTelemetry.json.new
!= expected JSON
/Users/runner/work/1/s/libraries/botbuilder-ai/tests/TestData/LuisRecognizer/SingleIntent_SimplyEntityTelemetry.json
at TestJson.recognizer.recognize.then.res (/Users/runner/work/1/s/libraries/botbuilder-ai/tests/luisRecognizer.test.js:179:13) …
```
=> fix: luis recognizer tests

libraries/adaptive-expressions/src/expressionProperties/arrayExpression.ts, libraries/adaptive-expressions/src/expressionProperties/boolExpression.ts, libraries/adaptive-expressions/src/expressionProperties/intExpression.ts, libraries/adaptive-expressions/src/expressionProperties/numberExpression.ts, libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts, libraries/adaptive-expressions/tests/ExpressionPropertyType.test.js
Fixes #2568
Add type checking for the implements of ExpressionProperty. Including `NumberExpression`, `IntExpression`, `BoolExpression`, `ArrayExpression`, `StringExpression`
=> Add type check for ExpressionProperty

libraries/botbuilder-core/src/skills/botFrameworkClient.ts, libraries/botbuilder-core/src/turnContext.ts, libraries/botbuilder-dialogs/src/skillDialog.ts, libraries/botframework-schema/src/index.ts
Also includes some small cleanup/formatting changes.
Fixes #2962
=> port: fix issues w/ ExpectReplies, invoke in SkillDialog

libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts, libraries/adaptive-expressions/src/expressionProperties/valueExpression.ts, libraries/adaptive-expressions/tests/expressionProperty.test.ts
Fixes #2982 in `4.11`
Feature parity with .NET PR: https://github.com/microsoft/botbuilder-dotnet/pull/4847
=> port: fix error caused by backtick in stringExpression and valueExpression

libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts, libraries/adaptive-expressions/src/expressionProperties/valueExpression.ts, libraries/adaptive-expressions/tests/expressionProperty.test.ts
Cherry-pick of #2983
Fixes #2982
=> fix: error caused by backtick in stringExpression and valueExpression

libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts
Fixes #2988 
Cached instances of `LanguageGeneratorManager` in `LanguageGeneratorExtensions` to avoid registering duplicated callbacks in resource explorer.
- Cached lgm instance in LanguageGeneratorExtensions.useLanguageGenerator().
-
-
=> Cached lgm initialization in lg extension

libraries/botbuilder-repo-utils/package.json, libraries/botbuilder-repo-utils/src/file.ts
It looks like this was added in Node 14.x unfortunately.
=> fix: fs/promises not available in node 12.x

libraries/botbuilder-repo-utils/src/execCmd.ts, libraries/botbuilder-repo-utils/src/workspace.ts
- Propagate flags to underlying command (i.e. `yarn execute lint -- --quiet`)
- Clean up error handling/logging and make `--continue` work
- Add `--stream` support
=> fix: small execute script tweaks

libraries/botbuilder-repo-utils/src/workspace.ts
This should make Windows builds work again.
=> fix: use path.posix.join for globs

.github/workflows/run-test-repoutils.yml, libraries/botbuilder-repo-utils/package.json, libraries/botbuilder-repo-utils/src/execCmd.ts, libraries/botbuilder-repo-utils/src/package.ts, libraries/botbuilder-repo-utils/src/process.ts, libraries/botbuilder-repo-utils/src/updateVersions.ts, libraries/botbuilder-repo-utils/src/workspace.ts, libraries/botbuilder-repo-utils/tests/execCmd.test.ts, libraries/botbuilder-repo-utils/tests/updateVersions.test.ts, package.json, yarn.lock
=> fix: add tests for repo utils

.github/workflows/run-test-repoutils.yml
Missed this in https://github.com/microsoft/botbuilder-js/pull/3056
=> fix: add repoutils workflow script to glob pattern

libraries/adaptive-expressions/src/builtinFunctions/dateReadBack.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
Function `dateReadBack` is broken. This PR fixes this issue.
=> Fix function dateReadBack bug

libraries/botbuilder-ai-orchestrator/package.json, libraries/botbuilder-ai-orchestrator/src/orchestratorAdaptiveRecognizer.ts, libraries/botbuilder-ai-orchestrator/tests/orchestratorAdaptiveRecognizer.test.js
Closes #3073 
Fix the Orchestrator null check on Initialize() to be consistent at lines 156 and 299
- Change null check at line 299 to match line 156
Unit tests added to catch cases where either the `orchestrator` or `labelResolver` objects are not initialized before `score` is called (would have failed this test before).
=> bug: Fix OrchestratorRecognizer null checks 

libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tests/lg.test.js
Fixes #3076
Previously, the sourceRange(start and end line position) of a LG template is calculated based on the parsed token. But in certain scenarios that, when there are extra empty character (line breaks) at the end of a template, will cause this calculation not correct, and thus causing the further update on this lg file misplaced in the wrong position, causing potential data loss. 
Use the real content received to calculate start\end line.  Content is the golden truth, more trustworthy than parsed tokens. 
Composer
=> Compute LG SourceRange based on content instead of parsed token

libraries/adaptive-expressions-ie11/package.json, libraries/adaptive-expressions-ie11/tsconfig.json, libraries/adaptive-expressions-ie11/webpack.config.js, yarn.lock
Part 1 of #3053
- add terser-webpack-plugin@^4.2.3 to adaptive-expressions-ie11 (https://github.com/microsoft/botbuilder-js/commit/395b86427c287cc55b5d14ef0051ad81775121f4)
- new `dist/` footprint: 
https://bundlephobia.com/result?p=adaptive-expressions@4.11.0
https://bundlephobia.com/result?p=adaptive-expressions-ie11@4.11.0
=> feat: minify adaptive-expressions-ie11 

libraries/adaptive-expressions-ie11/package.json, libraries/adaptive-expressions-ie11/webpack.config.js, yarn.lock
- Use `require.resolve` for proper package resolution algorithm, do not
hardcode paths to packages
- Use `CleanWebpackPlugin`
- Use `CopyWebpackPlugin` instead of `copyfiles` for proper package
resolution algorithm
Replaces #3087
=> fix: adaptive-expressions-ie11 webpack config

libraries/botbuilder/src/botFrameworkAdapter.ts
Reverts microsoft/botbuilder-js#2950
=> Revert "feat: immediate accept"

libraries/botframework-connector/README.md
Noticed a spelling mistake in the README of the `botframework-connector`.
- Updates variable `acivityResponse` to `activityResponse` in the example code.
=> Fix typo in botframework-connector README

libraries/botbuilder-ai-orchestrator/package.json, libraries/botbuilder-ai/package.json, libraries/botbuilder-applicationinsights/package.json, libraries/botbuilder-azure-blobs/package.json, libraries/botbuilder-azure/package.json, libraries/botbuilder-core/package.json, libraries/botbuilder-dialogs-adaptive-testing/package.json, libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-declarative/package.json, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-repo-utils/package.json, libraries/botbuilder-testing/package.json, libraries/botbuilder/package.json, libraries/botframework-config/package.json, libraries/botframework-connector/package.json, libraries/botframework-schema/package.json, libraries/botframework-streaming/package.json, package.json, yarn.lock
I have submitted a PR to upstream a bugfix to downlevel-dts with no
response yet. I also added a feature that computes checksums that can be
used to skip superfluous processing, drastically reducing subsequent
`yarn build` times (~50%).
PR: https://github.com/sandersn/downlevel-dts/pull/48
=> feat: use fork of downlevel-dts

libraries/adaptive-expressions/package.json, libraries/botbuilder/package.json, tools/package.json, yarn.lock
- bump `moment` and `moment-timezone` dependencies to latest.
- remove unnecessary `@types/moment-timezone`. (See https://www.npmjs.com/package/@types/moment-timezone)
=> feat: bump moment-related dependencies

libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
Fixes #3023 
Fixed timeout logic in `OAuthInput`
- 
-
-
=> Fixed timeout in OAuthInput

.github/workflows/tests.yml
I didn't know this was supported!
=> fix: use matrix for operating system

libraries/browser-functional-tests/browser-tests-build-ci.yml
Adds tags to the provisioned Azure Resource Group for automated management of RGs.
These tags indicate when and why the Resource Group was created. They also provide pointers to the repository, the source branch and name of the pipeline that was run to better assist other team members with figuring out who to contact.
- Add tags to `az group create` step
- Create `$DateTimeTag` runtime variable in Azure DevOps
- A REST call is required to get the actual pipeline queue time, which didn't seem necessary for the goals of this PR.
=> fix: add tags to browser CI resource groups

libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts, libraries/botbuilder-dialogs-declarative/tests/resourceExplorer.test.js, libraries/botbuilder-dialogs-declarative/tests/resources/CycleDetection/child.dialog, libraries/botbuilder-dialogs-declarative/tests/resources/CycleDetection/root.dialog, libraries/botbuilder-dialogs/src/dialogContainer.ts, libraries/botbuilder-dialogs/src/dialogManager.ts, libraries/botbuilder-dialogs/src/dialogSet.ts
Fixes #2640 
Allow `ResourceExplorer` to preload types into cache to support cycle references between dialog files.
- allow `ResourceExplorer` to preload types
- updated container registration in `DialogManager` to avoid infinite loops
- updated telemetry client configuration in `DialogContainer` to avoid infinite loops
Added tests to cover cycle references.
=> feat: cycle references support

libraries/botbuilder-azure/src/cosmosDbStorage.ts
This is definitely the sketchiest implementation, though I've verified it with the locally installed dependencies. It's also very defensive and purely opt-in.
=> fix: plumb http agent into documentdb client

libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
=> fix: port throw meaningful exception

libraries/adaptive-expressions/package.json, libraries/adaptive-expressions/src/builtinFunctions/newGuid.ts, libraries/botbuilder-ai-orchestrator/package.json, libraries/botbuilder-ai-orchestrator/src/orchestratorAdaptiveRecognizer.ts, libraries/botbuilder-core/package.json, libraries/botbuilder-core/src/testAdapter.ts, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-dialogs/src/waterfallDialog.ts, libraries/botbuilder-lg/package.json, libraries/botbuilder-lg/src/templateExtensions.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder/package.json, libraries/botbuilder/src/eventFactory.ts, libraries/botbuilder/src/inspectionMiddleware.ts, libraries/botbuilder/src/skills/skillHandler.ts, libraries/botbuilder/src/streaming/tokenResolver.ts, libraries/botbuilder/tests/fileTranscriptStore.test.js, libraries/botframework-config/package.json, libraries/botframework-config/src/botConfiguration.ts, libraries/botframework-streaming/package.json, libraries/botframework-streaming/src/utilities/protocol-base.ts, yarn.lock
Fixes #3160 
Using package [uuid](https://github.com/uuidjs/uuid) to generate RFC-compliant UUIDs
- Added `uuid` package to `adaptive-expressions`
- Added `uuid` package to `botbuilder-ai-orchestrator`
- Added `uuid` package to `botbuilder-core`
- Added `uuid` package to `botbuilder`
- Added `uuid` package to `botbuilder-lg`
- Added `uuid` package to `botbuilder-dialogs`
- Updated `uuid` package to 8.x in `botframework-config`
- Updated `uuid` package to 8.x in `botframework-streaming`
Fixed tests.
=> fix: use package 'uuid' to generate RFC-compliant UUIDs

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_BeginSkill.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_BeginSkillEndDialog.test.dialog, libraries/botbuilder-dialogs-adaptive/src/adaptiveComponentRegistration.ts, libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts, libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts, libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts, libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts
Fixes #3037 
Fixes #3042 
adds two BeginSkill action tests using .dialog files and required middleware
- Registered `Microsoft.StaticActivityTemplate`
- Registered `Microsoft.ActivityTemplate`
- Registered `Microsoft.TextTemplate`
- Added tests for BeginSkill with middlewares
Added tests.
=> fix: tests for BeginSkill with middlewares

libraries/botbuilder-dialogs-adaptive-testing/src/adaptiveTestComponentRegistration.ts, libraries/botbuilder-dialogs-adaptive-testing/src/dialogInspector.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testAction.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/assertNoActivity.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/assertReplyActivity.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/customEvent.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/index.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/memoryAssertions.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/setProperties.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/userActivity.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/userConversationUpdate.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/userDelay.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/userSays.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testActions/userTyping.ts, libraries/botbuilder-dialogs-adaptive-testing/src/testScript.ts, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_OAuthInputRetries_WithNullMessageText.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_PropertyMock.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/testScript.test.js, libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs-adaptive/src/entityAssignment.ts
Fixes #3113 
Fixes #3035 
Fixes #2474 
Implemented `DialogInspector` with some new test actions.
- Implemented `DialogInspector`
- Added `AssertNoReply`
- Added `MemoryAssertions`
- Added `SetProperties` (Microsoft.Test.SetProperties)
- Centralized resetting retries
Added test `PropertyMock`.
=> feat: DialogInspector and new test actions

libraries/botbuilder/package.json, yarn.lock
Note: it doesn't appear that we support proxy functionality within `botbuilder`, so I don't think this is a high priority issue deserving patch releases.
=> fix: axios dependeabot alert

.eslintrc.json, libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts
Add `no-var` eslint rule, fix `var` usage (and prettier formatting).
=> fix: remove var, add lint rule

libraries/botbuilder-dialogs-adaptive-testing/src/testActions/memoryAssertions.ts, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_PropertyMock.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/testScript.test.js
Related: https://github.com/microsoft/botbuilder-dotnet/pull/5084
The MemoryAssertions tests were silently failing. They'll now pass and also elicit errors if they fail. In the Node version, it also was passing the assertions when it shouldn't, due to [this](https://github.com/microsoft/botbuilder-js/compare/main...mdrichardson:main?expand=1#diff-934af35e8c122351d11ac7a4f294230a5fa2a3bf641d17c5d408af46061e48cfL50), which was correct in Dotnet, which [correctly uses `||`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/MemoryAssertions.cs#L62). You can see the issues in the original code if you throw a breakpoint [here](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-dialogs-adaptive-test …
=> Fix MemoryAssertions and test

libraries/botbuilder-ai/package.json, libraries/botbuilder/package.json, libraries/botframework-connector/package.json, yarn.lock
=> fix: bump ms-rest-js for axios version bump

libraries/botbuilder-dialogs-adaptive-testing/src/testActions/userActivity.ts, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_UserActivity.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/testScript.test.js
`userActivity` in the Node SDK didn't match the one in the .NET SDK, with respect to using `activity.from` in the `activity` property supplied in `test.dialog` files.
- Added an `else if` condition to match [.NET SDK](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs#L72), that sets `activity.from` to match the `activity.from` if passed in from the `test.dialog` file.
Added a test for `UserActivity` that would catch this as well as other things, since the test didn't exist.
The first `Microsoft.Test.UserActivity` is to check that it sets the adapter defaults. The next activity is to check that from gets set by the `activity.from` property. The next is to make sure it gets set by the `user` property
=> Ensure UserActivity activities inherit from set activity

libraries/botbuilder-stdlib/src/types.ts
Small issue with `typeof null === 'object'` is true.
=> fix: null/undefined is not an object

libraries/adaptive-expressions/src/builtinFunctions/dateTimeDiff.ts, libraries/adaptive-expressions/src/builtinFunctions/int.ts, libraries/adaptive-expressions/src/functionUtils.internal.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #2211
Currently, JS sdk uses Number to handler all number input, and with BigInt to handler ticks().
Here SDK provides such a solution to reduce the gap between these two languages:
- Keep the range gap of the normal number.**-2^63 ~ 2^63 -1** for C# and **-2^53+1 ~ 2^53** for JS. (JS would provide inaccurate calculation of numbers beyond this range)
- Provide a solution to convert bigint object into a normal number in js. `int()` function can accept a bigint input, and output a fuzzy number output.
For example: `int(ticks(utcNow())) - 1` would be valid and the output would be a `number`. But the accuracy of the output is not guaranteed
=> make bigInt more applicability in adaptive-expressions

libraries/botbuilder-dialogs-adaptive-testing/package.json, libraries/botbuilder-dialogs-adaptive-testing/src/policies/actionPolicy.ts, libraries/botbuilder-dialogs-adaptive-testing/src/policies/actionPolicyException.ts, libraries/botbuilder-dialogs-adaptive-testing/src/policies/actionPolicyValidator.ts, libraries/botbuilder-dialogs-adaptive-testing/tests/actionPolicy.test.js, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-dialogs/src/dialogSet.ts
Introduces a few small tweaks:
- Use type assertions for better runtime safety and compiler hinting
- Simplify classes a bit (remove unnecessary setters/getters)
- Use assert.throws in tests for clarity
- Prettier code formatting
=> ActionPolicy clean up

.eslintrc.json, libraries/botbuilder-azure-queues/tests/azureQueueStorage.test.js, libraries/botbuilder-repo-utils/src/file.ts, libraries/botbuilder-repo-utils/src/run.ts, libraries/botbuilder-stdlib/src/types.ts
Tune unused eslint rule to support prefixing things with `_` to disable unused error
=> fix: tune unused eslint rule

libraries/botbuilder-dialogs/src/dialogSet.ts, libraries/botbuilder-dialogs/tests/dialogManager.test.js, libraries/botbuilder-dialogs/tests/dialogSet.test.js
Ports relevant tests related to #3229 to ensure that cyclical components don't trigger stack overflows in a few specific scenarios.
Note: there is a single commit related to code formatting, I would suggest reviewing the first and third commits directly.
Fixes #3229
=> feat: cyclical dialog tests

libraries/adaptive-expressions/src/builtinFunctions/abs.ts, libraries/adaptive-expressions/src/builtinFunctions/index.ts, libraries/adaptive-expressions/src/builtinFunctions/sqrt.ts, libraries/adaptive-expressions/src/expressionFunctions.ts, libraries/adaptive-expressions/src/expressionType.ts, libraries/adaptive-expressions/tests/badExpression.test.js, libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #3240
Add `abs` and `sqrt` prebuilt function.
Example:
```
abs(3.12134)  -> 3.12134
abs(-3.12134) -> 3.12134
abs(0) -> 0
sqrt(9) -> 3
sqrt(-1)  -> throw error
sqrt(0) ->  0
```
=> [PORT]Add abs and sqrt built-in function

libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.BeginDialog.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.BeginSkill.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.CancelAllDialogs.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.DeleteProperties.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.DeleteProperty.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.EditActions.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.EditArray.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.EmitEvent.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.Foreach.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.ForeachPage.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.GetActivityMembers.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.GetConversationMembers.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.HttpRequest.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.IfCondition.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.ReplaceDialog.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.SendActivity.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.SetProperties.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.SetProperty.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.SwitchCondition.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.ThrowException.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.UpdateActivity.schema, libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.UpdateActivity.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.Ask.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.AttachmentInput.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.ChoiceInput.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.ConfirmInput.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.DateTimeInput.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.NumberInput.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.OAuthInput.uischema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.TextInput.uischema
(Copied from C#. Refs https://github.com/microsoft/botbuilder-dotnet/pull/5099)
follows #2986 
In #2986, we port the ui schema `form` part to runtime in order to support the customization of Composer Form Editor;
in this PR, the `flow` part is added to runtime as well to support the customization of Composer Flow Editor.
Refs ui.schema definition change in SDK repo: https://github.com/microsoft/botframework-sdk/pull/6163
- QnAMakerDialog
- BeginDialog
- BeginSkill
- CancelAllDialog
- DeleteProperty, DeleteProperties
- EditActions
- EditArray
- EmitEvent
- Foreach, ForeachPage
- GetActivityMembers, GetConversationMembers
- HttpRequest
- IfCondition
- ReplaceDialog
- SendActivity
- SetProperties, SetProperty
- SwitchCondition
- ThrowException
- UpdateActivity
- Ask
- AttachmentInput, …
=> Append Composer ui schema 'flow' part to component schema files

libraries/botbuilder-ai/src/luisAdaptiveRecognizer.ts, libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/src/luisTelemetryConstants.ts, libraries/botbuilder-ai/tests/luisRecognizer.test.js
=> fix: port Luis intent2 properties from dotnet

libraries/botbuilder/src/eventFactory.ts, libraries/botbuilder/tests/eventFactoryTests.test.js
Fixes #3242
Sets the `type` on the returned Activity to `ActivityTypes.Event` in EventFactory.createHandoffEvent()
- Set returned `Activity.type` to `ActivityTypes.Event`
- Cleanup imports, remove unnecessary cast
- Add test coverage
Updated existing test with coverage for changes.
=> fix createHandoffEvent activity.type & cleanup

libraries/botbuilder-ai-orchestrator/schemas/Microsoft.OrchestratorRecognizer.schema, libraries/botbuilder-ai-orchestrator/src/orchestratorAdaptiveRecognizer.ts, libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts, libraries/botbuilder-ai-orchestrator/tests/orchestratorAdaptiveRecognizer.test.js
Note: This checkin associated with :
- C# Orchestrator recognizer update ([dotnet pr](https://github.com/microsoft/botbuilder-dotnet/pull/5147))
- A samples update that uses Orchestrator recognizer ([samples pr](https://github.com/microsoft/BotBuilder-Samples/pull/3062))
- Composer updates (@taicchoumsft : Will submit once new SDK released)
- bf-cli updated (@tsuwandy checked in updates)
From the first preview, we've received feedback that our parameter names are confusing. 
This performs the following parameter renames:
modelPath => modelFolder
snapshotPath => snapshotFile
Tests have been updated to reflect new parameter names.
=> Orchestrator Recognizer: Rename misleading parameter names

libraries/adaptive-expressions/.gitattributes, libraries/botbuilder-lg/.gitattributes
Reference issue: #3007
Make the generated files from Antlr as generated to ignore for the repository's language statistics and hidden by default in diffs.
=> [Expression, LG]use gitattributes to mark files as generated

libraries/adaptive-expressions/src/builtinFunctions/string.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
Currently, the string pre-built function does not always work correctly for numeric inputs. 
for example: `string(1.22, 'de-DE')` returns `1.22`. It is not the same as the result of C#.
So I switched the toLocaleString() to d3-format in the string function while a numeric input passed.
With the change, now `string(1.22, 'de-DE')` will return: `1,22`
=> Change the implementation in string a number in the string pre-built function

libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #3258
Add the test for class `NumericEvaluator`
=> [PORT]Add test for NumericEvaluator

libraries/botbuilder-dialogs/src/dialogManager.ts, libraries/botbuilder-dialogs/tests/dialogManager.test.js
Fixes #3269
also added check to the related test
=> Updated dialogManager to send EoC code like dialogHelper

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_TextInputWithNonStringInput.test.dialog, libraries/botbuilder-dialogs-adaptive/src/input/textInput.ts
Port https://github.com/microsoft/botbuilder-dotnet/pull/4966
In adaptive dialog, TextInput action only accept string values, but in some cases, non-string values such as objects will be passed into TextInput action, in such cases, it will throw exceptions instead of throw invalid prompt to users for a valid input. This is not friendly. In this fix, we added the validation of string format for all values and if it's value is not string, it will go into invalid state instead of throwing exceptions. 
- textInput.ts
Test cases added
=> [PORT] Return invalid state instead of throwing exceptions for non-string input of TextInput action

libraries/adaptive-expressions/src/functionUtils.internal.ts
Fixes #3266
Use `Number.EPSILON` for equal check in expression
=> [PORT]Use Number.Epsilon for equal check in expression

libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/HttpRequestMock/httpqnaanswer.mock.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/HttpRequestMock/httpqnaintent.mock.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/HttpRequestMock/httpqnalevel1.mock.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/HttpRequestMock/httpqnanoanswer.mock.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/HttpRequestMock/httpqnaprompts.mock.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/HttpRequestMock/httpqnatopnanswer.mock.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_HttpRequestQnAMakerDialogMock.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_HttpRequestQnAMakerRecognizerMock.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/testScript.test.js, libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts
Fixes #3017 
Ported tests for `QnAMakerDialog` and `QnAMakerRecognizer`.
- Test `QnAMakerDialog` via http request mocks
- Test `QnAMakerRecognizer` via http request mocks
-
=> feat: Mock QnAMaker via http request mocks

libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts, libraries/botbuilder-ai/src/qnamaker-utils/httpRequestUtils.ts, libraries/botbuilder-ai/tests/qnaMaker.test.js
Fixes #2317 
This PR exposed error message from QnAMaker server to allow users locating and fixing errors.
Response type of `HttpRequestUtils` of QnAMaker is not correctly defined, it should be `QnAMakerResults` (while calling `generate` api) or undefined (while calling `train` api).  Check out https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamaker4.0/runtime/generateanswer#response . This PR will fix this.
- Exposed error from QnAMaker server side
- Corrected return type to `QnAMakerResults`
-
=> fix: correct QnAMaker response types and expose error from server

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/skills/skillHandler.ts, libraries/botframework-connector/src/auth/appCredentials.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts, libraries/botframework-connector/tests/connector.test.js
=> port: remove trust service url references

libraries/adaptive-expressions/package.json
Fixes #3274
In #3222, the tinyified adaptive-expressions `browser.js` was malformed and caused Composer to break. This PR fixes the break by disabling a plugin in tinyify.
Using ce99c67, the browserified-and-tinyified `lib/browser.js` is 1,091 KB in size and a 40 KB increase after https://github.com/microsoft/botbuilder-js/pull/3222.
- add --no-flat flag to browserify script in AEL
1. Cloned and setup BotFramework-Composer repo per [README instructions](https://github.com/microsoft/botframework-composer#build-composer-locally)
1. Used `yarn link` to symlink a local clone of the JS repository
1. Built JS repo @`main` (729a577)
1. Ran `yarn startall` in `BotFramework-Composer/Composer` and observed bug
1. Applied fix to `adaptive-expressions` package.json's "browserify" script
1. Rebuilt …
=> fix: add --no-flat flag to browserify script in AEL

.eslintrc.json, libraries/botbuilder-dialogs-adaptive-teams/package.json, libraries/botbuilder-dialogs-adaptive-teams/src/actions/baseTeamsCacheInfoResponseDialog.ts, libraries/botbuilder-repo-utils/package.json, package.json, testing/botbuilder-test-utils/src/jwt.ts, testing/botbuilder-test-utils/src/oauth.ts, testing/consumer-test/package.json, yarn.lock
Ensures we have dependencies listed properly.
EDIT: I reorganized the root eslint config a bit to make the order a bit more natural.
=> fix: add eslint-plugin-import

libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-declarative/package.json, yarn.lock
The `jsonpath` package is no longer required and may cause security issues.
- Removed `jsonpath` from botbuilder-dialogs-adaptive
- Removed `jsonpath` from botbuilder-dialogs-declarative
-
=> fix: removed unused dependency `jsonpath`

libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-declarative/package.json, yarn.lock
Cherrypick for a new 4.12 release candidate.
=> cherrypick: removed `jsonpath` (#3331)

libraries/botbuilder-dialogs-adaptive/src/recognizers/regexRecognizer.ts, libraries/botbuilder-dialogs-adaptive/tests/regexRecognizer.test.js
The value of a regex matched group could be `undefined` in JavaScript. We have to filter these values out.
- RegexRecognizer
-
-
Added test.
=> fix: filter out undefined regex match  groups

libraries/botbuilder-ai/package.json, libraries/botbuilder-dialogs-adaptive-testing/package.json, yarn.lock
Updates package parse-url to resolve a CVE.
Cherry pick of https://github.com/microsoft/botbuilder-js/pull/3337
=> (4.12) cherrypick: #3337

libraries/botbuilder-ai/package.json, libraries/botbuilder-ai/src/index.ts, libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/src/qnaMaker.ts, libraries/botbuilder-ai/src/qnaMakerDialog.ts, libraries/botbuilder-ai/src/qnaMakerRecognizer.ts, libraries/botbuilder-ai/tests/qnaMaker.test.js, libraries/botbuilder-ai/tests/qnaMakerDialog.test.js, libraries/botbuilder-ai/tsconfig.json, libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-adaptive/tests/regexRecognizer.test.js, libraries/botbuilder-dialogs/package.json, libraries/botbuilder-dialogs/src/recognizer.ts, yarn.lock
Fixes #3345 
Ported latest changes of QnAMakerDialog/QnAMakerRecognizer from C#.
- New interface `QnAMakerClient`
- New turn state key `QnAMakerClientKey`
- Added `continueDialog` and `onPreBubbleEvent` to `QnAMakerDialog`
- Added `fillRecognizerResultTelemetryProperties` to `QnAMakerRecognizer`
- Updated access modifiers
Updated corresponding tests.
=> fix: QnAMakerDialog to handle interuption scenarios

libraries/botbuilder-dialogs-adaptive-testing/tests/resources/SelectorTests/SelectorTests_Float_Priority.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/selector.test.js, libraries/botbuilder-dialogs-adaptive/schemas/TriggerConditions/Microsoft.OnCondition.schema, libraries/botbuilder-dialogs-adaptive/src/conditions/onCondition.ts
closes: #3349 
Now the priority in triggers is float number, where 0 is the highest and less than 0 is ignored.
The `priority` property in OnCondition now is NumberExpression, the default value is 0.
=> Port: Switch priority in triggers to float type

build/yaml/botbuilder-js-daily.yml, libraries/botbuilder-repo-utils/src/git.ts, libraries/botbuilder-repo-utils/src/updateVersions.ts, libraries/botbuilder-repo-utils/tests/updateVersions.test.ts
=> fix: better version metadata

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive/src/adaptiveComponentRegistration.ts, libraries/botbuilder-dialogs-adaptive/src/index.ts, libraries/botbuilder-dialogs-adaptive/src/languageGenerationComponentRegistration.ts
Wrap `TemplateInterface` based classes into `LanguageGenerationComponentRegistration` to match the implementation in C#: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGenerationComponentRegistration.cs
- LanguageGenerationComponentRegistration
-
-
Updated related tests.
=> feat: language generation component registration

libraries/botbuilder-runtime-integration-express/.eslintrc.json, libraries/botbuilder-runtime-integration-express/.gitignore, libraries/botbuilder-runtime-integration-express/README.md, libraries/botbuilder-runtime-integration-express/package.json, libraries/botbuilder-runtime-integration-express/src/index.ts, libraries/botbuilder-runtime-integration-express/tsconfig.json
Fixes #3352
Adds `botbuilder-runtime-integration-express` to enable JS Runtime bots to use `express` instead of `restify`.
- `start()`, makeApp()`, `Options` are the exports
- `index.d.ts` exposes a public dependency on `runtypes`
- `runtypes` is a new public dependency in `botbuilder-runtime` used for type checking at compile time and runtime.
Tested using [`stgum/runtime-contoso`](https://github.com/microsoft/botbuilder-js/tree/stgum/runtime-contoso) (forked from `jpg/runtime-contoso`)
=> feat: add botbuilder-runtime-integration-express

libraries/botbuilder-runtime-integration-restify/package.json, libraries/botbuilder-runtime-integration-restify/src/index.ts
Adds `messagingEndpointPath: string` to `botbuilder-runtime-integration-restify.Options` for configurability of messaging endpoint. `start()` uses ternary and spread operators to combine `defaultOptions` with the optional passed in `options`. 
https://github.com/microsoft/botbuilder-js/blob/d44179f6f344b2882cc585bd373509852ba91e10/libraries/botbuilder-runtime-integration-restify/src/index.ts#L37-L45
The value for `defaultOptions.messagingEndpointPath` is `'/api/messages'`.
`makeServer()` now takes the `messagingEndpointPath` as its first argument.
To avoid annoying JS runtime errors around the incorrect type being passed in for `options`, `botbuilder-stdlib` was added to make use of `tests.isObject` in the ternary operator. 
https://github.com/microsoft/botbuilder-js/blob/1774d5104b1e40073 …
=> fix: add messagingEndpointPath to Options in restify integration lib

libraries/adaptive-expressions/src/parser/parseErrorListener.ts, libraries/adaptive-expressions/tests/badExpression.test.js
Fixes #3368
The error thrown by `Antlr` is not readable for non-developer users. Change it to the general expression format error.
=> port: Make syntax error message more readable in Expression

libraries/botbuilder-dialogs/src/dialogHelper.ts, libraries/botbuilder-dialogs/src/dialogManager.ts, libraries/botbuilder-dialogs/tests/dialogManager.test.js
Fixes #3389
Feature parity with https://github.com/microsoft/botbuilder-dotnet/pull/5294
Existing tests work as expected
=> feat: refactor DialogHelper & DialogManager to follow .NET impl

libraries/browser-functional-tests/package.json, yarn.lock
Bump chromedriver in browser-functional-tests to `latest` (89.0.0) to fix failing tests
=> fix: bump chromedriver to ^89.0.0 in browser-functional-tests

libraries/botbuilder-runtime-integration-express/src/index.ts, libraries/botbuilder-runtime-integration-restify/src/index.ts, libraries/botbuilder-runtime/package.json, libraries/botbuilder-runtime/src/configuration.ts, libraries/botbuilder-runtime/src/index.ts, libraries/botbuilder-runtime/test/configuration.test.ts, libraries/botbuilder-runtime/test/settings/base.json, yarn.lock
Encapsulate port handling that has leaked into the generators ([see here](https://github.com/microsoft/botframework-components/pull/746/files#diff-4d0da3953d67d3a6198cbd063f0efcf70af9240a5a1e09875b50715d155ed5bfR7)).
Fixes https://github.com/microsoft/botbuilder-js/issues/3407
=> feat: config argv source, runtime port handling

libraries/botbuilder/tests/inspectionMiddleware.test.js, libraries/botbuilder/tests/skills/skillHandler.test.js, libraries/botbuilder/tests/statusCodeError.test.js, libraries/botbuilder/tests/teamsActivityHandler.test.js, libraries/botbuilder/tests/teamsInfo.test.js
Partial fix for #3226. This will be done in multiple PRs.
(Alphabetically such that `botbuilder` comes before `botbuilder-`)
* `adaptive-expressions-ie11` through `botbuilder`, inclusive
* Many tests in [`channelServiceRoutes.test.js`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/tests/channelServiceRoutes.test.js?rgh-link-date=2021-03-19T18%3A34%3A40Z#L118)
Replaces the use of `done()` in tests with proper `async/await`.
- `done` => `async/await`
- Remove `done` completely when used in synchronous tests. For example, it was in some `beforeEach()` hooks, but it's not needed; [nock doesn't even use it there](https://github.com/nock/nock/blob/af7105c3c1731be5c0f2051b20bd44ead006e177/tests/setup.js#L12)
- Remove some of the try/catches that are no longer needed …
=> Replace done w/ async in tests part 1

libraries/botbuilder-ai/tests/luisSdk.test.js, libraries/botbuilder-ai/tests/luisV3OracleTests.test.js, libraries/botbuilder-ai/tests/qnaMaker.test.js, libraries/botbuilder-applicationinsights/tests/TelemetryWaterfallTest.test.js, libraries/botbuilder-applicationinsights/tests/telemetryInitializer.test.js
Partial fix for #3226. This will be done in multiple PRs.
(Alphabetically such that `botbuilder` comes before `botbuilder-`)
* `botbuilder-ai` through `botbuilder-applicationinsights`, inclusive
* Many tests in [`TelemetryWaterfallTest.test.js`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-applicationinsights/tests/TelemetryWaterfallTest.test.js)
Replaces the use of `done()` in tests with proper `async/await`.
- `done` => `async/await`
- Remove `done` completely when used in synchronous tests. For example, it was in some `beforeEach()` hooks, but it's not needed; [nock doesn't even use it there](https://github.com/nock/nock/blob/af7105c3c1731be5c0f2051b20bd44ead006e177/tests/setup.js#L12)
- Remove some of the try/catches that are no longer needed since we …
=> Replace done w/ async part 2

libraries/adaptive-expressions/src/expression.ts, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_OAuthInputLG.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/TestScriptTests_OAuthInputMockProperties.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/TestScriptTests/main.lg, libraries/botbuilder-dialogs-adaptive-testing/tests/testScript.test.js, libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/tests/oauthPrompt.test.js, libraries/botbuilder-lg/src/templates.ts
Fixes #3306 
Enabled LG syntax in `OAuthInput`'s title and text.
Fixed blocking bugs as well.
- Refactored `OAuthPrompt` to expose `sendOAuthCard()`
- Updated `OAuthInput` to enable LG syntax
- Fixed a blocking bug in Expression.parse() to trim starting `=` of expressions
- Fixed a blocking bug in `Templates` to recognize multi line text correctly
Ported tests as well.
=> port: enable LG syntax in OAuthInput

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_TextInput_WithEmptyPrompt.test.dialog, libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
=> port: Check null for input prompt

libraries/botbuilder-core/src/index.ts, libraries/botbuilder-core/src/skills/index.ts, libraries/botbuilder-core/src/skills/skillConversationIdFactory.ts, libraries/botbuilder-runtime/src/index.ts, libraries/botframework-connector/src/auth/allowedCallersClaimsValidator.ts, libraries/botframework-connector/src/auth/index.ts
=> port: move classes/helpers out of runtime

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_TextInputWithInvalidResponse.test.dialog, libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
=> port: do nothing when activity is null

libraries/botbuilder-runtime/src/index.ts, libraries/botbuilder/package.json, libraries/botbuilder/src/index.ts, libraries/botbuilder/src/setSpeakMiddleware.ts, libraries/botbuilder/tests/setSpeakMiddleware.test.js, libraries/botframework-schema/src/index.ts, yarn.lock
Fixes https://github.com/microsoft/botbuilder-js/issues/3432
=> port: add speach middleware to runtime

libraries/botbuilder-core/src/botAdapter.ts, libraries/botbuilder-runtime-core/src/configuration.ts, libraries/botbuilder-runtime/src/configuration.ts, libraries/botbuilder-runtime/src/configurationResourceExplorer.ts, libraries/botbuilder-runtime/src/coreBotAdapter.ts, libraries/botbuilder-runtime/src/index.ts, libraries/botbuilder-runtime/test/configuration.test.ts, libraries/botbuilder-runtime/test/index.test.ts
- Fixes #3442 
- Ports `ConfigurationResourceProvider`, which is part of #3423
- Makes configuration methods sync which is compatible with .NET
=> feat: port several runtime changes

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/streaming/botFrameworkAdapterStreaming.test.js, libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts
Fixes #3449
- Make BotFrameworkAdapter.useNamedPipe idempotent by checking for StreamingServer and new `namedPipeName` member
- Add `private namedPipeName?: string` member to BotFrameworkAdapter
- Minor docstring fix in `botframework-streaming.NamedPipeServer`
Add new tests for new behavior in useNamedPipe
=> fix: make useNamedPipe idempotent if already connected to pipeName

libraries/botbuilder-core/src/activityHandler.ts, libraries/botbuilder-core/src/index.ts, libraries/botbuilder-core/src/invokeException.ts, libraries/botframework-schema/src/index.ts
=> port: adaptive card invoke

libraries/botbuilder-ai-orchestrator/package.json
Update orchestrator package to point at "`rc`" tag for `orchestrator-core` dependency in preparation for Bot Framework rc.
=> Update Orchestrator Recognizer to use "rc" orchestrator-core dependency.

libraries/adaptive-expressions/src/builtinFunctions/dateReadBack.ts
Fixes #3378
`dateReadBack` test was failing when run locally. Turns out, there was a bug in the code that only expressed itself when the machine running the code wasn't on UTC (or something like that).
The issue is how `timestamp1` was getting set.
The code: `const timestamp1 = new Date(dayjs(args[0]).format(dateFormat));`
`args[0]` was a timestamp, `'2018-03-15T13:00:00.111Z'`
1. `dayjs()` call would convert the timestamp to a dayjs Date object (good so far)
2. It would then get formatted to `2018-03-15` (good so far)
3. But then, we'd call `new Date()` on `2018-03-15`, which interprets the input as UTC and creates a Date object in PST, so it would more or less become `2018-03-14` and be off a whole day
It now passes, locally:
=> Fix dateReadBack test

libraries/botbuilder-ai/src/qnaCardBuilder.ts, libraries/botbuilder-ai/tests/qnaMakerDialog.test.js
Fixes #3431
This PR fixes QnACardBuilder.getSuggestionsCard() to correctly use `QnAMakerDialog.activeLearningCardTitle` as expected.
- Fix call to CardFactory.heroCard() in QnACardBuilder.getSuggestionsCard()
Add unit test coverage for fix.
=> fix: getSuggestionsCard() to set card title

libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts
Adds proper error handling to integration servers.
Fixes https://github.com/microsoft/botbuilder-js/issues/3493
=> fix: async error handling for request handlers

libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts
Cherry pick of https://github.com/microsoft/botbuilder-js/pull/3494
=> cherrypick: async error handling for request handlers (#3492)

libraries/botbuilder-dialogs-adaptive-runtime/src/coreBotAdapter.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
Couple oversights:
- Hard coded dummy appId/appPassword for Skills
- Mis-port of CoreBotAdapter due to differences between .NET CloudAdapter and JS BotFrameworkAdapter
=> fix: resolve bad runtime adapter/skill auth configuration

libraries/botbuilder-repo-utils/src/updateVersions.ts, libraries/botbuilder-repo-utils/tests/updateVersions.test.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/3502
=> fix: add sha to prerelease instead of build metadata

libraries/botbuilder-dialogs-adaptive-runtime-core/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-express/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/package.json, libraries/botbuilder-dialogs-adaptive-runtime/package.json, yarn.lock
Runtypes 5.2.0 has an issue and is deprecated. v6 is coming soon, but we should lock down to 5.1.x for R13.
=> fix: lock runtypes to 5.1.x version range

libraries/botbuilder-dialogs-adaptive-runtime-core/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-express/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/package.json, libraries/botbuilder-dialogs-adaptive-runtime/package.json, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts, libraries/botbuilder/src/setSpeakMiddleware.ts, libraries/botbuilder/tests/setSpeakMiddleware.test.js, yarn.lock
=> cherrypick: runtypes lock and set speak middleware fixes

libraries/botbuilder-ai/tests/qnaMakerDialog.test.js
Addresses [PR feedback](https://github.com/microsoft/botbuilder-js/pull/3475#discussion_r603593050) for #3475.
=> fix: use sinon for QnAMakerDialog test

libraries/botbuilder-dialogs-adaptive-runtime/src/coreBot.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/coreBotAdapter.ts, libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts, libraries/botbuilder-dialogs/src/dialogContext.ts
Fixes #3512
Seems like we missed a change in `beginSkill` that fetches the conversation state from the turn context. @stevengum can you triple check that?
=> port: dialog context dialog manager prop obsolete

libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/3520
=> fix: small runtime tweaks

libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
* fix: azure logs issues
Can't log after response is written for some reason.
* fix: watch files in dev only
* fix: load appsettings files based on NODE_ENV
Roughly maps to behavior added via https://github.com/microsoft/botbuilder-dotnet/pull/5421
=> cherrypick: small runtime tweaks (#3519)

libraries/botbuilder-core/src/skills/skillConversationIdFactory.ts, libraries/botbuilder-dialogs-adaptive-testing/package.json, libraries/botbuilder-dialogs-adaptive-testing/tests/adaptiveDialog.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/AdaptiveDialogTests/AdaptiveDialog_ParentBotInterruption.test.dialog, libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts, libraries/botbuilder-dialogs/src/skillDialog.ts
=> port: resume dialog fix from .net

libraries/botbuilder-core/src/skills/skillConversationIdFactory.ts, libraries/botbuilder-dialogs-adaptive-testing/package.json, libraries/botbuilder-dialogs-adaptive-testing/tests/adaptiveDialog.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/AdaptiveDialogTests/AdaptiveDialog_ParentBotInterruption.test.dialog, libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts, libraries/botbuilder-dialogs/src/skillDialog.ts
=> cherrypick: port resume dialog fix from .net (#3525)

libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.HttpRequest.schema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.OAuthInput.schema, libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts, libraries/botbuilder-dialogs/src/dialogHelper.ts, libraries/botbuilder-dialogs/src/dialogManager.ts, libraries/botbuilder-dialogs/src/memory/scopes/turnMemoryScope.ts, libraries/botbuilder-dialogs/tests/dialogManager.test.js, libraries/tests.schema
Fixes #3536
Fixes #3537
Fixes #3538
Fixes #3539
=> port: several parity issues

libraries/botbuilder-dialogs-adaptive-runtime/generated/luis.settings.mocha.westus.json, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime/test/appsettings.json, libraries/botbuilder-dialogs-adaptive-runtime/test/index.test.ts
=> fix: merge generated config into runtime config

libraries/botbuilder-ai-luis/.eslintrc.json, libraries/botbuilder-ai-luis/.gitignore, libraries/botbuilder-ai-luis/README.md, libraries/botbuilder-ai-luis/package.json, libraries/botbuilder-ai-luis/src/index.ts, libraries/botbuilder-ai-luis/tsconfig.json, libraries/botbuilder-ai-qna/.eslintrc.json, libraries/botbuilder-ai-qna/.gitignore, libraries/botbuilder-ai-qna/README.md, libraries/botbuilder-ai-qna/package.json, libraries/botbuilder-ai-qna/src/index.ts, libraries/botbuilder-ai-qna/tsconfig.json, libraries/botbuilder-dialogs-adaptive-runtime/package.json, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
=> feat: export ai components for runtime consumption

libraries/botbuilder-ai-orchestrator/src/index.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/3598
=> fix: export default orchestrator bot component

libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
=> fix: conflict -> precondition failed

libraries/botframework-connector/src/auth/appCredentials.ts, libraries/botframework-connector/src/auth/authenticationError.ts, libraries/botframework-connector/src/auth/certificateAppCredentials.ts, libraries/botframework-connector/src/auth/channelValidation.ts, libraries/botframework-connector/src/auth/emulatorValidation.ts, libraries/botframework-connector/src/auth/enterpriseChannelValidation.ts, libraries/botframework-connector/src/auth/governmentChannelValidation.ts, libraries/botframework-connector/src/auth/governmentConstants.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts, libraries/botframework-connector/src/auth/openIdMetadata.ts, libraries/botframework-connector/src/auth/serviceClientCredentialsFactory.ts, libraries/botframework-connector/src/auth/skillValidation.ts, libraries/botframework-connector/src/emulatorApiClient.ts
#minor
Addresses lint errors in `botframework-connector`, the new doc strings are either a verbatim port from .NET or derived from examples in the JS SDK.
=> fix: cleanup lint errors in bf-connector

libraries/botbuilder-dialogs-adaptive-runtime-core/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime-integration-express/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/package.json, libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime/package.json, libraries/botbuilder-dialogs-adaptive-runtime/src/configuration.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts, libraries/botbuilder-dialogs/package.json, yarn.lock
=> bump: runtypes

libraries/botbuilder-dialogs-declarative/tests/schemaMergeTest.js
Fixes #3687 
When installing bf-cli, there is sometimes a prompt during install to allow telemetry.
We need to set an environment variable so the prompt doesn't appear and halt install, causing a timeout.
See: https://github.com/microsoft/botframework-cli#enable-telemetry-in-continuous-integration-pipelines
=> fix: auto-disable telemetry for schema tests

libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.EmitEvent.schema, libraries/botbuilder-dialogs-adaptive/src/actions/emitEvent.ts, libraries/tests.schema
Fixes #3594 
Added a new "Handled Property" property which lets you specify where to return a flag indicating if the event was handled.
=> port: add handledProperty to emitEvent

libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts, libraries/botbuilder-azure-blobs/package.json, libraries/botbuilder-azure-blobs/src/blobsStorage.ts, libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts, libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts
* fix: more permissive type assertions
Fixes #3684
* fix: json serialization cycles (#3693)
See https://github.com/microsoft/BotFramework-Composer/issues/7854 for more details.
* fix: limit serialized form of storage types
These can end up in serialized JSON transcripts as well, so to limit the chance of including connection strings or other
secrets we should restrict their serialized forms.
Co-authored-by: Steven Gum <14935595+stevengum@users.noreply.github.com>
=> cherrypick: two more runtime fixes

libraries/botbuilder-stdlib/src/index.ts, libraries/botbuilder-stdlib/src/retry.ts, libraries/botbuilder-stdlib/tests/retry.test.js, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botframework-streaming/package.json, libraries/botframework-streaming/src/interfaces/IStreamingTransportServer.ts, libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts, libraries/botframework-streaming/src/payloadTransport/payloadReceiver.ts, libraries/botframework-streaming/src/payloadTransport/payloadSender.ts, libraries/botframework-streaming/src/utilities/createNodeServer.ts, libraries/botframework-streaming/tests/NamedPipe.test.js, libraries/botframework-streaming/tests/PayloadSender.test.js, libraries/botframework-streaming/tests/ProtocolAdapter.test.js
- Remove unnecessary autoReconnect logic
- Simplify connection management
- Properly support client reconnection to incoming/outgoing servers
Fixes #3472
=> fix: named pipe issues

libraries/botframework-connector/package.json, yarn.lock
=> bump: adal-node to 0.2.2

package.json
=> fix: clean command should ignore missing

libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts
=> fix: ignore node_modules declarative assets

libraries/botbuilder-dialogs-adaptive-testing/src/httpRequestMocks/httpRequestSequenceMock.ts, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ChooseEntityTests/LuisChooseEntity-wheat.mock.dialog
Fixes #3712 
See linked issue for more details, but this is for parity w/ .NET.
Allow wildcards in URL paths by replacing the path with a RegExp and replacing `*` with `.*`.
Changed 1 test, which passes. Others will change as part of another PR.
=> feat: allow wildcard in mock paths

libraries/browser-functional-tests/package.json, yarn.lock
#minor
Should fix: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=248670&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9
Edit: [_Does_ fix](https://fuselabs.visualstudio.com/86659c66-c9df-418a-a371-7de7aed35064/_build/results?buildId=248682)
=> chore: bump chromedriver to ^90.0.1 in browser-functional-tests

.eslintrc.json, libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts, libraries/botbuilder-ai/src/luisAdaptivePredictionOptions.ts, libraries/botbuilder-ai/src/luisAdaptiveRecognizer.ts, libraries/botbuilder-ai/src/luisComponentRegistration.ts, libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/src/luisRecognizerOptionsV2.ts, libraries/botbuilder-ai/src/luisRecognizerOptionsV3.ts, libraries/botbuilder-ai/src/luisTelemetryConstants.ts, libraries/botbuilder-ai/src/qnaCardBuilder.ts, libraries/botbuilder-ai/src/qnaMaker.ts, libraries/botbuilder-ai/src/qnaMakerComponentRegistration.ts, libraries/botbuilder-ai/src/qnaMakerDialog.ts, libraries/botbuilder-ai/src/qnaMakerRecognizer.ts, libraries/botbuilder-ai/src/qnaTelemetryConstants.ts, libraries/botbuilder-ai/src/qnamaker-utils/activeLearningUtils.ts, libraries/botbuilder-ai/src/qnamaker-utils/bindToActivity.ts, libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts, libraries/botbuilder-ai/src/qnamaker-utils/httpRequestUtils.ts, libraries/botbuilder-ai/src/qnamaker-utils/trainUtils.ts, libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts, libraries/botbuilder-applicationinsights/src/telemetryInitializerMiddleware.ts, libraries/botbuilder-azure-queues/src/azureQueueStorage.ts, libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts, libraries/botbuilder-azure/src/blobStorage.ts, libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts, libraries/botbuilder-azure/src/cosmosDbStorage.ts, libraries/botbuilder-azure/src/doOnce.ts
Part 1 of #3518
#minor
Removed `public` access modifier from following packages:
- botbuilder-ai-orchestrator
- botbuilder-ai
- botbuilder-applicationinsights
- botbuilder-azure-queues
- botbuilder-azure
=> chore: remove unnecessary public access modifier

libraries/botbuilder-dialogs/src/choices/channel.ts, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/tests/choices_channel.test.js, libraries/botbuilder-dialogs/tests/choices_choiceFactory.test.js, libraries/botframework-schema/src/index.ts
Fixes #3603
Targeting `cloud-adapter` to avoid future merge conflicts
- Remove Cortana from `Channels` enum in botframework-schema, see https://github.com/microsoft/botbuilder-js/issues/3603#issuecomment-856311472
- Hidden public helper `hasMessageFeed()` always returns `true` (no change on visibility in declarations)
- `supportsCardActions()` no longer has `Channels.Cortana` case (will use default `false` for `'cortana'` channelId).
- remove/update Cortana specific tests in `choices_channel.test.js` and `choices_choiceFactory.test.js`
- `OAuthPrompt.channelSupportsOAuthCard()` no longer has `Channels.Cortana` case (will use default `true` for `'cortana'` channelId).
=> fix: remove Cortana from Channels enum

libraries/botbuilder-core/tests/ActivityHandler.test.js, libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
#minor
Per [the OBI](https://github.com/microsoft/botframework-obi/blob/jeffders/adaptiveCards2/protocols/botframework-protocol/botframework-action-execute.md#authentication-field), `AdaptiveCardInvokeValue.authentication` should actually be a `TokenExchangeInvokeRequest`, which has the same properties as `AdaptiveCardAuthentication`, which is now superfluous.
In working on this, I also noticed that [this PR](https://github.com/microsoft/botbuilder-js/pull/3716) was actually already covered.
- Remove `AdaptiveCardAuthentication` and replace with `TokenExchangeInvokeRequest`
- Revert [this PR](https://github.com/microsoft/botbuilder-js/pull/3716) (manually, because I didn't realize I should've just called `git revert` until I had already manually removed it.
- Added tests
=> fix: adjust adaptiveCard/action handling

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsInfo.ts, libraries/botbuilder/tests/teamsInfo.test.js, libraries/botframework-connector/src/teams/models/index.ts, libraries/botframework-connector/src/teams/models/mappers.ts, libraries/botframework-connector/src/teams/models/teamsMappers.ts, libraries/botframework-connector/src/teams/operations/teams.ts, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts
Fixes #3723 
Adds a `getMeetingInfo` method to `TeamsInfo`.
Bots implementing this must add this to their `manifest.json`:
```json
"webApplicationInfo": {
"id": "<MicrosoftAppId>",
"resource": "<urlToApp>",
"applicationPermissions": [
"OnlineMeeting.ReadBasic.Chat"
]
}
```
Per Teams, this is currently only available for:
1. Tenets who have the RSC permission for `OnlineMeeting.ReadBasic.Chat` set to Allowed. This won't be available for the Graph API permissions set until 6/17, or
2. Developers with the bot AppId whitelisted by the Teams Team (currently only available for Microsoft partner teams
=> feat: add getMeetingInfo to TeamsInfo

libraries/adaptive-expressions/src/converters/enumExpressionConverter.ts
I tested the HTTP action in Composer with the .NET runtime, and it appears that enum resolution is case insensitive, so this PR replicates that behavior. I tested this by linking against a Composer bot and manually editing the enum value in the dialog to different casing variations.
Fixes https://github.com/microsoft/BotFramework-Composer/issues/7834
Fixes https://github.com/microsoft/botbuilder-js/issues/3744
=> fix: make enum lookup case insensitive

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_Foreach_Object.test.dialog, libraries/botbuilder-dialogs-adaptive/src/actions/forEach.ts
Fixes #3769
Make it possible for Microsoft.ForEach action to  traverse its keys and values.
There is no change while the value of `itemsProperty` is array.
If the property value is Object, user could use the "index" property to get the current key, and use "value" value to get current value.
For example:
given such object for property `dialog.item`:
```
{
"k1":"v1",
"K2":"v2"
}
```
and the action:
```
{
"$kind": "Microsoft.Foreach",
"itemsProperty": "dialog.item",
"actions": [
{
"$kind": "Microsoft.SendActivity",
"activity": "index is: ${dialog.foreach.index}, and value is: ${dialog.foreach.value}"
}
]
}
```
The result would be:
`index is: k1 and value is v1` and `index is: k2 and value is v2`
[indicesAndValues](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adapti …
=> port: Support iteration for object in ForEach action

libraries/botbuilder-core/src/activityHandler.ts, libraries/botbuilder-core/src/activityHandlerBase.ts, libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/package.json, libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts, yarn.lock
Fixes #3724 
Adds support to TeamsActivityHandler for meeting start/end events.
Bots implementing this must add this to their `manifest.json`:
```json
"webApplicationInfo": {
"id": "<MicrosoftAppId>",
"resource": "<urlToApp>",
"applicationPermissions": [
"OnlineMeeting.ReadBasic.Chat"
]
}
```
Note that somebody needs to actually start/join the meeting for this to work. The scheduled start/end times mean nothing for this event.
=> feat: add support for Teams meeting start/end events

libraries/botbuilder-core/src/activityHandler.ts, libraries/botbuilder-core/tests/ActivityHandler.test.js, libraries/botbuilder/tests/teamsActivityHandler.test.js
=> fix: return full response w/ adaptiveCard invoke action

libraries/botbuilder-core/src/turnContext.ts, libraries/botbuilder-dialogs-declarative/tests/jsonLoad.test.js, libraries/botbuilder-dialogs-declarative/tests/resources/JsonDialog/ReplyToId.main.dialog, libraries/botframework-schema/src/activityEx.ts, libraries/botframework-schema/tests/activityEx.test.js, yarn.lock
Fixes #3732
When the activity is the first one of the conversation and it's sent from bot to user, the ReplyToId was assigned to the bogus ConversationUpdate activity's id. The fix is to not assign the bogus ReplyToId if previous activity is the ConversationUpdate activity
- Do not assign ReplyToId if conversantionReference is from ConversationUpdate activity
- Add test tests to test the changes
Tests are added
=> fix: first activity from bot to user has fake replyToId value

libraries/botbuilder-core/src/activityHandlerBase.ts, libraries/botbuilder-core/tests/activityHandlerBase.test.js
Fixes #3795 
Simple change for .NET parity. We just needed to allow reactions `added` and `removed` to _both_ be handled.
=> fix: handle reactions added/removed separately

libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.OAuthInput.schema, libraries/tests.schema
Fixes #3797 
Note: The .NET PR also replaces this for TestBot, but we don't have that or anything like it (particularly, the testbot.schema file), so the JS port gets 2 of the 3 changes.
=> fix: OAuth prompt should store in turn.token, not dialog.token

libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-core/src/botAdapter.ts, libraries/botbuilder-core/src/cloudAdapterBase.ts
=> feat: create conversation

libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/Analyzer.lg
=> fix: add sortNumber test case

libraries/botbuilder-dialogs-adaptive-runtime/src/coreBot.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts, libraries/botframework-connector/src/auth/passwordServiceClientCredentialFactory.ts, libraries/botframework-connector/tests/passwordServiceClientCredentialFactory.test.js
#minor
- Removes `SkillHttpClient` node from Adaptive runtime in favor of `BotFrameworkAuthentication.createBotFrameworkClient()` ([`AdaptiveDialogBot`](https://github.com/microsoft/botbuilder-dotnet/blob/e5b4e812171015d3b7bf5fb077ef7fbdb6dc226c/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs#L98) in .NET)
- The `addSkills()` method is now more aligned with .NET's implementation ([`AddBotRuntimeSkills()`](https://github.com/microsoft/botbuilder-dotnet/blob/e5b4e812171015d3b7bf5fb077ef7fbdb6dc226c/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs#L115))
- Also removes `SkillHttpCllient` dependency `ICredentialProvider` from Adaptive runtime
- Ran code formatter in `botbuilder-dialogs-adaptive-runtime/src/index.ts`
- …
=> chore: use BFAuthentication for BFClient in runtime, fix comparison bug

libraries/botbuilder/src/teamsInfo.ts, libraries/botbuilder/tests/teamsInfo.test.js
#minor
Many of the TeamsInfo methods fail with ["This method requires a connector client."](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsInfo.ts#L418) when using `CloudAdapter`. This is because most of them have a check for `adapter.createConnectorClient()`, which doesn't exist in CloudAdapter.
Align JS TeamsInfo with [.NET](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs#L330) by having the adapter get pulled from the `TurnState`.
This also required a lot of testing changes since the adapter didn't exist on the `TurnState` in the tests. The JS tests now manually add the adapter to the `TurnState`, [as also done in .NET](https://github.com/microsoft/botbuilder-dotnet/blob/main/tests/Microsoft. …
=> fix: enable TeamsInfo methods to work with CloudAdapter

libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts
=> fix: Bug in orchestratorRecognizer.ts InitializeModel

libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
=> port: runtime docs

libraries/botbuilder-repo-utils/src/updateVersions.ts, libraries/botbuilder-repo-utils/tests/updateVersions.test.ts
.NET does versions like 4.14.0-rc0.preview, i.e. the "build label" comes before "preview".
#minor
=> fix: build label before state label

libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
Cherrypick a few more changes for 4.14.
#minor
=> feat: cherrypick orchestrator fix, runtime docs

.eslintrc.json, libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts, libraries/botbuilder-ai/src/luisAdaptiveRecognizer.ts, libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/tests/qnaMaker.test.js, libraries/botbuilder-ai/tests/qnaMakerDialog.test.js, libraries/botbuilder-applicationinsights/tests/telemetryInitializer.test.js, libraries/botbuilder-azure-queues/src/azureQueueStorage.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts, libraries/botframework-connector/src/auth/authenticationError.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts, libraries/botframework-connector/src/auth/skillValidation.ts, libraries/botframework-connector/tests/auth/authenticationError.test.js, libraries/botframework-connector/tests/connector.test.js, libraries/botframework-connector/tests/simpleCredentialProvider.test.js, libraries/botframework-schema/src/activityEx.ts, libraries/botframework-schema/tests/activityEx.test.js, libraries/botframework-schema/tests/speechConstants.test.js, libraries/botframework-streaming/src/utilities/createNodeServer.ts, libraries/botframework-streaming/src/webSocket/nodeWebSocketClient.ts
=> chore: estlint quotes rule

libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.BeginSkill.uischema, libraries/tests.uischema
=> port: beginskill uischema fix

libraries/botbuilder-dialogs-adaptive-runtime/src/configuration.ts, libraries/botbuilder-dialogs-adaptive-runtime/test/configuration.test.ts
https://github.com/microsoft/botbuilder-js/pull/3840 introduced an issue with configuration key handling that broke the behavior of `.get()`. This PR fixes that handling and adds tests to ensure the behavior remains consistent going forward. The code was not released as part of 4.14 so it doesn't need patching.
#minor
=> fix: configuration key handling

libraries/adaptive-expressions/src/builtinFunctions/merge.ts, libraries/adaptive-expressions/tests/badExpression.test.js, libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #3857
extend merge built-in function
Originally, `merge` only accepts objects.
For example:
`merge({}, {k1:'v1'}, {k2:'v2', k3:'v3'})`
but sometimes the input is an array, and there is no way to convert the array into a list of objects.
The solution is to change the merge function to accept `array` type as well.
The logic is, if the item is array, merge its object children.
For example:
`merge({k1:'v1'}, [{k2:'v2'}, {k3: 'v3'}], {k4:'v4'})`
The second item is array, if we follows the previous practice, would get en error which shows the input only accepts "structure object", but not array. But now, you would get the right result:
`{  ​"k1":"v1",  ​"k2":"v2",  ​"k3":"v3", "k4":"v4"} `
But it should be noted that, the flatten operator would be applied for only once. If the array is …
=> port: extend merge built-in function

libraries/botbuilder-core/src/recognizerResult.ts, libraries/botbuilder-core/tests/getTopScoringIntent.test.js, libraries/botbuilder-dialogs-adaptive/src/recognizers/crossTrainedRecognizerSet.ts
Fixes [Composer#8368](https://github.com/microsoft/BotFramework-Composer/issues/8368). fixes #minor.
There is a minor drift between the dotnet and nodeJs implementation of `getTopScoringIntent`.  
1. In the NodeJS implementation, `topIntent` is declared but not initialized. In the case of empty `intents` bag, can return `undefined`.  
[NodeJS Implementation](https://github.com/microsoft/botbuilder-js/blob/4ba6d97ec3a80446184c8ad4136b1808dee6158f/libraries/botbuilder-core/src/recognizerResult.ts#L49)
``` javascript
let topIntent: string;
```
In the dotnet implementation, the topIntent is initialized.
[Dotnet Implementation](https://github.com/microsoft/botbuilder-dotnet/blob/1220aed51d97a300a73b46c230dc49867483a97c/libraries/Microsoft.Bot.Builder/RecognizerResultExtensions.cs#L30)
``` c# …
```
=> fix: Make getTopScoringIntent return '' instead of undefined

libraries/botframework-schema/src/activityEx.ts
Fixes #3874
This PR fixes a parity issue in the [getContinuationActivity](https://github.com/southworks/botbuilder-js/blob/main/libraries/botframework-schema/src/activityEx.ts#L443) method, adding the missing `type` property that its DotNet counterpart has ([link](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/ConversationReference.cs#L95)). Otherwise when the `ActivityHandler.run` method is executed will validate and throw the [Activity is missing its type](https://github.com/southworks/botbuilder-js/blob/main/libraries/botbuilder-core/src/activityHandlerBase.ts#L401) error when the `type` property is not found in the Activity.
- Added the `type` property to be an `ActivityTypes.Event` in the `getContinuationActivity` method.
=> fix: [#3874] Parity issue with getContinuationActivity method missing the type property

libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts
=> fix: blobs transcript date filter

libraries/botbuilder-repo-utils/package.json, libraries/botbuilder-repo-utils/src/updateVersions.ts, libraries/botbuilder-repo-utils/src/workspace.ts, libraries/botbuilder-repo-utils/tests/updateVersions.test.ts, yarn.lock
MyGet and npm have inconsistent handling for semver metadata which causes several nightly tests to fail. Let's revert to
prerelease for dates.
#minor
=> fix: prerelease for date instead of metadata

libraries/botbuilder-repo-utils/package.json, libraries/botbuilder-repo-utils/src/updateVersions.ts, libraries/botbuilder-repo-utils/tests/updateVersions.test.ts, yarn.lock
Bruce educated me on semver sorting, so here's one more small fix along with a unit test 😄 
#minor
=> fix: date precedence for semver sorting

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/cloudAdapter.ts, libraries/botframework-streaming/src/assemblers/payloadAssembler.ts, libraries/botframework-streaming/src/disassemblers/responseDisassembler.ts
=> fix: parse attachments from streaming request

libraries/botbuilder-dialogs-adaptive-testing/tests/multiLanguageRecognizer.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/MultiLanguageRecognizerTests/MultiLanguageRecognizerTest_RecognizerCaseInsensitivity.test.dialog, libraries/botbuilder-dialogs-adaptive/src/recognizers/multiLanguageRecognizer.ts
Fixes #3892
Change MultiLanguageRecognizer to case insensitive
=> port: Make Multi-language recognizer case-insensitive

libraries/botframework-connector/package.json, yarn.lock
`adal-node` published `0.2.3` which moves to `@xmldom/xmldom` as a CVE resolution.
#minor
=> chore: bump adal-node for xmldom CVE

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_MissingProperty.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/main.lg, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/sub.lg, libraries/botbuilder-dialogs-adaptive/etc/botbuilder-dialogs-adaptive.api.md, libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs-adaptive/src/functions/index.ts, libraries/botbuilder-dialogs-adaptive/src/functions/missingPropertiesFunction.ts, libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts, libraries/botbuilder-dialogs-adaptive/src/generators/templateEngineLanguageGenerator.ts, libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts, libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts, libraries/botbuilder-dialogs-adaptive/tests/LGGenerator.test.js, libraries/botbuilder-dialogs-adaptive/tests/lg/properties.lg, libraries/botbuilder-dialogs/etc/botbuilder-dialogs.api.md, libraries/botbuilder-dialogs/src/dialogContext.ts, libraries/botbuilder-dialogs/src/memory/turnPath.ts
Reverts #3970
Fixes #3969
Fix: [commit](https://github.com/microsoft/botbuilder-js/commit/52d282246ff903f81fcf551c6a2082f0652c6a3d)
This PR fixes an issue where the bot wasn't able to respond to messages after the Welcome message is sent.
When the `AdaptiveDialog.beginDialog` method is executed, the `context.turnState` for the second message (`e.g.: help`) was the same as the first message (`WelcomeMessage`), thus, having the `activityProcessed` property set to `true`, the bot didn't process the new Activity and ended the Dialog right away.
- Revert PR #3970
- Updates the `LanguageGeneratorExtensions.useLanguagePolicy` method to set the correct LanguagePolicy like in DotNet ([link](https://github.com/microsoft/botbuilder-dotnet/blob/406d58042e49737b8738416d35bc7fbb47deccc9/libraries/Micros …
=> fix: [#3969] useLanguagePolicy setting turn state, instead of languagePolicy

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-connector/src/auth/connectorFactoryImpl.ts, libraries/botframework-connector/tests/botFrameworkAuthenticationFactory.test.js
=> fix: add accept header

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-connector/src/auth/connectorFactoryImpl.ts, libraries/botframework-connector/tests/botFrameworkAuthenticationFactory.test.js
fixes: #3962
* Add accept header to connectorclient outgoing calls
* Add accept header to connectorFactoryImpl connector client options
=> fix: cherry-pick to 4.15: add accept header (#3983)

testing/browser-functional/browser-tests-build-ci.yml, testing/browser-functional/nightwatch.conf.js, testing/browser-functional/package.json
Fixes #minor
Fixes pipeline error "Current browser version is 96.0.4664.45 This version of ChromeDriver only supports Chrome version 94"
This also required a 5 second delay put into nightwatch config to fix error "Timeout while trying to connect to Selenium Server".
Also updates vmImage.
Affected pipelines:
Run-JS-Functional-Tests-BrowserBot-yaml
Run-JS-Functional-Tests-Linux
=> fix: Update chromedriver to v 96

libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts
Fixes Issue [Incorrect check against Content-Type instead of content-type in httpRequest #3992](https://github.com/microsoft/botbuilder-js/issues/3992)
Fixes #3992
=> fix: Incorrect check against Content-Type instead of content-type in httpRequest #3992

build/code-analysis/credscan.json, libraries/botbuilder/tests/botFrameworkAdapter.test.js, libraries/botframework-config/tests/encryption.test.js
=> fix: Add CredScan suppression

libraries/botbuilder-dialogs/src/choices/findValues.ts, libraries/botbuilder-dialogs/tests/choices_recognizers.test.js
Fixes #4007
This PR ports the changes in [dotnet PR#4671](https://github.com/microsoft/botbuilder-dotnet/pull/4671) to add the _findExactMatch_ function in `botbuilder-dialogs/choices` to check for exact matches and bypass the tokenizer logic if an exact match is found.
- Updated `findValues` class to check for exact matches and bypass the rest of its logic if an exact match is found.
- Added a test to account for situations where multiple choices have the same word characters but different non-word characters.
These images show the star choice being ignored, and after the fix, being properly recognized.
=> fix: [#4007] Bot framework V4. Unable to use ⭐ emoji in suggested actions

build/yaml/botbuilder-js-daily.yml
#minor
Adding Component governance to the build to enable failure on error and deleting all package manager files before it is run.
- 
-
-
=> chore: adding component governance to build

build/yaml/botbuilder-js-daily.yml
#minor
Deleting node_modules after build to remove overhead of package manager dependencies and prevent Component Governance to report unused packages
- 
-
-
=> chore: Delete node modules after build

build/yaml/botbuilder-js-daily.yml
Fixes #minor
This changes the Component Detection scan area to include the yarn.lock file at the root. I believe those dependencies should be included in the Component Detection scanning process. 
Delete the sourceScanPath input line so scanning includes the yarn.lock file at the root.
Add ./generators to the ignoreDirectories list because that is currently scanned in the pipeline BotBuilder-Generators-JS-daily.
=> fix: Change component detection scan path to root

package.json, yarn.lock
Fixes #minor
Fixes the high severity mixme vulnerability listed in these CG alerts:
https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/112352/alert/5657655?typeId=10422422
https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/112352/alert/5657656?typeId=10422422
Vulnerability: mixme 0.3.5. Recommended to upgrade to v 0.5.2.
Force dependency mixme to version 0.5.2.
Add a resolutions section to the root package.json.
=> fix: mixme Component Governance vulnerability

package.json, yarn.lock
Fixes #minor
Fixes the high severity follow-redirects vulnerability listed in these 2 CG alerts:
https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/112352/alert/6373557?typeId=10422422
https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/112352/alert/6373574?typeId=10422422
Vulnerability: follow-redirects 1.5.10
-- Recommendation: Upgrade follow-redirects from 1.5.10 to 1.14.7
Vulnerability: follow-redirects 1.14.4
--  Recommendation: Upgrade follow-redirects from 1.14.4 to 1.14.7
The initial follow-redirects dependency tree looked like this:
```
C:\src\botbuilder-js>npm ls follow-redirects
botbuilder-js@4.13.0 C:\src\botbuilder-js
`-- @azure/ms-rest-js@1.9.1
`-- axios@0.21.4
`-- follow-redirects@1.14.4
```
I fixed it with the command:
`yarn upgrade …
=> fix: follow-redirects Component Governance vulnerability

libraries/botbuilder-ai/package.json, libraries/botbuilder/package.json, libraries/botframework-connector/package.json, yarn.lock
Fixes #minor
High severity vulnerability.
https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/112352/alert/4059014?typeId=10406766
https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/112352/alert/6373557?typeId=10406766
[Found in this JS daily build](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=289514&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=92ae5ab9-2fad-5d38-c077-2da744b5c79c&l=13073)
Upgrade @azure/cognitiveservices-luis-runtime@2.0.0 to latest version 5.0.0. 
Upgrade axios@0.21.4 to latest version 0.25.0.
=> fix: CG alerts for follow-redirects 1.5.10, axios 0.19.2

testing/botbuilder-test-utils/package.json, testing/browser-functional/browser-echo-bot/yarn.lock, testing/streaming-e2e/react-app/package-lock.json, tools/package.json, yarn.lock
Fixes #minor
- Bump **handlebars** from 4.7.6 to 4.7.7
- Bump **follow-redirects** from 1.14.7 to 1.14.9
- Bump **follow-redirects** from 1.14.7 to 1.14.9 in _/testing/streaming-e2e/react-app_
- Bump **follow-redirects** from 1.13.0 to 1.14.9 in _/testing/browser-functional/browser-echo-bot_
- Bump **vm2** from 3.9.5 to 3.9.8
- Bump **node-forge** from 0.10.0 to 1.0.0
- Bump **postcss** from 7.0.35 to 7.0.39 in _/testing/browser-functional/browser-echo-bot_
- Bump **url-parse** from 1.4.7 to 1.5.10 in _/testing/browser-functional/browser-echo-bot_
- Bump **pathval** from 1.1.0 to 1.1.1
- Bump **ua-parser-js** from 0.7.22 to 0.7.31 in _/testing/browser-functional/browser-echo-bot_
- Bump **ua-parser-js** from 0.7.22 to 0.7.31 in _testing/streaming-e2e/react-app_
- Bump …
=> chore: (deps) Bump dependencies

testing/browser-functional/nightwatch.conf.js, testing/browser-functional/package.json
Fixes #minor
error: [
'Current browser version is 98.0.4758.102 ... This version of ChromeDriver only supports Chrome version 96'
Failing run: https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=293897&view=logs&j=6b902995-b73d-5f5c-66fd-a7f66c857d2c&t=a1c457be-0fbe-5525-b6b0-ac3cf58f8d6c
The following changes address frequent timeout errors when nightwatch runs selenium tests:
Increase check_process_delay to 10 seconds.
Update nightwatch.
=> fix: failing pipeline Run-JS-Functional-Tests-BrowserBot-yaml

libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-core/src/testAdapter.ts, libraries/botbuilder-core/tests/testAdapter.test.js
TestAdapter throws unhalded promise rejections on errors
- The testadapter should handle errors
- For that, TestFlow must implement the thenable implementation correctly
- Implemented further the tenable on TestFlow to allow handling catch clauses correctly
A test is added to verify the behavior change (If you run that test on main before this PR is merged, it fails)
#minor
=> fix: [botbuilder-core] TestAdapter throws unhandled promise rejection on error

libraries/botbuilder-dialogs/etc/botbuilder-dialogs.api.md, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/tests/oauthPrompt.test.js
Fixes #3943
This PR ports the changes in [BotBuilder-DotNet's PR#5906](https://github.com/microsoft/botbuilder-dotnet/pull/5906) to add the **_showSignInLink_** property in **_OAuthPromp_** allowing the user to decide if a sign-in link should be shown or not.
- Updated `oauthPrompt.ts` to include the _showSignInLink_ property and the validation to set the sign-in link.
- Added unit tests in `oauthPrompt.test.js` to cover the different test cases.
- Updated `botbuilder-dialogs.api.md` to include the new property.
This image shows the new unit tests passing.
=> port: [#3943] Add ShowSignInLink to OAuthPromptSettings (#5906)

libraries/botbuilder-dialogs/src/choices/channel.ts, libraries/botbuilder-dialogs/tests/choices_channel.test.js
Fixes #4039
This PR ports the changes in [BotBuilder-DotNet's PR#6085](https://github.com/microsoft/botbuilder-dotnet/pull/6085) to add support for <= 50 Card Actions on teams.
- Updated `channel.ts` to support <= 50 Card Actions on teams.
- Added unit tests in `choices_channel.test.js` to cover the different test cases.
This image shows the new unit tests passing.
=> port: [#4039] Teams now supports <= 50 Card Actions (#6085)

libraries/botbuilder/src/cloudAdapter.ts
Fixes #4062
This PR ports the changes in [BotBuilder-DotNet's PR#6135](https://github.com/microsoft/botbuilder-dotnet/pull/6135) adding a warn logger in CloudAdapter's process method when the activity hasn't a type.
- Updated CloudAdapter class adding a `console.warn` when a BadRequest error is thrown for a missing activity type.
This image shows the tests passing after the change.
=> port: [#4062] Log BadRequest in adapter (#6135)

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
Fixes #3931
This PR adds `omnichannel` to the Channels enum in _botframework-schema_.
- Added `Omni` value to the Channels enum in _botframework-schema_.
- Updated `botframework-schema.api.md` to include the new channel value.
This image shows the schema tests passing after including the new channel.
=> port: [#3931] Add "omnichannel" to Channels (#5891)

libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts
Fixes #4137
This PR removes an outdated validation for token exchange that was causing the exchange between root and skill bots using CloudAdapter to fail.
This validation was already removed from .NET implementation in [this commit](https://github.com/microsoft/botbuilder-dotnet/commit/c000b4acfb4f236a33d0edb552a21770407c8c1e).
- Updated oauthPrompt' recognizeToken method removing validation for 'exchangeToken'.
Here we can see a root and a skill bot properly exchanging the token.
=> fix: [SSO] Remove 'exchangeToken' validation from OauthPrompt

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsInfo.ts
chore: Marked getMembers and getTeamMembers as deprecated.
Fixes #4140
Marked getMembers and getTeamMembers as deprecated.
=> chore: Deprecate getTeamMembers and getMembers.

libraries/botbuilder/src/teamsInfo.ts
Fixes #4144
#minor
This PR fixes an issue when calling the `TeamsInfo.sendMessageToTeamsChannel` method and reply to the new message thread, it replies to the first message sent to the bot instead of the new created one.
[DotNet's reference](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs#L309)
- Updated `TurnContext.getConversationReference` execution to get the `ConversationReference` from the `turnContext` instead of the original `context`.
The following images show the bot working as expected after the applied fix.
=> port: [#4144] TeamsInfo.sendMessageToTeamsChannel() doesn't return the correct ConversationReference

libraries/botbuilder-core/src/telemetryConstants.ts, libraries/botbuilder-core/src/telemetryLoggerMiddleware.ts, libraries/botbuilder-core/tests/telemetryMiddleware.test.js
Fixes #4092
This PR adds the `activityTypeProperty` into the `TelemetryConstants` class, also adds the missing documentation for the rest of the properties. Additionally, it adds the type property to the `TelemetryLoggerMiddleware` receive, update and delete events, and updates the unit tests.
- Adds the `activityTypeProperty` into the `TelemetryConstants` class.
- Adds the missing property comments in the `TelemetryConstants` class.
- Adds the property to the `TelemetryLoggerMiddleware` receive, update and delete events.
- Updates the unit tests to support the new property.
The following image shows the tests passing successfully.
=> port: [#4092] Add ActivityTypeProperty to TelemetryLoggerMiddleware

libraries/botbuilder-core/src/extendedUserTokenProvider.ts, libraries/botbuilder-core/src/userTokenProvider.ts, libraries/botbuilder-dialogs/src/dialogManager.ts, libraries/botbuilder/src/inspectionMiddleware.ts
Fixes #4060, #4061, #4108 
- Obsolete sidecar debugging classes
- Add Obsolete attribute to IExtendedUserTokenProvider and IUserTokenProvider
- Add Obsolete attribute to DialogManager
=> port: Obsolete classes for future deprecation

libraries/botbuilder-dialogs-adaptive/tests/activityFactory.test.js, libraries/botbuilder-lg/etc/botbuilder-lg.api.md, libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tests/lg.test.js
Fixes #3967 #3975
This PR ports the changes in [BotBuider-DotNet](https://github.com/microsoft/botbuilder-dotnet/pull/5943) to add the `enableFromFile` property in the _Templates_ class.
- Added `enableFromFile` property in the _Templates_ class.
- Added condition for _fromFile_ in _customizedEvaluatorLookup_ method of _Evaluator_ and _Expander_ classes. 
- Added unit test for the _FileOperationDisabled_ scenario.
This image shows the new tests passing.
=> port: [#3967] add control property (#5943)

libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-adaptive/src/actions/getActivityMembers.ts, libraries/botbuilder-dialogs-adaptive/src/actions/getConversationMembers.ts
Fixes #3922
This PR ports the changes in [BotBuider-DotNet](https://github.com/microsoft/botbuilder-dotnet/pull/5874)  to Corrected GetConversationMembers in Adaptive.Runtime to use TeamsInfo helper class rather than rely on BotFrameworkAdapter functions that aren't available now that CoreBotAdapter derives from CloudAdapter and not BotFrameworkAdapter.
- getActitivityMemebers.ts
- Remove BotFrameworkAdapter
- Create a private function, which gets the connector client and returns the accounts info
- getConversationsMemebers.ts
- Remove BotFrameworkAdapter
- Create a private function, which gets the connector client and returns the conversation's members info
These images show the unit tests passing after the changes.
=> port: [#3922] Corrected GetConversationMembers to use TeamsInfo helper class rather… (#5874)

libraries/botbuilder-ai-orchestrator/package.json, libraries/botbuilder-ai/package.json, libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-declarative/package.json
Fixes #4064
This PR moves redundant dependencies out of the `dependencies` section to the `peerDependencies` or `devDependencies` sections depending on the case.
> _**Note: If we remove the dependencies, although the build and the tests work, the `depcheck` command fails with the 'missing dependency' error.**_
- **botbuilder-ai-orchestrator**
- Moved _botbuilder-dialogs-declarative_ and _botbuilder-dialogs-adaptive-runtime-core_ under `peerDependencies` as they are included in _botbuilder-dialogs-adaptive_.
- Moved _adaptive-expressions_, _botbuilder-core_, and _botbuilder-dialogs_ under `devDependencies` as they are required by the tests.
- **botbuilder-ai**
- Moved _adaptive-expressions_, _botbuilder-core_, and _botbuilder-dialogs_ under `devDependencies` as they are required by the …
=> port: [#4064][#6019] Remove redundant project dependencies from AI Recognizers (#6067)

libraries/botbuilder-lg/etc/botbuilder-lg.api.md, libraries/botbuilder-lg/src/analyzer.ts, libraries/botbuilder-lg/src/analyzerOptions.ts, libraries/botbuilder-lg/src/index.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/tests/lgDiagnostic.test.js, libraries/botbuilder-lg/tests/testData/exceptionExamples/LoopDetected.lg
Fixes #3917
This PR ports the changes in [BotBuilder-DotNet's PR#5872](https://github.com/microsoft/botbuilder-dotnet/pull/5872) so the analyzeTemplate method throws an error with loop detected message.
- Updated `analyzer` class to include the _analyzerOptions_ in its constructor and in the _analyzeTemplate_ method.
- Added new `analyzerOptions`class.
- Included the new class in the `index` export list.
- Updated `templates` class to include the _analyzerOptions_ in the _analyzeTemplate_ method.
- Added new asserts in the `TestLoopDetected` test.
- Updated `botbuilder-lg.api.md` documentation with the changes in the API.
This image shows the TestLoopDetected passing with the new asserts.
=> port: [#3917] Add ThrowOnRecursive to LG AnalyzerOptions (#5872)

yarn.lock
Fixes #3889 
Security violations from package `is-generator-function` are fixed in version @1.0.10:  https://github.com/inspect-js/is-generator-function/commit/bce7ca64ae45c8453e6406abf480e55a90100aa0
This change updates the versions of `is-generator-function` and `node-util` to include security fixes. It does not change the version of `browserify`.
=> fix: Update node-util and is-generator-function dependencies to eliminate security violation

libraries/adaptive-expressions-ie11/LICENSE, libraries/adaptive-expressions/LICENSE, libraries/botbuilder-ai-luis/LICENSE, libraries/botbuilder-ai-orchestrator/LICENSE, libraries/botbuilder-ai-qna/LICENSE, libraries/botbuilder-ai/LICENSE, libraries/botbuilder-applicationinsights/LICENSE, libraries/botbuilder-azure-blobs/LICENSE, libraries/botbuilder-azure-queues/LICENSE, libraries/botbuilder-azure/LICENSE, libraries/botbuilder-core/LICENSE, libraries/botbuilder-dialogs-adaptive-runtime-core/LICENSE, libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/LICENSE, libraries/botbuilder-dialogs-adaptive-runtime-integration-express/LICENSE, libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/LICENSE, libraries/botbuilder-dialogs-adaptive-runtime/LICENSE, libraries/botbuilder-dialogs-adaptive-testing/LICENSE, libraries/botbuilder-dialogs-adaptive/LICENSE, libraries/botbuilder-dialogs-declarative/LICENSE, libraries/botbuilder-dialogs/LICENSE, libraries/botbuilder-lg/LICENSE, libraries/botbuilder-repo-utils/LICENSE, libraries/botbuilder-stdlib/LICENSE, libraries/botbuilder-testing/LICENSE, libraries/botbuilder/LICENSE, libraries/botframework-config/LICENSE, libraries/botframework-connector/LICENSE, libraries/botframework-schema/LICENSE, libraries/botframework-streaming/LICENSE
Fixes #3192
This PR adds the `LICENSE` file to all the packages under the `libraries` folder.
- Added the `LICENSE` from the root project to each package under the `libraries` folder.
=> fix: [#3192] Missing LICENSE files and invalid package.json - Part 2

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/botFrameworkHttpAdapter.ts, libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botbuilder/src/channelServiceHandler.ts, libraries/botbuilder/src/skills/skillHandler.ts, libraries/botframework-connector/src/auth/channelValidation.ts, libraries/botframework-connector/src/auth/credentialProvider.ts, libraries/botframework-connector/src/auth/emulatorValidation.ts, libraries/botframework-connector/src/auth/enterpriseChannelValidation.ts, libraries/botframework-connector/src/auth/governmentChannelValidation.ts, libraries/botframework-connector/src/auth/jwtTokenValidation.ts, libraries/botframework-connector/src/auth/skillValidation.ts
Fixes #4044
This PR adds the `@deprecated` attribute to BotFrameworkHttpAdapter and related classes, in order to migrate to CloudAdapter.
[BotBuilder-DotNet's PR#6096](https://github.com/microsoft/botbuilder-dotnet/pull/ 6096) was taken as a base.
- Added the `@deprecated` attribute to the following classes:
- botFrameworkAdapter
- botFrameworkAdapterSettings
- botFrameworkHttpAdapter
- botFrameworkHttpClient
- channelServiceHandler
- skillHandler
- channelValidation
- SimplecredentialProvider
- ICredentialProvider
- emulatorValidation
- enterpriseChannelValidation
- governmentChannelValidation
- jwtTokenValidation
- skillValidation
- Updated botbuilder.api.md documentation
This image shows the build passing after the changes.
=> port: [#4044] Add obsolete attribute to BotFrameworkHttpAdapter and related classes. (#6096)

libraries/botbuilder/src/teamsActivityHelpers.ts, libraries/botbuilder/tests/teamsHelpers.test.js
Fixes #4073
This PR updates the `alert` property for the `teamsNotifyUser` method notification, to depend on the `alertInMeeting` property. Additionally, it updates the unit tests to support these changes.
- Updates `alertInMeeting` property default value to be false instead of undefined, when the parameter is not passed in.
- Updates the `alert` property notification to be the opposite value of the `alertInMeeting` property.
- Updates the unit tests to include the conditions of `alertInMeeting` and `alert` properties. Additionally, it updates the naming for some unit tests, to differ from the rest.
The following image shows the tests passing successfully.
=> port: [#4073] Set TeamsNotifyUser Alert to opposite of AlertInMeeting

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHelpers.ts
Fixes #4154
This PR updates the `teamsNotifyUser` method in teamsActivityHelper class to receive a Partial<Activity> instead of an Activity enabling to call it using a MessageFactory.
This method only uses the Activity's ChannelData which is not a required property.
- Updated `teamsNotifyUser` method to receive a Partial<Activity> as parameter.
- Updated the method signature in `botbuilder.api.md` documentation.
These images show a Teams bot sending a notification to the user.
=> fix: [#4154] teamsNotifyUser does not accept messages returned from MessageFactory

libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-core/src/activityHandler.ts, libraries/botbuilder-core/tests/ActivityHandler.test.js, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
=> fix: Add search invoke

libraries/botbuilder-dialogs-adaptive/etc/botbuilder-dialogs-adaptive.api.md, libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts, libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts, libraries/botbuilder-dialogs-adaptive/tests/choiceInputDialog.test.js, libraries/botbuilder-dialogs-adaptive/tests/inputDialog.test.js
Fixes #4163 
This pull request fixes a bug for the multi-choice options not getting logged in application insights.
=> port: [#4163] log multi-choice options in App Insights

libraries/botbuilder-ai/package.json
Fixes #4179
4 E2E test pipelines are failing. A sample error:
```
npm ERR! path D:\a\1\s\samples\typescript_nodejs\13.core-bot
node_modules/botbuilder-ai/lib/luisAdaptivePredictionOptions.d.ts(8,79): error TS2307: Cannot find module 'adaptive-expressions' or its corresponding type declarations.
```
This was a regression from this PR: https://github.com/microsoft/botbuilder-js/pull/4152
Move the "adaptive-expressions" reference in libraries/botbuilder-ai/package.json from devDependencies to dependencies.
Running against the packages with the fix, the 4 failing test pipelines passed:
- https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=298474&view=results
- https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=298472&view=results
- …
=> fix: failing Samples E2E JS CoreBot tests

libraries/botbuilder-ai/package.json
#minor
Cherry pick to fix missing dependency in ai.
=> fix: Move "adaptive-expressions" to dependencies (#4178)

libraries/botbuilder-repo-utils/src/package.ts, libraries/botbuilder-repo-utils/src/updateVersions.ts
Addresses #3192
#minor
This PR modifies the `update-versions` script, to take the private packages into account when updating all the libraries versions and references and also the `peerDependencies`.
- Updated `update-versions` script to gather all the repo packages and update the version for the ones that aren't private.
- Updated `update-versions` script to take the `peerDependencies` into consideration.
=> fix: [#3192] Missing LICENSE files and invalid package.json - Part 1

libraries/botbuilder-azure-blobs/etc/botbuilder-azure-blobs.api.md, libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts, libraries/botbuilder-azure-blobs/src/sanitizeBlobKey.ts, libraries/botbuilder-azure-blobs/tests/blobsTranscriptStore.test.js, libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
Fixes #4176 
Expecting Azure blob to creat transcript activity and follow the pattern of `container/{channelId]/{conversationId}/{Timestamp.ticks}-{activity.id}.json`
instead it was creating directory `container%2F{channelId}%2F{conversationId}%2F{Timestamp.ticks}-{activid.id}.json` due to [sanitizeBlobKey ](https://github.com/microsoft/botbuilder-js/blob/c5de4422f37793e6080949974368e3a41846a7a6/libraries/botbuilder-azure-blobs/src/sanitizeBlobKey.ts#L11)method using the [encodeURIComponent ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)function.
- Created optional `decodeTranscriptKey` boolean property in [`BlobsTranscriptStoreOptions`](https://github.com/microsoft/botbuilder-js/blob/ramfattah/blobTranscript/libraries/botbuilder-azure …
=> fix: Azure Blob transcript key 

testing/streaming-e2e/build/create-react-app.yml, testing/streaming-e2e/react-app/package.json
Fixes #minor
Pipeline [E2E_BF-Streaming-DL-ASE_Test](https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=1018&_a=summary) is failing in task Component Detection with 1 Malware alert(s) rated at 'Critical’ severity. Malicious component found: es5-ext 0.10.60
```
npm ls es5-ext
react-app@0.1.0 C:\src\botbuilder-js\testing\streaming-e2e\react-app
`-- react-scripts@4.0.3
`-- resolve-url-loader@3.1.4
`-- es6-iterator@2.0.3
+-- d@1.0.1
| `-- es5-ext@0.10.60  deduped
`-- es5-ext@0.10.60
```
I tried updating react-scripts to v 5.0.1, but that broke the build at step Build React App with "Can't resolve 'stream'".
Override "es5-ext" downgrading it to "0.10.53". (0.10.60 is the latest version.)
This fix resolves the es5-ext 0.10.60 critical alert and stops the build from failing.
Add Component …
=> fix: Critical alert for es5-ext 0.10.60

testing/functional/functionaltestbot/template/linux/template.json, testing/testbot/template/linux/template.json
Fixes #minor
This fixes the bot SKU format as was done for Samples in this PR: https://github.com/microsoft/BotBuilder-Samples/pull/3732
Pipeline Run-JS-Functional-Tests-Linux is failling.
=> fix: sku for Microsoft.BotService/botServices in 2 ARM templates

package.json, yarn.lock
Fixes #4188
This fixes the high severity Component Governance alerts for async. [Example alert](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/112352/alert/6862405?typeId=11638130).
The alerts recommend "Upgrade async...to 3.2.2 to fix the vulnerability." V 3.2.3 is now the latest, so using that one.
The parent dependency, adal-node 0.2.3, has no updates available. And migrating to its replacement, ADAL for Node.js, requires code rewrites. So I have tried here forcing the async dependency to a safe version. The adal-node dependency tree:
```
botframework-connector@4.1.6 C:\src\botbuilder-js\libraries\botframework-connector
`-- adal-node@0.2.3
`-- async@2.6.3
```
Add "async": "3.2.3" to the "resolutions" section of package.json file. Yarn picks that up and forces all …
=> fix: Force dependencies on async to v 3.2.3 - main branch

libraries/botbuilder-ai/src/qnaMaker.ts, libraries/botbuilder-ai/src/qnaMakerDialog.ts, libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts, libraries/botbuilder-ai/tests/qnaMaker.test.js
Fixes #4207
Fixes #4205
1) Card is formed for every response and check for answerSpan is removed from checkForMultiTurnPrompt in qnamakerDialog to maintain parity with C#.
2) Sorting and filtering of the answers is removed from generateAnswerUtils
Updated QnAMaker tests.
=> fix: Botbuilder-ai bugs

libraries/botbuilder-ai/src/qnamaker-utils/languageServiceUtils.ts
Fixes #4242
QnAId passed in the payload body for the correct functioning of multi-turn prompts.
In the source code in botbuilder-ai, languageServiceUtils.ts, function queryKnowledgebaseRaw, the code does not pass properly queryOptions.qnaId to the custom question answering REST call. This gives wrong behavior when using prompts in the knowledge base.
=> fix: Pass qnaId in payload body.

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
Fixes #4245
This PR marks the unsupported channels as deprecated and adds the new channel Outlook.
Unsupported channels:
- Kik
- SkypeForBusiness
- Twilio-sms
New supported channels:
- Outlook
- Unsupported channels are marked as deprecated in BotFramework-schema.
This screenshot shows the unit tests passing
=> port: [#4245] Mark deprecated channels as obsolete in Channels enum

generators/generator-botbuilder/generators/app/templates/core/package-with-tests.json.ts, generators/generator-botbuilder/generators/app/templates/core/package.json.ts, generators/generator-botbuilder/generators/app/templates/echo/package.json.ts, generators/generator-botbuilder/generators/app/templates/empty/package.json.ts
Fixes #4251 
Updates the TypeScript version of the generators for empty, echo, and core bot templates to the earliest supported version, `4.0.7`, to resolve the bug.
- Update TS version `package.json.ts` and `package-with-tests.json.ts` in core bot template from `3.9.2` to `4.0.7`.
- Update TS version `package.json.ts` in echo  bot template from `3.9.2` to `4.0.7`.
- Update TS version `package.json.ts` in empty bot template from `3.9.2` to `4.0.7`.
`npm install` fails on version `3.9.2`. Updating the version and rerunning the install results in a success and the bot then runs.
=> fix: Update TypeScript Version in Yeoman Templates to 4.0.7

testing/browser-functional/browser-tests-build-ci.yml
Fixes #minor
This fixes [Run-JS-Functional-Tests-BrowserBot-yaml/20220602.3](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=307061&view=results), broken because chromedriver is out of date. New Chrome browser releases break this pipeline about every 4 weeks.
This lets the pipeline automatically keep up with Chrome browser releases.
Add update script to pipeline
=> fix: Keep chromedriver up to date

testing/browser-functional/browser-tests-build-ci.yml
Fixes #minor
#4256 containing broken PowerShell@2 tasks was merged. This fixes the yaml.
=> fix:  Broken yaml for Run-JS-Functional-Tests-BrowserBot-yaml

libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/create_an_object.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/delete_an_object.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/does_not_throw_when_deleting_an_unknown_object.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/handle_crazy_keys.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/is_aware_of_nesting_limit.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/is_aware_of_nesting_limit_with_dialogs.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/passes_cosmosClientOptions_with_default_userAgentSuffix.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/performs_batch_operations.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/proceeds_through_a_waterfall_dialog.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/return_empty_object_when_reading_unknown_key.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/support_using_multiple_containers.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/support_using_multiple_databases.json, libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests/update_an_object.json, libraries/botbuilder-azure/tests/cosmosDbPartitionedStorage.test.js
Fixes #4233
This PR updates the `cosmosDbPartitionedStorage` class to set the package name and version in the UserAgent header for calls to CosmosDb.
It also adds a unit test to cover the changes made.
- Set the name and version from the package.json in the _userAgentSuffix_ property of _cosmosClientOptions_.
- Added a unit test that verifies the new value is correctly appended to the User-Agent header.
- Updated the Nock recordings in `tests/TestData/CosmosDbPartitionedStorage - Base Storage Tests` as the container ids have been incremented by the new test.
This image shows the new test successfully executed.
=> port: [#4233] Add ApplicationName to CosmosDb client options for UserAgent (#6321)

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHandler.ts
Fixes #4259
Invoke activity with the name `adaptiveCard/action` is supported in [ActivityHandler](https://github.com/microsoft/botbuilder-js/blob/e7d845eeacb32824af93652d07e46aabf30e800e/libraries/botbuilder-core/src/activityHandler.ts#L508) class, the method [`handleAdaptiveCardAction`](https://github.com/microsoft/botbuilder-js/blob/e7d845eeacb32824af93652d07e46aabf30e800e/libraries/botbuilder/src/teamsActivityHandler.ts#L523) is not needed in [teamsActivityHandler](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts) class.
- Removed unused method `handleAdaptiveCardAction` in [teamsActivityHandler](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts) class.
=> fix: Removed unused method in teamsActivityHandler

libraries/botbuilder-core/package.json, libraries/botbuilder-core/tests/ActivityHandler.test.js, libraries/botbuilder-core/tests/activityHandlerBase.test.js, libraries/botbuilder-core/tests/autoSaveStateMiddleware.test.js, libraries/botbuilder-core/tests/botAdapter.test.js, libraries/botbuilder-core/tests/botState.test.js, libraries/botbuilder-core/tests/botStatePropertyAccessor.test.js, libraries/botbuilder-core/tests/botStateSet.test.js, libraries/botbuilder-core/tests/cardFactory.test.js, libraries/botbuilder-core/tests/conversationState.test.js, libraries/botbuilder-core/tests/getTopScoringIntent.test.js, libraries/botbuilder-core/tests/memoryStorage.test.js, libraries/botbuilder-core/tests/mention.test.js, libraries/botbuilder-core/tests/messageFactory.test.js, libraries/botbuilder-core/tests/middlewareSet.test.js, libraries/botbuilder-core/tests/privateConversationState.test.js, libraries/botbuilder-core/tests/showTypingMiddleware.test.js, libraries/botbuilder-core/tests/storageBaseTests.js, libraries/botbuilder-core/tests/stringUtils.test.js, libraries/botbuilder-core/tests/telemetryMiddleware.test.js, libraries/botbuilder-core/tests/testAdapter.test.js, libraries/botbuilder-core/tests/transcriptMiddleware.test.js, libraries/botbuilder-core/tests/transcriptStoreBaseTest.js, libraries/botbuilder-core/tests/transcriptUtilities.js, libraries/botbuilder-core/tests/turnContext.test.js, libraries/botbuilder-core/tests/userState.test.js
Addresses #4204
#minor
This PR fixes the ESLint and JSDoc issues in the `botbuilder-core` library.
**_Note: we excluded the @typescript-eslint/no-explicit-any and @typescript-eslint/explicit-module-boundary-types to tackle those issues as a separate task as they require deeper analysis and testing._**
- Applied auto-fixes with `yarn lint --fix`
- Fix spacing.
- Fix indentation.
- Fix quoting.
- Replace arrow functions:   () => with function ().
- Replace let with const. 
- Applied manual fixes for: 
- Unused parameters and imports.
- Replacing _hasOwnProperty_ calls.
- Removing unused test class BotStateMock in _botStateSet.test.js_.
- Removed unused `lodash` devDependency.
Here we can see the eslint status before and after.
=> fix: [#4204] Fix remaining eslint warnings - botbuilder-core (2/2)

testing/browser-functional/browser-tests-build-ci.yml, testing/browser-functional/package.json
Fixes #minor
JS-Functional-Tests-BrowserBot-yaml started failing when a new chromedriver version was released, because the driver version is now ahead of the Chrome browser version.
My tests indicate auto updating to the second latest driver version will keep driver and browser versions in better sync.
Tweak "Upgrade chromedriver reference" step to use the 2nd latest version.
=> fix: chromedriver version updater

libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs-adaptive/src/actions/baseInvokeDialog.ts, libraries/botbuilder-dialogs-adaptive/src/entityAssignmentComparer.ts, libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts, libraries/botbuilder-dialogs-adaptive/src/recognizers/valueRecognizer.ts
Addresses #4204
#minor
This PR fixes the ESLint and JSDoc issues in the `botbuilder-dialogs-adaptive` library.
**_Note: we excluded the @typescript-eslint/no-explicit-any and @typescript-eslint/explicit-module-boundary-types to tackle those issues as a separate task as they require deeper analysis and testing._**
- Applied auto-fixes with `yarn lint --fix`
- Fix spacing.
- Applied manual fixes for: 
- Missing documentation.
- Moved devDependencies to the Dependencies section.
Here we can see the eslint status before and after.
=> fix: [#4204] Fix remaining eslint warnings - botbuilder-dialogs-adaptive

libraries/botbuilder-ai/etc/botbuilder-ai.api.md, libraries/botbuilder-ai/package.json, libraries/botbuilder-ai/src/customQuestionAnswering.ts, libraries/botbuilder-ai/src/luisAdaptivePredictionOptions.ts, libraries/botbuilder-ai/src/luisAdaptiveRecognizer.ts, libraries/botbuilder-ai/src/luisBotComponent.ts, libraries/botbuilder-ai/src/luisComponentRegistration.ts, libraries/botbuilder-ai/src/luisRecognizer.ts, libraries/botbuilder-ai/src/qnaMaker.ts, libraries/botbuilder-ai/src/qnaMakerBotComponent.ts, libraries/botbuilder-ai/src/qnaMakerComponentRegistration.ts, libraries/botbuilder-ai/src/qnaMakerDialog.ts, libraries/botbuilder-ai/src/qnaMakerRecognizer.ts, libraries/botbuilder-ai/src/qnamaker-utils/bindToActivity.ts
Addresses #4204
#minor
This PR fixes the ESLint and JSDoc issues in the botbuilder-ai library.
- Applied manual fixes for:
- Missing documentation.
- Import dependences
_Eslint and tests status_
=> fix: [#4204] Fix remaining eslint warnings - botbuilder-ai

libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/coreBot.ts, libraries/botbuilder-dialogs-adaptive-runtime/src/coreBotAdapter.ts
Addresses #4204
#minor
This PR fixes the ESLint and JSDoc issues in the botbuilder-dialogs-adaptive-runtime library.
- Applied auto-fixes with yarn lint --fix
- Fix spacing
- Fix indentation
- Add blank line in between comments
- Applied manual fixes for:
- Missing documentation
_Library eslint status_
_Library tests status_
=> fix: [#4204] Fix remaining eslint warnings - Rest of botbuilder-dialogs libraries - adaptive runtime

libraries/botbuilder-dialogs-adaptive-testing/package.json, libraries/botbuilder-dialogs-adaptive-testing/tests/crossTrainedRecognizerSet.test.js, libraries/botbuilder-dialogs-adaptive/src/recognizers/crossTrainedRecognizerSet.ts, libraries/botbuilder-dialogs/src/recognizer.ts
Fixes #4261
This PR ports the changes from [PR#6348](https://github.com/microsoft/botbuilder-dotnet/pull/6348) to include the sentiment properties into the RecognizerResult when the None intent is triggered.
- Added sentiment properties for None intents in:
- botbuilder-dialogs-adaptive/recognizers/crossTrainedRecognizerSet.ts
- botbuilder-dialogs/recognizer.ts
- Added unit tests in `crossTrainedRecognizerSet.test.js` to cover the new code.
- Added `botbuilder` as _dev-dependency_ for the new tests.
These images show the bot trace with the sentiment block and the new tests passing.
=> port: [#5837] Fix sentiment values not being set for None / Unknown intent (#6348)

libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_ChoicesWithChoiceOptions.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_ChoicesWithChoiceOptionsTemplate.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_ConfirmInputWithChoiceOptions.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_ConfirmInputWithChoiceOptionsTemplate.test.dialog, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/test.en.lg, libraries/botbuilder-dialogs-adaptive/etc/botbuilder-dialogs-adaptive.api.md, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.ChoiceInput.schema, libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.ConfirmInput.schema, libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts, libraries/botbuilder-dialogs-adaptive/src/input/choiceOptionsSet.ts, libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts, libraries/botbuilder-dialogs-adaptive/src/input/index.ts, libraries/botbuilder-dialogs-adaptive/tests/choiceOptionsSet.test.js, libraries/tests.schema
Fixes #4270
This PR updates the ChoiceOptions to support LG allowing to define different template expressions for each language.
It also adds unit tests to cover the new code.
- Updated `ConfirmInput` and `ChoiceInput` to get the choice options from an expression.
- Added the new class `ChoiceOptionsSet` containing the `bind` method to map the LG expression into a `ChoiceFactoryOptions` object.
- Updated `ChoiceInput` and `ConfirmInput` schemas.
- Added new tests in `ActionTests` class:
- Action_ChoicesWithChoiceOptions.test.dialog 
- Action_ChoicesWithChoiceOptionsTemplate.test.dialog 
- Action_ConfirmInputWithChoiceOptions.test.dialog
- Action_ConfirmInputWithChoiceOptionsTemplate.test.dialog
- Added new test file `choiceOptionsSet.test.js` containing all the tests related to the …
=> port: [#4270] Choice options separator should be multi language (#6366)

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHelpers.ts, libraries/botbuilder/tests/teamsHelpers.test.js, libraries/botbuilder/tests/teamsInfo.test.js, libraries/botframework-connector/src/teams/models/mappers.ts, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts
Fixes #4274
This PR adds the ability to gather the selected MS Team's channel id when available in the incoming Activity. (Available in Install and Uninstall the teams' bot events).
- Added the `teamsGetSelectedChannelId` helper function.
- Added the `TeamsChannelDataSettings` interface and all its related properties to be accessible from the Activity.
- Added unit tests around this implementation.
- Updated mappers to include the new added properties.
- Updated compatibility Markdown document.
The following images show the tests passing successfully and the selected channel id being gathered successfully from a teams' bot.
=> port: [#4274] Add settings.selectedChannel to TeamsChannelData and Type to ChannelInfo and TeamDetails (#6360)

libraries/botbuilder-azure/package.json
Fixes #4300
botbuilder-azure v4.16.0 depends on azure-storage v2.10.2 which has a dependency on validator v9.4.1
validator.js prior to 13.7.0 is vulnerable to "Inefficient Regular Expression Complexity"
More details: https://github.com/advisories/GHSA-qgmg-gppg-76g5
The ask is to bump up the version of azure-storage to v2.10.7 which depends on validator v13.7.0
- Updated the version number of azure-storage to 2.10.7 in package.json
=> fix: Update package.json

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js, libraries/botframework-connector/src/teams/index.ts, libraries/botframework-connector/src/teams/readReceiptInfo.ts, libraries/botframework-connector/tests/teams/readReceiptInfo.test.js
Fixes #4276
This PR ports the changes in [PR#6356](https://github.com/microsoft/botbuilder-dotnet/pull/6356) adding support for the Teams read receipt event.
- Added `onTeamsReadReceiptEvent` handler method in the **_teamsActivityHandler_** class.
- Added the new `ReadReceiptInfo` class in **_botframework-connector/teams_**.
- Added unit tests for the new class and methods.
- Updated `botbuilder.api.md` with the new method.
These images show the new unit tests passing.
=> port: [#4276] Add Teams read receipt event (#6356)

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts
Fixes #4296
This PR adds the '_silentAuth_' value to the **_MessagingExtensionResultType_**'s enum.
_Note: In .NET the type for MessagingExtensionResult is a string._ 
- Updated `MessagingExtensionResultType` in _botframework-schema/teams/index.ts_ to include the new value '_silentAuth_'.
- Updated documentation in `botframework-schema.api.md`.
These images show the error shown when using '_silentAuth_' as the type and the type being correctly assigned after the changes.
=> fix: [#4296] MessagingExtensionResultType missing silentAuth Type

libraries/botbuilder-ai/src/qnamaker-utils/languageServiceUtils.ts, libraries/botbuilder-ai/tests/TestData/LanguageService/returns_answer_with_metadata.json, libraries/botbuilder-ai/tests/languageService.test.js
Fixes #4288
This PR fixes the formatting made over the answer's _metadata_, causing the information to get lost. The _metadata_ field was treated as an array and it is actually an object.
- Updated the _formatQnaResult_ method of the `languageServiceUtils` class to format the _metadata_ field treating it as an object.
- Added a new unit test in the `languageService.test` class to verify the metadata field gets properly mapped.
- Added `returns_answer_with_metadata.json` test data file.
These images show the answer the bot received before and after the changes.
=> fix: [#4288] CustomQuestionAnswering answers return empty metadata

libraries/adaptive-expressions/src/builtinFunctions/bool.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #4309
This PR ports the changes in botbuilder-dotnet to evaluate 'true' and 'false' strings.
- Updated _func()_ method of AdaptiveExpressions/BuiltinFunctions/bool to evaluate 'false' string
- Updated AdaptiveExpressions/Tests/expressionParser.test.js
This image shows the unit tests passing.
=> port: [#4309] AdaptiveExpression Bool function is not very useful because it doesn't convert anything but ints (#6431)

libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs-adaptive/src/recognizers/regexRecognizer.ts, libraries/botbuilder-dialogs-adaptive/tests/adaptiveDialog.test.js
Fixes #4308
This PR ports the changes in [PR#6435](https://github.com/microsoft/botbuilder-dotnet/pull/6435) updating the AdaptiveDialog's _onRecognize_ method to take into consideration the priority set for the intents when there is more than one result with the same score.
- Updated the _onRecognize_ method to choose the topIntent considering both score and priority.
- Removed the break from the _recognize_ method to return all the intents that match the pattern.
- Added a unit test to cover the priority scenario in _adaptiveDialog.test_.
These images show the bot not recognizing the correct intent before and the bot returning the right intent according to its priority after the changes.
=> port: [#6434] Priority broken for RegexRecognizer (#6435)

libraries/botbuilder-core/src/cloudAdapterBase.ts
Fixes #4314
This PR fixes an issue where multiple message activities were sent in different orders using WebChat or Emulator.
The problem was in the [sendActivities](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-core/src/cloudAdapterBase.ts#L71) method, where the activities were processed in parallel, and thus sent in different order.
To solve this issue, we basically ported the functionality changes from [DotNet's SendActivities](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs#L69) implementation.
- Replaced promise loop from `map` to `for of`, so activities are processed sequentially and not in parallel.
- Ported changes from [DotNet's SendActivities](https://github.com/microsoft/botbuilder-dotnet/bl …
=> fix: [#4314] CloudAdapter: messages are not sorted correctly

libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-core/src/botState.ts, libraries/botbuilder-core/tests/botState.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
Fixes #4325
This PR fixes an issue where the Host calls a Skill using the `BeginSkill` action, and right after ending the conversation with the skill a `TextInput` is prompt.
Moreover, after the input was prompted and provided the text response, the Host fails, because it tries to call the Skill again.
Furthermore, the Host was trying to call the Skill because the `ConversationState` was being updated with old information due to the `BeginSkill` class was saving into the Storage the `ConversationIdFactory` and `ConversationState` instances (that also have a `Storage`).
By skipping the two properties, [like DotNet does](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/SkillDialogOptions.cs#L57-L67), solved the issue.
- Added a functionality …
=> fix: [#4325] Skip Storage properties from BotState class

build/yaml/botbuilder-js-daily.yml
Fixes #minor
ubuntu-18.04 is deprecated. This sets it to latest for the daily build.
=> chore: Update Ubuntu vmImage version

build/yaml/botbuilder-js-daily.yml, testing/browser-functional/browser-tests-build-ci.yml
Fixes #minor
In pipeline JS-Functional-Tests-BrowserBot-yaml, task 'Get second latest chromedriver version number from npmjs.com' is not getting the correct version. This fixes that.
=> fix: get chrome version task in browser test pipeline

libraries/botbuilder/src/botFrameworkAdapter.ts
Fixes #4332 
Fixing a very small typo from `req` to `res` to denote the correct `Response` object in the process method
- Change `req` to `res`
=> fix: change req to res in process method

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/channelServiceHandlerBase.ts, libraries/botbuilder/src/channelServiceRoutes.ts, libraries/botbuilder/src/skills/cloudSkillHandler.ts, libraries/botbuilder/src/skills/skillHandlerImpl.ts, libraries/botbuilder/tests/skills/cloudSkillHandler.test.js
Fixes #4317
This PR ports the changes in [PR#6443](https://github.com/microsoft/botbuilder-dotnet/pull/6443) to fix the error thrown when executing the _TeamsInfo.GetMember_ in a root-skill scenario.
- Added the _handleGetConversationMember_ and _onGetConversationMember_ methods in `ChannelServiceHandlerBase`.
- Added the _processGetConversationMember_ method in `channelServiceRoutes`.
- Added the _onGetConversationMember_ method in the `CloudSkillHandler` class.
- Added the implementation of the _onGetMember_ method in the `SkillHandlerImpl` class.
- Added the `cloudSkillHandler.test.js` file with unit test for _CloudSkillHandler_ constructor and _onGetConversationMember_ methods.
These images show the skill bot retrieving the member's information successfully and the new unit test …
=> port: [#6432] TeamsInfo.GetMemberAsync(...) doesn't work properly in Skill Bot scenario, it returns http 405 error (#6443)

libraries/adaptive-expressions/src/builtinFunctions/isMatch.ts, libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes #4310
This PR ports the changes in [PR#6426](https://github.com/microsoft/botbuilder-dotnet/pull/6426) to fix the error in the **_isMatch_** built-in function when the value is null or an empty string.
- Updated the `IsMatch` built-in function to handle empty strings and null values by the evaluator.
- Added 2 new unit tests for empty string and null values for the _IsMatch_ function.
Here we can see the new unit tests passing after the changes.
=> port: [#6354] isMatch adaptive expression returns error when value is null or empty string (#6426)

libraries/botbuilder-ai-orchestrator/package.json, yarn.lock
Fixes #minor
Update the orchestrator-core dependency to the new version 4.14.4. That version has the minimist 1.2.5 vulnerability fixed.
=> chore: Fix the CG security vulnerability from minimist v 1.2.5

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js
=> feat: Add new handler for anonymous query link invoke

build/AnalyzeDependencies/InterdependencyGraph.html
Fixes #4341
This PR fixes de CodeQL SM01507 alert related to open redirects by implementing a fixed domain for the script's _src_ param.
- Updated `build/AnalyzeDeps/InterdependencyGraph.html` to append the domain URL to the _data_ param.
We tested the changes locally rendering the HTML with and without the _data_ query parameter.
=> fix: CodeQL alert SM01507: Client-side URL redirect

libraries/botbuilder-azure/package.json, libraries/botbuilder-azure/src/cosmosDbKeyEscape.ts
Fixes #4335
#minor
This PR fixes the SM01511 alerts which were related to the use of password hash with insufficient computational effort in microsoft/microsoft/botbuilder-js/botbuilder-js.
To fix it, we replaced the current password hashing scheme crypto with [bcrypt](https://github.com/kelektiv/node.bcrypt.js).
- Replace the current crypto library with bcrypt in botbuilder-azure/src/cosmosDbKeyEscape.ts.
=> fix: [CodeQL] SM01511 - Improve password hash security

libraries/botbuilder-dialogs-adaptive-testing/src/httpRequestMocks/httpRequestSequenceMock.ts, libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/testData/examples/Expand.lg, tools/scripts/unit-arm.js, tools/scripts/unit-coverage.js, tools/scripts/unit.js
Fixes #4336, #4337, #4338, #4339, #4340
This PR fixes the SM02383 alerts which are related to incomplete string escaping or encoding.
To correct them, we replaced the _replace_ method with _replaceAll_ (where it was allowed). In case it wasn't allowed, we fixed the issue by updating the regex related and using methods like _split_ and _join_ instead of _replace_.
- Replace method replaced by split and join ones in _botbuilder-dialogs-adaptive-testing_
- Updated regex in _botbuilder-lg_ to escape `"` and `\\`
- New unit test case for _botbuilder-lg_
- Use _endsWith_ and _slice_ methods to trim trailing \r instead of use replace in _scripts_
This image shows the new unit test for the _botbuilder-lg_ library.
=> fix: [CodeQL] SM02383 alerts: incomplete string escaping or encoding

build/yaml/botbuilder-js-daily.yml, testing/browser-functional/browser-tests-build-ci.yml
Fixes #minor
Upgrade the node version used in JS pipelines from 12 to 16.
This upgrade was prompted by discovering that the latest chromedriver, v 107.0.3, errors on 12:
```
error chromedriver@107.0.3: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.12"
error Found incompatible module.
```
(chromedriver is used in pipeline JS-Functional-Tests-BrowserBot-yaml.)
=> chore: Upgrade node to v 16 in JS pipelines

testing/browser-functional/browser-tests-build-ci.yml
Fixes #minor
Improved logging makes it easier for build admin to monitor available versions and adjust driver version when needed.
=> chore: Improve 'Get second latest chromedriver' logging

libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-core/src/activityHandler.ts, libraries/botbuilder-core/src/activityHandlerBase.ts, libraries/botbuilder-core/tests/ActivityHandler.test.js, libraries/botbuilder-core/tests/activityHandlerBase.test.js, libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js
This PR aims to extend the Bot SDK so that developers can consume newly added events that Teams will emit to the bot. They are:
`TeamsMessageEdit` - a user editing a message in Teams.
`TeamsMessageUndelete` - a user undo-ing a deleted message in Teams.
`TeamsMessageSoftDelete` - a user deleting a message in Teams.
Closes #4375
* Extended `ActivityHandlerBase` to handle `MessageUpdate` and `MessageDelete` activity types
* Extended `ActivityHandler` to handle `MessageUpdate` and `MessageDelete` activity types and dispatch functions for subtypes.
* Extended `TeamsActivityHandler` to handle `MessageUpdate` (with subtypes `TeamsMessageEdit` and `TeamsMessageUndelete`) and `MessageDelete` (with subtype `TeamsMessageSoftDelete`) teams events.
* Ran `yarn build:rollup` on both the `botbuilder` …
=> feat: teams message update & message delete events

package.json, yarn.lock
Fixes #4370
This PR updates the [@azure/ms-rest-js](https://www.npmjs.com/package/@azure/ms-rest-js) library inside the [@azure/cognitiveservices-luis-runtime](https://www.npmjs.com/package/@azure/cognitiveservices-luis-runtime) dependency, from `1.6.0` to `2.6.1`, so the [uuid](https://www.npmjs.com/package/uuid?activeTab=readme) library is upgraded from the version `3.4.0` to `8.3.2` (the warning message is also removed).
> **Note:** upgrading the uuid from the version 3 to 8 alone wasn't possible due to deprecated imports ([more information](https://github.com/uuidjs/uuid#upgrading-from-uuid3)).
- Added a new resolutions' field at the root _package.json_ file, upgrading the ms-rest-js version to `2.6.1`.
- Updated _yarn.lock_ file with the updated ms-rest-js version.
The following …
=> fix: [#4370] Update @azure/cognitiveservices-luis-runtime > @azure/ms-rest-js library

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsInfo.ts, libraries/botbuilder/tests/teamsInfo.test.js, libraries/botframework-connector/src/teams/models/index.ts, libraries/botframework-connector/src/teams/models/mappers.ts, libraries/botframework-connector/src/teams/models/teamsMappers.ts, libraries/botframework-connector/src/teams/operations/teams.ts, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts
This feature aims to extend the JS Bot SDK so that developers can send targeted meeting notifications in Microsoft Teams meetings.
Closes #4384
Ran yarn build:rollup on both the botbuilder, botframework-connector & botframework-schema libraries to generate public api doc.
- Added `sendMeetingNotification` method to `TeamsInfo` class.
- Added multiple interfaces to the `index.ts` monolith of interfaces & types related to Teams meeting notifications. `TeamsMeetingNotification` interface defines the `notification` payload to the API call. All other interfaces are used to build this interface.
- Added a type to teams related model.
- Added multiple ms-rest objects used in the ms-rest set up for the REST API call.
- Implemented `sendMeetingNotification` REST API call using the existing ms-rest …
=> feat: send targeted meeting notification in Teams meetings

libraries/botbuilder-core/etc/botbuilder-core.api.md, libraries/botbuilder-core/src/cardFactory.ts, libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts, libraries/botbuilder-dialogs/tests/oauthPrompt.test.js, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
Fixes #4315
This PR introduces support for passing through a token post resource via botbuilder. The token post resource contains a sas url for directly posting a token from a client to the bot framework token service. Botbuilder gets this url from token service and passes it onto the client.
These changes were ported from .NET repository.
- Add support for token post resource
- Support optional token post resource inside oauthcard
- Added unit tests 
- Working sample
=> port: [#4315] Support passing sas token url's for token service (#6449)

libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts, libraries/botbuilder-dialogs-adaptive-runtime/test/index.test.ts
Fixes #4351
This PR ports the changes from .NET [PR#6533](https://github.com/microsoft/botbuilder-dotnet/pull/6533) to throw an error if the storage value of the _runtimeSettings_ does not match any of the possible values. Only defaults to _MemoryStorage_ for an empty/missing storage value.
- Updated default case in **_addStorage_** function of `botbuilder-dialogs-adaptive-runtime/index.ts`.
- Updated a unit test and added two new ones to cover the new scenario in `botbuilder-dialogs-adaptive-runtime/test/index.test.ts`.
This image shows the new unit tests passing.
=> port: [#4351] Throwing for invalid runtimeSettings.storage values or missing storage config (#6533)

libraries/botbuilder-dialogs/etc/botbuilder-dialogs.api.md, libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts, libraries/botbuilder-dialogs/src/prompts/prompt.ts, libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
Fixes #4369
This PR adds the **_recognizeLanguage_** property in the **_PromptOptions_** interface.
It also updates the _onRecognize_ method of the _**ConfirmPrompt**_ class to use this property solving the issue when a ConfirmPrompt is used along with a TranslationMiddleware.
- Updated **_PromptOptions_** interface adding the **_recognizeLanguage_** property.
- Updated the **_onRecognize_** method of the **_ConfirmPrompt_** class using the new property.
- Added a unit test in **_confirmPrompt.tests_** to cover the new test case.
These images show how the sample bot recognizes the option in French.
=> port: [#4369] Prompt validation of confirm prompt in chatbot is not working for newly added language (#6554)

libraries/botbuilder-m365/src/AdaptiveCards.ts, libraries/botbuilder-m365/src/Application.ts, libraries/botbuilder-m365/src/MessageExtensions.ts
#minor
The current pattern in botbuilder-m365's `Application` is that all routes are registered to a single array and processed in order of the registration (via `Application.addRoute()`). This leads to an edge case where Teams' Invoke Activities may not be responded within the required time window.
A developer first registers 10 AppRoutes. Their RouteSelectors are for non-Invoke activities, but each require a minimum of 500ms to determine whether or not the RouteHandler should handle the activity.
The developer then registers 3 Message Extension AppRoutes and 3 AdaptiveCards' CardAction AppRoutes.
When an Invoke activity is received by the Application, it iterates over the first 10 AppRoutes, which take at least 5 seconds for all the RouteSelectors to determine that they won't process …
=> fix: refactor Route registration and Application.run() for better Invoke-handling

testing/functional/functionaltestbot/template/linux/template.json, testing/functional/tests/directLine.test.js
Fixes #4414
This PR fixes the errors in the JS Linux Functional Test pipeline. It also applies some prettier fixes to the DirectLine tests.
The error `TypeError: Cannot read property 'text' of undefined` was fixed by upgrading the **_botSku_** from F0 to S1, as the bot was throwing an error related to the _max transactions being exceeded_.
We also had an authorization issue that was solved by upgrading the bot's **_Node version from 10 to 16._**
- Updated the `functionaltestbot/template/linux/template.json` to upgrade the Node version to 16 and the botSku default value to S1.
- Updated prettier issues in `testing/functional/tests/directLine.test.js`.
This image shows the testing pipeline successfully executed after the changes:
=> fix: [#4414] JS Linux Functional Test pipeline failing

libraries/botbuilder/src/teamsActivityHandler.ts
Added remarks for usage of `Message Update` and `Message Delete` events
Fixes #4406 
Documentation changes to include remarks on the Teams-related message update and message delete activities.
=> fix: Teams activity handler documentation fix

libraries/botbuilder-core/src/botState.ts
Fixes #4423 
Thanks to @tdurnford for help with this.
Adds a check for null values in botState.ts which was allowing null to pass through.
- Added `value === null` to the check on line 228.
- Tested in a sample bot and successfully connected to the skill
- Passed tests
=> fix: Add check to handle bad values in Orchestrator botState.ts

libraries/botbuilder/src/teams/teamsSSOTokenExchangeMiddleware.ts, libraries/botbuilder/tests/teams/teamsSSOTokenExchangeMiddleware.test.js
Fixes #4408
This PR allows the SSO Teams bots to work with CloudAdapter. It also adds the unit tests for the different adapter cases.
- Updated teamsSSOTokenExchangeMiddleware to allow UserTokenClient tokens.
- Added unit tests for _botFrameworkAdapter_ and _cloudAdapter_ cases.
Added unit tests for the _exchangedToken_ method.
=> fix: [#4408] Cloud adapter is not working with teams SSO

libraries/botbuilder/src/channelServiceRoutes.ts, libraries/botbuilder/tests/channelServiceRoutes.test.js
#minor
Fixes **Internal**: https://portal.microsofticm.com/imp/v3/incidents/details/365652257/home
restify 10.0.0 and greater enforces the need for a `next()` callback that passes execution to the next function in the handler chain. `channelServiceRoutes.ts` does not currently address this requirement. Since this class is required to interact with skills, this means that root bots that import this class will fail to start.
- Add the `next: Function` parameter to the handlers in `channelServiceRoutes.ts`
- Add a `return next()` statement to the aforementioned handlers
- Update the tests in `channelServiceRoutes.test.js` to pass in an empty `Function` as `next` in each test
Ran the updated unit tests successfully.
=> fix: Update channelServiceRoutes to add next() parameter to support restify 10.0.0+ 

libraries/botframework-streaming/src/payloads/requestManager.ts, libraries/botframework-streaming/src/protocolAdapter.ts, libraries/botframework-streaming/src/webSocket/browserWebSocketClient.ts, libraries/botframework-streaming/src/webSocket/nodeWebSocketClient.ts, libraries/botframework-streaming/src/webSocket/webSocketTransport.ts, libraries/botframework-streaming/tests/Assembler.test.js, libraries/botframework-streaming/tests/ContentStream.test.js, libraries/botframework-streaming/tests/Disassembler.test.js, libraries/botframework-streaming/tests/NamedPipe.test.js, libraries/botframework-streaming/tests/NodeWebSocket.test.js, libraries/botframework-streaming/tests/PayloadSender.test.js, libraries/botframework-streaming/tests/ProtocolAdapter.test.js, libraries/botframework-streaming/tests/RequestManager.test.js, libraries/botframework-streaming/tests/StreamManager.test.js, libraries/botframework-streaming/tests/WebSocket.test.js, libraries/botframework-streaming/tests/WebSocketClientServer.test.js, libraries/botframework-streaming/tests/helpers/createDeferred.js, libraries/botframework-streaming/tests/helpers/expectEventually.js, libraries/botframework-streaming/tests/helpers/fauxSock.js, libraries/botframework-streaming/tests/helpers/index.js
Fixes #4452. Fixes #4456. Fixes #4460.
When Web Socket disconnected, all pending requests should be rejected.
- Added `RequestManager.rejectAllResponses()` to reject all pending responses
- Updated `browserWebSocketClient` and `nodeWebSocketClient` to call `RequestManager.rejectAllResponses()` on disconnection
- Fixed inconclusive tests related to `.to.throw`
- Fixed a racing condition in `ProtocolAdapter`
- If server respond quickly, some responses may be dropped
- This is because their respective requests are registered in `RequestManager` only after the request is send, the response may already get through
Added tests to make sure `NodeWebSocketClient` and `WebSocketServer` can communicate with each other by using real Web Socket. This should make our test more stable.
Note: because …
=> fix: [#4452][#4456][#4460][botframework-streaming] Should reject pending requests on disconnection

libraries/botbuilder/tests/channelServiceRoutes.test.js, libraries/botframework-connector/tests/connector.test.js, libraries/botframework-streaming/tests/Assembler.test.js, libraries/botframework-streaming/tests/NamedPipe.test.js, libraries/botframework-streaming/tests/PayloadSender.test.js, libraries/botframework-streaming/tests/ProtocolAdapter.test.js, libraries/botframework-streaming/tests/StreamManager.test.js
Fixes #4455
This PR modifies and removes unnecessary `done` function calls from all unit tests.
- Redundant `done` function calls have been removed to use only one.
- Removed `done` function calls where wasn't necessary.
=> fix: [#4455] [botframework-streaming] Tests are not conclusive

libraries/botbuilder-core/src/telemetryConstants.ts, libraries/botbuilder-core/src/telemetryLoggerMiddleware.ts, libraries/botbuilder-core/src/turnContext.ts, libraries/botbuilder-core/tests/telemetryMiddleware.test.js
Fixes #4466
This PR adds the `activityId` and `conversationId` properties to the `TelemetryLoggerMiddleware` functionality. Additionally, it fixes a port issue where the `activity.id` property wasn't being available after sending the activities.
- Added `activityId` key property to the telemetry constants class.
- Added `activityId` property to the `TelemetryLoggerMiddleware` class.
- Fixed a port issue where the `activity.id` property wasn't available after sending the activities.
- Updated unit tests to assert over the `conversationId` and `activityId` properties.
The following image shows how the `activityId` and `conversationId` properties are displayed correctly.
=> fix: [#4466] Fix telemetry activityId and conversationId properties

libraries/botbuilder-core/src/configurationBotFrameworkAuthentication.ts, libraries/botbuilder-core/src/configurationServiceClientCredentialFactory.ts, libraries/botbuilder-core/tests/configurationServiceClientCredentialFactory.test.js, libraries/botframework-connector/src/auth/authenticationConstants.ts, libraries/botframework-connector/src/auth/certificateServiceClientCredentialsFactory.ts, libraries/botframework-connector/src/auth/index.ts
Fixes #4449
This PR adds support for the CloudAdapter's configuration process to authenticate using certificates is _MultiTenant_ and _SingleTenant_ apps.
- Added `CertificateServiceClientCredentialsFactory` class, to instantiate and configure the `CertificateAppCredentials` class, so the process knows how to authenticate with certificates.
- Added `ConfigurationServiceClientCredentialFactory` unit tests, validating the different code paths when using certificates.
- Added `CertificateThumbprint` and `CertificatePrivateKey` constants to the `AuthenticationConstants`, `ConfigurationBotFrameworkAuthentication` and `ConfigurationServiceClientCredentialFactory` classes.
- Updated `ConfigurationServiceClientCredentialFactory` to detect when a certificate is provided, and execute the proper …
=> fix: [#4449] CloudAdapter always builds Connector with MicrosoftAppCredentials (never CertificateAppCredentials) -- certificate auth flow broken

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHelpers.ts, libraries/botbuilder/tests/teamsHelpers.test.js, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts
Fixes #4463
This PR ports the changes in .NET to add the _OnBehalfOf_ property and send messages via bots on behalf of another user in Teams.
- Added the _**OnBehalfOf**_ property in the _TeamsChannelData_ interface.
- Added the **_teamsGetTeamOnBehalfOf_** method in _teamsActivityHelpers_ to return the current activity's _OnBehalfOf_ list.
- Added unit tests in **_teamsHelpers.test_** to cover the new code.
The following image shows the message of the bot on behalf of another user in the Teams channel.
=> port: [#4463][#6596] TeamsChannelData need OnBehalfOf

libraries/adaptive-expressions/package.json, libraries/adaptive-expressions/src/builtinFunctions/xml.ts, yarn.lock
https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-3325616
#minor
- 
-
-
=> fix: Updates fast-xml-parser to address "Prototype Pollution" vulnerability

libraries/botbuilder-ai/etc/botbuilder-ai.api.md, libraries/botbuilder-ai/src/customQuestionAnswering.ts, libraries/botbuilder-ai/src/qnamaker-interfaces/qnamakerOptions.ts, libraries/botbuilder-ai/src/qnamaker-utils/languageServiceUtils.ts, libraries/botbuilder-ai/tests/languageService.test.js
Fixes #4482 
This PR allows adding the _userId_ property which was empty when displaying the _AzureDiagnostics_ table in the Log Analytics workspace resource.
- Added **_userId_** property to the _queryKnowledgebaseRaw_ request in the _LanguageServiceUtils_ file.
- Added **_userId_** property to the _QnAMakerOptions_ interface.
- Updated parameter sending of _queryKnowledgebaseRaw_, allowing to send the userId to the _QnAMakerOptions_ using the context activity
The following image shows the _AzureDiagnostics_ log with the _userId_ value.
=> port: [#4482][#6588] UserId not being passed to AzureDiagnostics

libraries/botbuilder-core/package.json, libraries/botbuilder-core/tests/transcriptUtilities.js, yarn.lock
#minor
This PR replaces the **_request_** package in `botbuilder-core/tests/transcriptUtilities.js` with **_axios_** to avoid the [security vulnerability issue](https://github.com/request/request/issues/3442).
- Replaced _request_ get with _axios_ get in the `downloadAndExtractOnce` function used for the transcript tests.
- Removed _request_ dependency from `package.json`
- Updated `yarn.lock` file
This image shows one of the tests that are using the _transcriptUtilities_, working after the changes.
=> fix: Remove request package from botbuilder-core tests

libraries/botbuilder-core/package.json, libraries/botbuilder-core/tests/transcriptUtilities.js, yarn.lock
#minor
This PR replaces the _chatdown_ dependency with the _@microsoft/bf-chatdown_ package to avoid the use of request due to its [security vulnerability issue](https://github.com/request/request/issues/3442).
- Replaced  _chatdown_ with the _@microsoft/bf-chatdown_  in **_transcriptUtilities_**.
The following image shows one of the transcripts tests running after the changes.
=> fix: Replace chatdown package from botbuilder-core tests

libraries/adaptive-expressions/src/parser/expressionParser.ts, libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts
#minor
This PR replaces the use of **Map** with **WeakMap** in the _LanguageGeneratorExtensions_ and _ExpressionParser_ classes due to a memory leak issue reported in a JS Composer bot.
- Replaced _Map_ `_languageGeneratorManagers` with _WeakMap_ in `LanguageGeneratorExtensions`.
- Replaced _Map_ `expressionDict` with _WeakMap_ in `ExpressionParser`. Also, changed the type of the key as _WeakMap_ only supports objects.
The unit tests passed after the changes.
=> fix: Replace Map with WeakMap to avoid memory leak

generators/generator-botbuilder/generators/app/templates/echo/package.json.js
#minor
Current version of restify leads to the following error on Node 18+:
```
➜  my-echo-bot npm start
> my-echo-bot@1.0.0 start
> node ./index.js
/home/gregborrelly/development/myJsBots/my-echo-bot/node_modules/restify/lib/request.js:848
Request.prototype.closed = function closed() {
^
TypeError: Cannot set property closed of #<Readable> which has only a getter
at patch (/home/gregborrelly/development/myJsBots/my-echo-bot/node_modules/restify/lib/request.js:848:30)
at Object.<anonymous> (/home/gregborrelly/development/myJsBots/my-echo-bot/node_modules/restify/lib/server.js:33:1)
```
- Upgraded restify version in Package.json
Create a echo bot dot following the SDK docs, if you are on Node 18 or above you will run into the following error. …
=> fix: Upgrading restify to fix error on Node version 18+

libraries/botbuilder/tests/cloudAdapter.test.js
Fixes #4529
This PR fixes the _throws exception on expired token_ test updating the token and avoiding logging an error in the console.
> Note: Because the implementation of the token validation between [_botbuilder-dotnet_](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs#L229) and [_botbuilder-js_](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-connector/src/auth/jwtTokenExtractor.ts#L132) is different, we haven't ported .NET changes, since _botbuilder-js_ uses a cache check as a security method for the token key. 
- Updated authorization token in  _throws exception on expired token_ test.
- Replaced the use of sinon.spy by sinon.stub in  _throws exception on expired token_ test in …
=> port: [#4529] Update JwtTokenExtractor

generators/generator-botbuilder/generators/app/templates/core/index.ts, generators/generator-botbuilder/generators/app/templates/core/package-with-tests.json.js, generators/generator-botbuilder/generators/app/templates/core/package-with-tests.json.ts, generators/generator-botbuilder/generators/app/templates/core/package.json.js, generators/generator-botbuilder/generators/app/templates/core/package.json.ts, generators/generator-botbuilder/generators/app/templates/core/tsconfig.json, generators/generator-botbuilder/generators/app/templates/echo/package.json.js, generators/generator-botbuilder/generators/app/templates/echo/package.json.ts, generators/generator-botbuilder/generators/app/templates/echo/tsconfig.json, generators/generator-botbuilder/generators/app/templates/empty/package.json.js, generators/generator-botbuilder/generators/app/templates/empty/package.json.ts, generators/generator-botbuilder/generators/app/templates/empty/tsconfig.json
Fixes #4520
This PR upgrades the **_restify_** dependency to version _11.1.0_ to avoid the error on Node 18+.
It also updates the target in TS bots, as the new version of _restify_ introduced a [breaking change](https://github.com/restify/node-restify/issues/1935).
Additionally, it upgrades **_botbuilder_** packages to version _4.20.0_ and fixes an eslint issue in the core bot's index.ts.
- Updated remaining TS and JS bots to use `restify` version _11.1.0_.
- Upgraded `botbuilder` packages to version _4.20.0_.
- Updated the `tsconfig.json`'s _target_ property to _es2017_.
- Fixed a lint issue in `templates/core/index.ts`.
These images show the generated bots working and the tests in _core-with-tests_ passing.
=> fix: [#4520] Upgrade restify to fix error on Node version 18+

libraries/botframework-config/package.json, libraries/botframework-config/src/botConfiguration.ts, package.json, yarn.lock
Fixes #4525
This PR removes the _read-text-file_ dependency to avoid the use of LGPL.
- Replaced _read_ and _readAsync_ functions with fs's _readFileSync_ and _readFile_ in _**BotConfiguration**_ class.
- Removed _read-text-file_ from the packages.json files.
The following image shows the _botframework-config_ tests, which use _**BotConfiguration**_ class, running successfully.
=> fix: [#4525] Replace read-text-file package to avoid using LGPL

libraries/botbuilder/etc/botbuilder.api.md, libraries/botbuilder/src/teamsActivityHandler.ts, libraries/botbuilder/tests/teamsActivityHandler.test.js, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts, package.json
Fixes #4530 
This PR ports the changes in [PR#6677](https://github.com/microsoft/botbuilder-dotnet/pull/6677) to add support for the new meeting participants join/leave events.
- Added support for 2 new activity types - `application/vnd.microsoft.meetingParticipantJoin` and `application/vnd.microsoft.meetingParticipantLeave`.
- Added functions to register handlers for when teams meeting participants are joined/left.
- Added unit tests for every case.
This image shows the implementation tested with a sample.
=> port: [#4530] Add support for meeting participants added/removed events

README.md, libraries/botbuilder-dialogs-adaptive-runtime-core/src/serviceCollection.ts, libraries/botframework-connector/package.json, libraries/botframework-connector/src/auth/index.ts, libraries/botframework-connector/src/auth/msalAppCredentials.ts, libraries/botframework-connector/src/auth/msalServiceClientCredentialsFactory.ts, testing/consumer-test/run.ts, yarn.lock
#minor
Addresses #2782
This PR adds support for MSAL as the first step to remove ADAL dependency from the repository.
As MSAL supports a limited number of TS versions, we removed support for versions 3.5, 3.6, and 3.7.
- Added new class `MsalAppCredentials`.
- Added new class `MsalServiceClientCredentialsFactory`.
- Updated `consumer-test/run.ts` to remove old TS versions from the testing matrix.
- Added TS version >= 3.8 as a pre-requisite in the README file
These images show a bot working with MSAL using credentials and certificates to authenticate.
=> fix: [#2782] Migrate to MSAL from adal-node - Add MSAL support

libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts
Fixes #4420
- `ParameterizedBotFrameworkAuthentication` uses `connectorClientOptions` to create `ConnectorFactory`.
=> fix: use connectorClientOptions to create ConnectorFactory (#4420)

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/sharepoint/handleActionResponse.ts
Fixes #4557 
The PR fixes issue with incorrectly named property for SharePoint `HandleActionResponse`.
- rename `type` to `responseType` in `BaseHandleActionResponse`, `CardViewHandleActionResponse`, `QuickViewHandleActionResponse` and `NoOpeHandleActionResponse`
Full flow tests using locally served bot and SharePoint Online.
=> fix: [SharePointActivityHandler] Rename type to responseType in handleActionResponse

libraries/adaptive-expressions/etc/adaptive-expressions.api.md, libraries/botbuilder-ai/etc/botbuilder-ai.api.md, libraries/botbuilder-dialogs-adaptive-testing/etc/botbuilder-dialogs-adaptive-testing.api.md, libraries/botbuilder-dialogs-adaptive/etc/botbuilder-dialogs-adaptive.api.md, libraries/botbuilder/package.json, libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/cloudAdapter.ts, libraries/botbuilder/src/setSpeakMiddleware.ts, libraries/botbuilder/src/teams/teamsSSOTokenExchangeMiddleware.ts, libraries/botbuilder/tests/cloudAdapter.test.js, libraries/botbuilder/tsconfig.json, libraries/botframework-connector/package.json, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/package.json, libraries/botframework-schema/src/index.ts, libraries/botframework-streaming/etc/botframework-streaming.api.md, package.json, testing/botbuilder-test-utils/package.json, testing/consumer-test/run.ts, yarn.lock
Addresses #4545
#minor
This PR migrates the use of zod 1.11.17 to ^3.22.4 to avoid [ReDoS](https://security.snyk.io/vuln/SNYK-JS-ZOD-5925617) vulnerability.
- Updated zod version to **^3.22.4** in 
- botbuilder
- botframework-schema
- botframework-connector
- botbuilder-tests-utils
- Replaced use of **_check_** method with **_safeParse_**.
The following image shows some bot samples working after the update.
=> fix: [#4545] Please upgrade zod package - botbuilder

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/teams/index.ts
Fixes #4566
My original PR had discrepancies with the C# implementation, so this is the fix
- `CacheInfo` added as optional to `ConfigAuth`
- fix `ConfigAuth` response type to 'config'
- fix BotConfigAuth type to be 'auth' only
=> fix: #4566 Teams config fetch typings

libraries/botbuilder-dialogs/README.md
Corrected typo, `steo` should be `step` within README documentation.
Fixes #
Corrected a typo in the readme
- "steo" should be "step"
=> chore: corrected typo in README.md

libraries/botbuilder-ai/src/qnaMaker.ts, libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts
Fixes #4568
This PR reverts part of the changes in PR #4208 where the function that filtered the QnAMaker results using the score threshold value set in the QnAMaker options was removed.
It also includes a condition to skip the filter when the returned answer is the QnAMaker default answer.
- Adding back the `sortAnswersWithinThreshold` function in _generateAnswerUtils.ts_.
- Restored the call to the sort function in the _QnAMaker_ class before returning the results.
These images show the results returned when a score threshold is set with a value of 0.65:
=> fix: [#4568] scoreThreshold no longer works in 4.17.0 and later

libraries/botframework-connector/package.json, libraries/botframework-connector/src/auth/certificateServiceClientCredentialsFactory.ts, yarn.lock
#minor
This PR allows the creation of an object of the _CertificateServiceClientCredentialsFactory_ class using only the values:
- _App Id_
- _x5c_ 
- _Certificate key_
In addition to being able to get the thumbprint value through the certificate when creating the credentials.
- Added the possibility of two possible parameters (thumbprint of x5c) for the constructor of the _CertificateServiceClientCredentialsFactory_ class.
- Added the method _**getThumbprint**_ to obtain the thumbprint value of the certificate when the x5c value is provided.
The following image shows the bot running with SNI authentication.
This is the configuration required to use the SNI authentication.
=> feat: Extraction of thumbprint value through the certificate

libraries/botbuilder/src/botFrameworkAdapter.ts, libraries/botbuilder/src/botFrameworkHttpClient.ts, libraries/botframework-connector/src/auth/appCredentials.ts, libraries/botframework-connector/src/auth/governmentConstants.ts, libraries/botframework-connector/src/auth/index.ts, libraries/botframework-connector/src/auth/microsoftGovernmentAppCredentials.ts, libraries/botframework-connector/src/auth/msalServiceClientCredentialsFactory.ts, libraries/botframework-connector/src/auth/passwordServiceClientCredentialFactory.ts, libraries/botframework-connector/tests/auth/microsoftAppCredentials.test.js, libraries/botframework-connector/tests/auth/microsoftGovernmentAppCredentials.test.js
Fixes #6717 
C# PR #6714
Fix a potential bug with USGov OAuthEndpoint while using SingleTenant.
Single tenant can't get token within <MicrosoftServices.onmicrosoft.us>.
Update MicrosoftGovernmentAppCredentials.OAuthEndpoint.
Test locally, hard to add usgov single appid/password to the TestEnvironment.
MicrosoftGovernmentAppCredentialsTests.ConstructorTests
=> fix: USGovSingleTenant OAuthEndpoint

libraries/botbuilder-core/package.json, libraries/botbuilder/package.json, libraries/botframework-connector/package.json, libraries/botframework-connector/src/auth/botFrameworkClientImpl.ts, yarn.lock
#minor
This PR updates the _axios_ package and replaces it  with _fetch_ in _botframework-connector_ due to a [breaking change](https://stackoverflow.com/questions/73958968/cannot-use-import-statement-outside-a-module-with-axios) in version 1.x.x of _axios_.
- Updated _axios_ version to _**^1.6.0**_ in botbuilder and botbuilder-core.
- Replaced _axios_ with _fetch_ in the _**botFrameworkClientImpl**_ class.
The following image shows a bot working using _CloudAdapter_ with the _botframework-connector_ fix.
=> fix: Update axios and fix issue in botframework-connector

libraries/botframework-connector/src/auth/botFrameworkClientImpl.ts
#minor
This PR includes the HTTP method _**post**_ to the _fetch_ request.
- Added _**post**_ method to the _fetch_ request in botFrameworkClientImpl.
- Imported _fetch_ from **_cross-fetch_**.
- Removed the _body_ parse.
The following image shows a skill bot working using _CloudAdapter_ with the _botframework-connector_ fix.
=> fix: Add HTTP method in fetch request

libraries/botbuilder-core/src/botState.ts, libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
#minor
This PR fixes an issue where the predefined skipped properties were removed from the bot's state cache object, instead of removing them only from the cache hash calculation because of the original issue (https://github.com/microsoft/botbuilder-js/issues/4325).
- Updated skipProperties method to not modify the parameter value, and instead generate a copy, so later the hash calculation can use.
- Updated the unit tests for BeginSkill, showing the properties are no longer deleted from the cache.
- Added `skillClient` to the skipped properties.
The following image shows the current error, and the bot working from the original issue.
=> fix: BotState cache hash skipped properties

testing/browser-functional/browser-tests-build-ci.yml, testing/browser-functional/nightwatch.conf.js, testing/browser-functional/package.json, yarn.lock
#minor
This PR avoids the Command Injection vulnerability by removing the _**chromedriver**_ package and replaces its functionality using its binary to perform the browser unit tests.
- Removed  _**chromedriver**_ package from browser-functional tests.
- Added _**chromedriver**_ binary into browser-functional.
- Modified server path of _nigthwatch_ chrome configuration.
- Removed unnecessary jobs related to _**chromedriver**_ in the _browser-tests-build-ci_ pipeline.
The following image shows the _browser-tests-build-ci_ pipeline running successfully after the changes.
=> fix: Add chromedriver binary in its updated version

libraries/botbuilder-dialogs-adaptive-runtime-core/package.json, libraries/botbuilder-dialogs-adaptive-runtime/package.json, yarn.lock
#minor
This PR updates the _**mocha**_ package to avoid the use of versions of _**nanoid**_ lower than 3.1.31 and the _Exposure of Sensitive Information to an Unauthorized Actor_ vulnerability.
- Updated _**mocha**_ package from ^8.2.1 to ^9.2.2 in _botbuilder-dialogs-adaptive-runtime_ and _botbuilder-dialogs-adaptive-runtime-core_.
The following image shows the unit tests passing after the update.
=> bump: Update mocha package to avoid vulnerability with nanoid

libraries/botbuilder-ai/package.json, package.json, yarn.lock
#minor
This PR updates the _**follow-redirects**_ package to avoid the _Exposure of Sensitive Information to an Unauthorized Actor_ vulnerability.
- Updated _**follow-redirects**_ package from 1.14.7 to ^1.14.8.
- Added _**follow-redirects**_ resolution to the version ^1.14.8.
The following image shows the unit tests passing after the update.
=> bump: Update follow-redirects to avoid vulnerability

libraries/botframework-connector/package.json, libraries/botframework-connector/src/auth/jwtTokenExtractor.ts, libraries/botframework-connector/src/auth/openIdMetadata.ts, libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts, yarn.lock
Fixes #4544
This PR fixes the error thrown in _openIdMetadata_ when the bot is used behind a proxy server by setting the proxy's URL in the fetch agent.
- Updated `parameterizedBotFrameworkAuthentication` to pass the proxy settings to _jwtTokenExtractor_.
- Updated `jwtTokenExtractor` to pass the proxy settings to _openIdMetadata_.
- Updated `openIdMetada` to set the agent in the fetch, containing the proxy URL.
- Replaced `cross-fetch` with `node-fetch` to pass the agent option.
We tested this using different tools to simulate HTTP and HTTPS proxies.
These images show the request intercepted by the proxy and the bot working.
=> fix: [#4544] JwtTokenExtractor.getIdentity:err! FetchError: request to https://login.botframework.com/v1/.well-known/openidconfiguration

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/sharepoint/aceData.ts
Fixes #4605
The PR adds `isVisible` property to the `AceData` interface to implement the #4605 feature request.
```ts
interface AceData {
// ...
isVisible?: boolean;
// ...
}
```
=> feat: Add isVisible property to AceData

libraries/botbuilder-core/src/botState.ts, libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
#minor
This PR fixes an issue where the skip properties were not set properly in the correct bot state. It was changed to be set directly in the Conversation State instance.
- Updated the custom internal handler to receive the state to skip the properties from.
The following image shows the change working.
=> fix: skip properties to be set in the Conversation State

libraries/botbuilder-dialogs-adaptive/package.json, libraries/botbuilder-dialogs/package.json
#minor
This PR removes the old version or **_@microsoft/recognizers-text-number_** from the other recognizers packages that require it.
- Added postinstall scripts in botbuilder-dialogs and botbuilder-dialogs-adaptive package.json files to remove the old version of  **_@microsoft/recognizers-text-number_**.
These images show the dependencies tree before and after running the postinstall scripts.
=> fix: Remove old @microsoft/recognizers-text-number version with postinstall scripts

package.json, testing/functional/package.json, testing/functional/tests/directLine.test.js, yarn.lock
#minor
This PR updates the _**swagger-client**_ package to stop using **_lodash-compat_** because this package has been [discontinued](https://www.npmjs.com/package/lodash-compat).
- Updated _**swagger-client**_ package from ^2.1.18 to ^3.0.0.
- Added _**@types/ramda**_ 0.26.0 to resolutions.
- Updated functional tests to use new _**swagger-client**_ version.
The following image shows the functional unit test passing after the update.
=> bump: Update swagger-client to stop using lodash-compat

libraries/botframework-connector/src/connectorApi/models/mappers.ts, libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
Fixes #4584
This PR includes the **_Properties_** property to the _ChannelAccount_ interface to allow using optional properties.
- Added _**Properties**_ property to the _ChannelAccount_ interface.
- Added _**properties**_ serialization in CompositeMapper.
The following image shows the object Properties retrieved in the request body of the bot.
=> fix: [#4584] ChannelAccount cannot accept extensible properties

package.json, testing/browser-functional/browser-echo-bot/package.json, testing/browser-functional/browser-echo-bot/yarn.lock, yarn.lock
#minor
This PR updates the _**follow-redirects**_ package version to ^1.15.4 to avoid [_improperly handles URLs_](https://github.com/microsoft/botbuilder-js/security/dependabot/319) vulnerability.
- Updated  _**follow-redirects**_  to ^1.15.4 in _browser-echo bot_ and _botbuilder_.
The following image shows the _browser-echo bot_  working after the changes.
=> bump: Update follow-redirects to ^1.15.4

libraries/botbuilder/package.json, libraries/botframework-connector/package.json, package.json, tools/package.json, yarn.lock
Fixes #4599 
This PR updates the versions of the packages **_@azure/msal-node_** and _**@azure/msal-browser**_ to avoid the use of deprecated versions.
- Updated _**@azure/msal-node**_ to ^1.18.4 in _botbuilder, botframework-connector_ and _tools_.
- Added resolutions _**axios: 0.21.4,**_ **_@azure/msal-node: ^1.18.4_** and _**@azure/msal-browser: ^2.38.3**_.
The following image shows an _echo bot_ working with authentication after the updates.
=> bump: Update @azure/msal-node and @azure/msal-browser

libraries/botframework-connector/src/auth/authenticationConstants.ts, libraries/botframework-connector/src/auth/emulatorValidation.ts
#minor
This PR includes a dynamic way to validate the access token _**issuer**_ value depending on the tenant ID used in Emulator.
- Added logic to validate the _**tid**_ and _**issuer**_ values to allow the Single Tenant authentication
The following image shows the Emulator working with a bot using Single Tenant authentication.
=> feat: Support Single Tenant authentication through BotFramework-Emulator

libraries/botframework-connector/src/auth/appCredentials.ts, libraries/botframework-connector/src/auth/certificateAppCredentials.ts, libraries/botframework-connector/src/auth/certificateServiceClientCredentialsFactory.ts, libraries/botframework-connector/src/auth/microsoftAppCredentials.ts, libraries/botframework-connector/src/auth/passwordServiceClientCredentialFactory.ts
Fixes #4636
This PR adds more information to optional Tenant parameters used in authentication classes. Explaining when it's optional or required, and the default when no value is provided.
- Add Tenant comment to authentication (AppCredentials, CertificateAppCredentials, MicrosoftAppCredentials, and auth factories) classes.
- The new comment contains information when required, optional, and the default value. Additionally, a link to the supported Azure app types.
The following image shows how the new comment looks.
=> chore: [#4636] Add more information to Tenant parameters

libraries/botframework-connector/src/auth/jwtTokenValidation.ts
=> fix: SM02383 suppression

libraries/botbuilder-azure/package.json, libraries/botbuilder-azure/src/cosmosDbKeyEscape.ts, yarn.lock
Fixes #4483
This PR changes the use of _**bcrypt**_ for _**bcryptjs**_ to improve the portability of botbuilder-js.
- Replaced _**bcrypt**_ ^5.0.1 by _**bcryptjs**_ ^2.4.3.
The following image shows the _CosmosDbKeyEscape_ unit tests working with the _hashSync_ method from _**bcryptjs**_.
=> fix: [#4483] Switching npm dependency bcrypt to bcryptjs

package.json, yarn.lock
#minor
This PR updates the version of the package **glob-parent** to 5.1.2 and avoids the [CVE-2022-28469](https://security.snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905) vulnerability.
- Updated **glob-parent** to 5.1.2
=> fix: Remove CVE-2020-28469 with with glob-parent 5.1.1 (High)

libraries/botbuilder-lg/src/evaluationOptions.ts
#minor
This PR removes `eval()` from the **botbuilder-lg** package.
There is no need for side-effects at execution time for the `nullSubstitution` lambda function.
Additionally, the related CodeQL and ESLint suppressions have been removed, as there is no use for them anymore.
- Removed unnecesary `eval()` code.
- Removed ESLint suppression for `security/detect-eval-with-expression`.
- Removed ESLint suppression for `@typescript-eslint/no-unused-vars`.
- Removed CodeQL suppression for SM04509.
The following image shows `EvaluationOptions` tests passing (along with all other tests).
=> fix: CodeQL SM04509 issue

libraries/botframework-streaming/package.json, package.json, testing/browser-functional/browser-echo-bot/package.json, testing/browser-functional/browser-echo-bot/webpack.config.js, testing/browser-functional/browser-echo-bot/yarn.lock, yarn.lock
#minor
This PR updates the version of the `ws` package from `7.1.2` to `7.5.10` to fix the CVE-2024-37890 vulnerability.
Along the way, to address this `ws` package issue for the `browser-functional/browser-echo` project, we have updated all `webpack` related packages to the latest supported node 16 version, fixing the following vulnerabilities.
- ansi-html https://github.com/microsoft/botbuilder-js/security/dependabot/171 - CVE-2021-23424
- braces https://github.com/microsoft/botbuilder-js/security/dependabot/358 - CVE-2024-4068
- dns-packet https://github.com/microsoft/botbuilder-js/security/dependabot/83 - CVE-2021-23386
- elliptic https://github.com/microsoft/botbuilder-js/security/dependabot/71 - CVE-2020-28498
- glob-parent …
=> fix: Remove CVE-2024-37890 vulnerability by updating the ws package

libraries/botbuilder-dialogs-adaptive-runtime-core/package.json, libraries/botbuilder-dialogs-adaptive-runtime/package.json, package.json, testing/streaming-e2e/tests/package.json, testing/transcripts/package.json, tools/package.json, yarn.lock
#minor
This PR updates the version of the package **_mocha_** to ^10.4.0 and avoids the [CVE-2020-36632](https://security.snyk.io/vuln/SNYK-JS-FLAT-596927) vulnerability with flat.
- Updated  **_mocha_** to ^10.4.0 in every library.
The following image shows the **_flat_** version installed after the update.
=> fix: Remove CVE-2020-36632 vulnerability

package.json, yarn.lock
#minor
This PR adds a resolution of _**babel-traverse**_ pointing to **_@babel/traverse_** ^7.24.7 to avoid the [CVE-2023-45133](https://github.com/advisories/GHSA-67hx-6x53-jw92) vulnerability with marked.
- Added resolution pointing to **_@babel/traverse_** ^7.24.7.
The following image shows the **_@babel/traverse_** version installed after the update.
=> fix: Remove CVE-2023-45133 vulnerability

package.json, yarn.lock
#minor
This PR updates the version of **lodash.pick** and fixes the [CVE-2020-8203](https://github.com/advisories/GHSA-p6mc-m468-83gw) vulnerability.
There is no patch for [lodash.pick@4.4.0](https://www.npmjs.com/package/lodash.pick/v/4.4.0) which is a dependency of [nightwatch@2.6.21](https://www.npmjs.com/package/nightwatch/v/2.6.21).
[Per Method Packages](https://lodash.com/per-method-packages) are discouraged by **lodash** and [nightwatch@3.4.0](https://www.npmjs.com/package/nightwatch/v/3.4.0) fixes this.
However, there's a transitive dependency with [jsdom@23.1.0](https://www.npmjs.com/package/jsdom/v/23.1.0) which restricts Node engines to `>=18`.
Thus, we need to force a fully patched version of **lodash** to replace **lodash.pick**.
- Added resolution for …
=> fix: CVE-2020-8203 with lodash.pick

libraries/adaptive-expressions-ie11/package.json, libraries/adaptive-expressions-ie11/webpack.config.js, package.json, tools/package.json, yarn.lock
#minor
This PR updates the version of the `y18n` package to `4.0.3` and `5.0.5` to fix the CVE-2020-7774 vulnerability.
Along the way, to address this `y18n` package issue, we have updated all `webpack` related packages to the latest supported node 16 version, fixing the following vulnerabilities.
- ssri https://github.com/microsoft/botbuilder-js/security/dependabot/25 - CVE-2021-27290
- terser https://github.com/microsoft/botbuilder-js/security/dependabot/215 - CVE-2022-25858
- ini https://github.com/microsoft/botbuilder-js/security/dependabot/15 - CVE-2020-7788
- Updated  `y18n` to `4.0.3` and `5.0.5`.
- Updated  `ssri` and `ini` packages to latest patch release.
- Updated `webpack` and `webpack-cli` to latest version of each that support node 16.
- Updated webpack …
=> fix: Remove CVE-2020-7774 vulnerability by updating the y18n package

libraries/botbuilder-dialogs-declarative/package.json, testing/browser-functional/browser-echo-bot/yarn.lock, yarn.lock
#minor
This PR updates the version of the packages **_chokidar_** and **_braces_** to avoid the [CVE-2024-4068](https://security.snyk.io/vuln/SNYK-JS-BRACES-6838727) vulnerability with braces.
- Updated  **_chokidar_** to ^3.6.0.
- Updated **_braces_** to 3.0.3.
The following image shows the **_braces_** version installed after the update.
=> fix: Remove CVE-2024-4068 vulnerability

libraries/botbuilder-dialogs-declarative/package.json, testing/browser-functional/browser-echo-bot/yarn.lock, tools/package.json, yarn.lock
Addresses #  4684
#minor
This PR updates the version of the package **_minimatch_** to avoid the [CVE-2022-3517](https://security.snyk.io/vuln/SNYK-JS-MINIMATCH-3050818) vulnerability.
- Updated  **_minimatch_** 3.0.2 to 3.1.2.
The following image shows the **_minimatch_** versions installed after the update.
=> fix: Remove CVE-2022-3517 vulnerability

libraries/botbuilder-dialogs-adaptive-testing/tests/adaptiveDialog.test.js, libraries/botbuilder-dialogs-adaptive-testing/tests/resources/AdaptiveDialogTests/AdaptiveDialog_OnQnAMatch.test.dialog, libraries/botbuilder-dialogs-adaptive/etc/botbuilder-dialogs-adaptive.api.md, libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts, libraries/botbuilder-dialogs-adaptive/src/conditions/onQnAMatch.ts
#minor
This PR ports the PR # 6793 which fixes the double QnA trace issue.
- Updated _**AdaptiveDialog**_ to avoid reprocessing recognized activities by adding a condition if the recognized event was already processed.
- Added unit tests to validate the new condition works.
The following image shows how it just throws one trace by every message.
=> port: [#6793][#6792] Composer Bot with QnA Intent recognized triggers duplicate QnA queries 

overrides/lodash.pick/package.json, overrides/lodash.pick/pick.js, package.json, testing/browser-functional/.gitignore, testing/browser-functional/browser-echo-bot/package.json, testing/browser-functional/browser-echo-bot/webpack.config.js, testing/browser-functional/browser-echo-bot/yarn.lock, testing/browser-functional/browser-tests-build-ci.yml, testing/browser-functional/globals.js, testing/browser-functional/nightwatch.conf.js, testing/browser-functional/package.json, testing/browser-functional/tests/message-handling-tests.js, testing/browser-functional/tests/tests_pages/echoBotPage.js, yarn.lock
#minor
This PR updates the version of the `jsonwebtoken` package from `8.x` to `9.x` to fix the CVE-2022-23539 (https://github.com/microsoft/botbuilder-js/security/dependabot/243) vulnerability.
Along the way, the following vulnerabilities were also fixed in this PR:
- sanitize-html https://github.com/microsoft/botbuilder-js/security/dependabot/345 - CVE-2022-25887
- lodash.pick https://github.com/microsoft/botbuilder-js/security/dependabot/324 - CVE-2020-8203
- node-fetch https://github.com/microsoft/botbuilder-js/security/dependabot/96 - CVE-2022-0235
- trim https://github.com/microsoft/botbuilder-js/security/dependabot/80 - CVE-2020-7753
This PR also improves the browser-functional project and pipeline to work with latest Chrome and Firefox drivers, avoiding using npm …
=> fix: Remove CVE-2022-23539 vulnerability by updating the jsonwebtoken packages

libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/package.json, testing/bot-integration/package.json, testing/functional/dialogToDialog/dialogRootBot/package.json, testing/functional/dialogToDialog/dialogSkillBot/package.json, testing/functional/functionaltestbot/package.json, testing/skills/skillchild/package.json, testing/skills/skillparent/package.json, testing/streaming-e2e/bot/package.json, testing/testbot/package.json, yarn.lock
#minor
This PR updates the version of the package **_restify_** to avoid the [CVE-2022-3517](https://security.snyk.io/vuln/SNYK-JS-MINIMATCH-3050818) vulnerability in minimatch 3.0.2.
- Updated  **_restify_** from ^8.5.1 to ^11.1.0.
The following image shows the **_minimatch_** versions installed after the update.
=> fix: Remove CVE-2022-3517 vulnerability with minimatch

package.json, testing/browser-functional/browser-echo-bot/yarn.lock, yarn.lock
#minor
This PR updates the version of the `glob-parent` package to `5.1.2` to fix the CVE-2020-28469 vulnerability.
- Removed `glob-parent` from resolutions as it's no longer needed.
- Updated `glob-parent` in `browser-echo-bot` project from `5.1.0` to `5.1.2`.
The following image shows the `glob-parent` updated version.
=> fix: Remove CVE-2020-28469 vulnerability by updating the glob-parent package

package.json, yarn.lock
#minor
This updates remaining medium and low vulnerable packages to latest possible versions:
- hosted-git-info https://github.com/microsoft/botbuilder-js/security/dependabot/27 - CVE-2021-23362
- tar https://github.com/microsoft/botbuilder-js/security/dependabot/343 - CVE-2024-28863
- semver https://github.com/microsoft/botbuilder-js/security/dependabot/279 - CVE-2022-25883
- ejs https://github.com/microsoft/botbuilder-js/security/dependabot/347 - CVE-2024-33883
- elliptic https://github.com/microsoft/botbuilder-js/security/dependabot/18 - CVE-2020-28498
- Updated `hosted-git-info`, `semver `, and `elliptic` versions by changing the yarn resolution reference inside yarn.lock file.
- Removed `tar` resolutions as it's no longer needed.
- Added `ejs` resolutions due to …
=> fix: Remove remaining vulnerabilities by updating the hosted-git-info, tar, semver, ejs, elliptic packages

libraries/botbuilder-azure-blobs/etc/botbuilder-azure-blobs.api.md, libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts, libraries/botbuilder-azure-blobs/tests/blobsTranscriptStore.test.js
Fixes #4715
This PR allows the use of Token Credentials to authenticate and create an instance of _BlobsTranscriptStore_.
- Added parameters _**blobServiceUri**_ and _**tokenCredential**_  in _BlobsTranscriptStore_ constructors. 
- Added constructor validations in unit tests.
The following images show the bot working and saving transcripts using _BlobsTranscriptStore_ instantiated with token credentials.
=> port: [#6813][#6798] Not able to create instance of BlobsTranscriptStore using TokenCredential instead of connectionString and containerName

testing/browser-functional/browser-echo-bot/package.json, testing/browser-functional/browser-echo-bot/yarn.lock
#minor
This PR updates the version of the package **_cssloader_** and adds a resolution to **_@microsoft/recognizers-text-number_** ^1.3.1 to avoid the vulnerabilities [CVE-2023-44270](https://security.snyk.io/vuln/SNYK-JS-POSTCSS-5926692) and [CVE-2020-28500](https://security.snyk.io/vuln/SNYK-JS-LODASH-1018905).
- Updated  **_cssloader_** from ^3.0.0 to ^6.11.0.
- Added resolution **_@microsoft/recognizers-text-number_** ^1.3.1 to remove use of _lodash.trimend_.
The following image shows the **_postcss_** version installed after the update.
=> fix: Remove browser-echo-bot vulnerabilities

testing/browser-functional/browser-echo-bot/yarn.lock, yarn.lock
#minor
This PR updates the _**elliptic**_ version to 6.5.7 to avoid the [CVE-2024-42460](https://github.com/advisories/GHSA-977x-g7h5-7qgw) vulnerability.
- Updated _elliptic_ to version 6.5.7 in _yarn.lock_ file.
The following image shows the _elliptic_ version installed.
=> fix: CVE-2024-42460 vulnerability with elliptic

libraries/botbuilder-dialogs-adaptive-runtime-integration-express/package.json, testing/bot-integration/package.json, yarn.lock
#minor
This PR fixes the '_outputs backtracking regular expressions_' issue with the `path-to-regexp` package by upgrading it to a safe version.
- Upgraded `express` dependency to the latest version 4.21.0 in _botbuilder-dialogs-adaptive-runtime-integration-express_ and _testing/bot-integration_ to upgrade the transitive dependency `path-to-regex`.
This image shows the safe version of the `path-to-regex` package being installed.
=> fix: Upgrade express dependency to latest version

package.json, testing/browser-functional/browser-echo-bot/yarn.lock, yarn.lock
#minor
This PR fixes the '_vulnerable to template injection that can lead to XSS_' issue with the `send` package by upgrading it to a safe version.
- Updated the `testing/browser-functional/browser-echo-bot/yarn.lock` file, removing old version of the send package so the new version could be resolved when reinstalling.
- Added the correct version of _send_ to the _resolutions_ section in `package.json`.
These images show the safe version of the `send` package being installed.
=> fix: Upgrade send dependency to latest version

libraries/botbuilder-applicationinsights/package.json, package.json, yarn.lock
#minor
This PR updates the `applicationinsights` package to version 2.9.6, the latest compatible version.
Upgrading to version 3.x will introduce breaking changes as it requires to initialize the instrumentation before the bot is executed ([issue](https ://github.com/microsoft/ApplicationInsights-node.js/issues/ 1375)).
- Updated `applicationinsights` from 1.7.5 to 2.9.6 in botbuilder-applicationinsights.
- Updated `applicationinsights` from 1.7.5 to 2.9.6 in root's package.json file.
The following image shows the unit tests passing and the telemetry logged by a bot with the custom properties in place.
=> bump: [#4684] Update applicationinsights dependency to version 2.x

libraries/botframework-streaming/etc/botframework-streaming.api.md, libraries/botframework-streaming/src/interfaces/INodeBuffer.ts
Fixes #4746
This PR fixes an issue with `INodeBuffer` incorrectly implementing the `Uint8Array`.
> [!NOTE]
> We are working on adding support for TS 5.6 and ESNext target in BotBuilder in a separate PR, which are impacting some of other libraries.
- Removed entries, keys, and values methods from the `INodeBuffer`, so they are inherited correctly across different TS versions.
The following image shows the `botframework-streaming` library building correctly with TS 5.6 and ESNext target.
=> fix: [#4746] Fix INodeBuffer in TypeScript 5.6 and ESNext target

package.json, yarn.lock
#minor
This PR fixes the vulnerabilities found with the `path-to-regexp` and `find-my-way` packages upgrading them to a safe version.
- Removed the old version of the **_path-to-regexp_** package from the _yarn-lock_ file so the install resolves the safe version 1.9.0.
- Added the safe version 8.2.2 of the **_find-my-way_** package to the _resolutions_ section of the _package.json_ file until _restify_ publishes a new version with the patch.
These images show the safe versions of the packages being installed.
=> fix: Upgrade path-to-regexp and find-my-way packages to latest version

libraries/botbuilder-ai/package.json, libraries/botbuilder-dialogs-adaptive-testing/package.json, libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder/package.json, libraries/botframework-connector/package.json, yarn.lock
#minor
This PR updates the `nock` package to version 13.5.5 fixing the failing test in _botbuilder-dialogs-adaptive-testing_.
- Updated `nock` from 11.9.1 to 13.5.5 in _botbuilder_, _botbuilder-ai_, _botbuilder-dialogs-adaptive-testing_, and _botframework-connector_.
- Fixed failing test in _botbuilder-dialogs-adaptive-testing_. Nock no longer recognizes arrays as part of the request's body. We used _JSON.stringify_ function for this case, as the tested functionality wasn't affected.
The following images show the unit tests passing after the upgrade.
=> bump: [#4684] Update nock dependency to latest version

libraries/botbuilder-core/tests/transcriptUtilities.js, package.json, yarn.lock
#minor
This PR updates the `rimraf` package to version 5.0.10, the latest compatible version with Node 18.
- Updated `rimraf` from 3.0.2 to 5.0.10 in root's `package.json`.
- Fixed import statement in `botbuilder-core/tests/transcriptUtilities.js` file.
The following image shows the unit tests in _botbuilder-core_ passing after the upgrade.
=> bump: [#4684] Upgrade rimraf dependency to v5

libraries/adaptive-expressions/.gitignore, libraries/adaptive-expressions/etc/adaptive-expressions.api.md, libraries/adaptive-expressions/package.json, libraries/adaptive-expressions/src/functionTable.ts, libraries/adaptive-expressions/src/functionUtils.ts, libraries/adaptive-expressions/tests/tsconfig.json, libraries/adaptive-expressions/tsconfig.json, libraries/adaptive-expressions/types/ts5.6/lib/index.d.ts, testing/consumer-test/run.ts, yarn.lock
Related issue #4746
#minor
This PR adds TypeScript 5.6 and ESNext target support for the test:consumer script.
The FunctionTable inside the adaptive-expressions project has been updated to support both es6 and esnext targets, alongside, lodash.isequal has been replaced for lodash, updating the import statement.
- Updated adaptive-expressions package.json, adding typesVersions with custom types for versions below 5.6.
- Replaced lodash.isequal for lodash.
- Updated FunctionTable class, changing IterableIterator for MapIterator due to the combination of TS 5.6 and ESNext requires using MapIterator.
- To address this disparity, we created a MapIterator type that extends from IterableIterator for all versions of TS below 5.6.
- Updated test:consumer script, adding TS 5.6 and ESNext target. …
=> feat: Add TS 5.6 and ESNext target support

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
Ported from #6863
#minor
This PR adds the 'dataset' property to the SearchInvokeValue interface, so it can be used when the OnSearchInvokeAsync event is triggered.
- Adds 'Dataset' property to the SearchInvokeValue interface.
The following image shows that the SearchInvokeValue having the dataset property set.
=> port: Add dataset to SearchInvokeValue

libraries/botbuilder-dialogs/src/skillDialog.ts
Fixes #4741
This PR ports the changes in [#6848](https://github.com/microsoft/botbuilder-dotnet/pull/6848) updating the **_interceptOAuthCards_** method in _SkillDialog_ to support _CloudAdapter_ in combination with _expect replies_ delivery mode.
- In _interceptOAuthCards_ added a call to _UserTokenAccess.exchangeToken_ method, which handles both adapters.
These images show the token exchange for _CloudAdapter_ and _expect replies_ before and after the fix.
=> port: [#6841] SkillDialog.InterceptOAuthCardsAsync doesn't support CloudAdapter

yarn.lock
#minor
This PR fixes the [CWE-72](https://cwe.mitre.org/data/definitions/74.html) weakness found in the `cookie` package by upgrading it to a safe version.
- Updated the `yarn.lock` file, removing the old version of the _express_ and _swagger-cilent_ packages so the safe version could be resolved when reinstalling.
This image shows the safe version of the `cookie` package installed.
=> fix: Upgrade cookie dependency to latest version

libraries/botbuilder-repo-utils/src/package.ts, libraries/botbuilder-repo-utils/src/updateVersions.ts, libraries/botbuilder-repo-utils/tests/updateVersions.test.ts
#minor
This PR fixes an issue with the update-versions script that didn't work with the latest workspaces changes.
- Changed workspaces type to use packages property instead of an array.
- Added unit tests to check if the command is running properly without altering the existing package.json files (using sinon).
The following image shows the script working, and the new unit test.
=> fix: Workspaces for update-versions script

generators/generator-botbuilder/package.json, package.json
#minor
This PR includes the `generators/generator-botbuilder` folder to the project's _workspaces_ so the _update-versions_ script can include the _package.json_ file inside this directory.
- Added the `generators/generator-botbuilder` folder to the project's _workspaces_.
- Changed version in `generators/generator-botbuilder/package.json` to 4.1.6 to match the rest of the projects.
This image shows the generators' .tgz file created with the correct version.
=> fix: Update Generators versions: Add missing directory to workspaces

libraries/botbuilder-lg/eslint.config.cjs, libraries/botbuilder-lg/package.json, libraries/botbuilder-lg/src/analyzer.ts, libraries/botbuilder-lg/src/customizedMemory.ts, libraries/botbuilder-lg/src/diagnostic.ts, libraries/botbuilder-lg/src/errorListener.ts, libraries/botbuilder-lg/src/evaluationOptions.ts, libraries/botbuilder-lg/src/evaluator.ts, libraries/botbuilder-lg/src/expander.ts, libraries/botbuilder-lg/src/extractor.ts, libraries/botbuilder-lg/src/index.ts, libraries/botbuilder-lg/src/multiLanguageLG.ts, libraries/botbuilder-lg/src/staticChecker.ts, libraries/botbuilder-lg/src/templateExtensions.ts, libraries/botbuilder-lg/src/templates.ts, libraries/botbuilder-lg/src/templatesParser.ts, libraries/botbuilder-lg/tests/lg.test.js, libraries/botbuilder-lg/tests/lgDiagnostic.test.js, libraries/botbuilder-lg/tests/multilanguageLG.test.js
#minor
This PR fixes the new ESLint errors and warnings after upgrading the ESLint packages in the **_botbuilder-lg_** project.
- Removed the 'only-warnings' plugin from 'botbuilder-lg/eslint.config.cjs' file and the related dependency.
- Applied the auto fix flag for most issues (spacing, trailing commas, indentation, and removing unnecessary eslint exceptions). 
- Applied manual fixes for new rules like 'no-require-imports'.
The following images show the number of issues fixed in the library and the tests passing after the changes.
=> fix: [#4684] ESLint issues in botbuilder-lg

package.json, testing/browser-functional/package.json, yarn.lock
#minor
This PR applies the needed changes to remove the unused resolutions in the project.
- Updated _**nightwatch**_ to version ^3.9.0, which allowed the removal of the resolutions:
- semver
- ejs
- lodash.pick
- Removed _**@types/ramda**_ resolution.
- Removed unnecessary resolution comments.
The following image shows the project building without errors after the updates.
=> fix: Remove unused resolutions

yarn.lock
#minor
This PR updates the _**path-to-regexp**_ version to avoid the [CVE-2024-52798](https://github.com/advisories/GHSA-rhx6-c78j-4q9w) vulnerability.
- Updated _path-to-regexp_ from 0.1.10 to 0.1.12 in lock file.
The following image shows the safe _path-to-regexp_ versions installed.
=> fix: CVE-2024-52798 vulnerability with path-to-regexp

.gitignore, libraries/adaptive-expressions/package.json, libraries/adaptive-expressions/src/builtinFunctions/formatNumber.ts, libraries/adaptive-expressions/src/builtinFunctions/string.ts, package.json, yarn.lock
#minor
This PR updates the _**d3-format**_ package to the latest version and applies the necessary configuration to keep working in _adaptive-expressions_.
- Updated _**d3-format**_  to version ^3.1.0.
- Added prebuild scripts to _adaptive-expressions_ to use tsup to compile ESM-only package.
- Updated imports of  _**d3-format**_  in every class.
The following image shows the  _adaptive-expressions_ unit tests working after the updates.
=> bump: Update d3-format package

libraries/botframework-connector/package.json, libraries/botframework-connector/src/auth/emulatorValidation.ts, libraries/botframework-connector/tests/auth/emulatorValidation.test.js, yarn.lock
#minor
This PR adds support for every possible token issuer version in Emulator validation.
- Added 3 new valid token issuers in token emulator validation.
- Added unit tests to check IsTokenFromEmulator expected results.
The following image shows the new unit tests working.
=> port:[#6879] Bot is not accepting v2 tokens from Bot Framework Emulator - Single Tenant Bots

libraries/botbuilder/package.json, libraries/botbuilder/tests/cloudAdapter.test.js
#minor
This PR adds a mock of an expired token to avoid token replacement in the _'throws exception on expired token'_ unit test.
- Mocked expired token in _'throws exception on expired token'_ test in cloudAdapterTest.
The following image shows the unit test running successfully.
=> port: [#6882] Mock expired token for 'throws exception on expired token' unit test

.github/workflows/depcheck.yml, .github/workflows/lint.yml, .github/workflows/test-compat.yml, .github/workflows/test-consumer.yml, .github/workflows/test-repoutils.yml, .github/workflows/test-schemas.yml, .github/workflows/tests.yml
#minor
This PR updates the actions/cache version due to deprecation and causing burnouts preventing workflows to function properly.
More info: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
The following image shows the issue.
=> fix: Fix actions/cache deprecation

package.json, yarn.lock
#minor
This PR updates elliptic, esbuild, and serialize-javascript packages to their latest versions.
- Updated elliptic by updating the yarn.lock
- Added esbuild and serialize-javascript to resolutions because they are subdependencies of packages that don't have the new versions.
The following image shows the audit not showing up any new sec issue.
=> fix: Update elliptic, esbuild, and serialize-javascript

yarn.lock
#minor
This PR updates the **pbkdf2** package to the safe version 3.1.3 fixing security alerts.
- Bumped pbkdf2 to version 3.1.3 in yarn.lock file.
This image shows the safe version of the package being resolved.
=> bump: pbkdf2 version from 3.1.1. to 3.1.3

libraries/botbuilder-core/tests/transcriptUtilities.js, libraries/botbuilder/src/channelServiceHandler.ts, libraries/botbuilder/tests/channelServiceHandler.test.js, libraries/botbuilder/tests/cloudAdapter.test.js, libraries/botframework-connector/src/auth/jwtTokenValidation.ts, libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts
#minor
This PR solves the following CodeQL issues of `high` severity:
- [CWE-22](https://cwe.mitre.org/data/definitions/22.html)
- [CWE-295](https://cwe.mitre.org/data/definitions/295.html)
- [CWE-807](https://cwe.mitre.org/data/definitions/807.html)
- Added a validation to the path of the zip file before moving to the directory in **_transcriptUtilities_**.
- Reordered validations to avoid relaying on user input to make authentication decisions in: 
- channelServiceHandler
- jwtTokenValidation
- parameterizedBotFrameworkAuthentication
-  Added a private function _isValidServiceURL_ in **_jwtTokenValidation_** to validate the URL before using it in the condition.
- Fixed failing tests in **_channelServiceHandler.test_**
These images show a bot working with anonymous and credential …
=> fix: CodeQL issues with severity High

libraries/botbuilder-ai/etc/botbuilder-ai.api.md, libraries/botbuilder-ai/package.json, libraries/botbuilder-ai/src/qnaMakerDialog.ts, libraries/botbuilder-ai/src/qnamaker-interfaces/qnamakerEndpoint.ts, libraries/botbuilder-ai/src/qnamaker-utils/httpRequestUtils.ts, libraries/botbuilder-ai/src/qnamaker-utils/languageServiceUtils.ts
Related DotNet issue https://github.com/microsoft/botbuilder-dotnet/issues/6889
#minor
This PR adds the ability to use a Managed Identity ClientId to authenticate to the Language service.
- Added managedIdentityClientId property to the QnAMakerDialog config.
- Added withEndpointKey and withManagedIdentityClientId methods to the QnAMakerDialog class to configure which authentication the request will use.
- Added the ability to detect and get the MSI token in the httpRequestUtils file.
The following image shows the bot working with both authorization types.
=> port: CQA to support TokenCredential instead of key

libraries/botbuilder-core/tests/chatdown.js, libraries/botbuilder-dialogs-adaptive-testing/tests/action.test.js, libraries/botbuilder-dialogs-adaptive/tests/beginSkill.test.js, libraries/botbuilder-dialogs-declarative/tests/jsonLoad.test.js, libraries/botbuilder-dialogs/tests/skillDialog.test.js, libraries/botbuilder/src/channelServiceRoutes.ts
#minor
This PR solves the following CodeQL issues:
- [CWE-209](https://cwe.mitre.org/data/definitions/209.html) - Medium
- [CWE-327](https://cwe.mitre.org/data/definitions/327.html) - Error
Additionally, it extends the timeout for the _jsonLoad_ unit test that frequently fails in the pipelines.
- Updated the _handleError_ function in **_channelServiceRoutes_** to log the error trace instead of sending it to the user in the HTTP Response.
- Changed the hash algorithm to a more secure one in: 
- chatdown.js
- action.test.js
- beginSkill.test.js
- skillDialog.test.js
- Added a 5 seconds timeout to fix transient errors in **_jsonLoad.test.js_** unit test.
These images show the involved tests passing after the changes.
=> fix: CodeQL issues with Medium and Error severity

libraries/botframework-connector/src/auth/jwtTokenExtractor.ts, libraries/botframework-connector/src/auth/openIdMetadata.ts, libraries/botframework-connector/src/auth/parameterizedBotFrameworkAuthentication.ts, libraries/botframework-connector/src/connectorApi/models/index.ts, libraries/botframework-connector/tests/openIdMetadata.test.js
#minor
This PR adds the **_tokenRefreshInterval_** property to the **_ConnectorClientOptions_** interface to set up the interval in the  bot's configuration. This value is used in _OpenIdMetadata's getKey_ method to retrieve the key from the cache, or to make a new request.
The interval should be configured in the following way:
```JavaScrip
const botFrameworkAuthentication = new ConfigurationBotFrameworkAuthentication(
process.env,
undefined,
undefined,
undefined,
{ tokenRefreshInterval: 1 } // Set the token refresh interval to 1 hour.
);
const adapter = new CloudAdapter(botFrameworkAuthentication);
```
**Considerations:**
- If tokenRefreshInterval is not set, it defaults to 24 hours (as it was originally).
- If tokenRefreshInterval is set to 0, it refreshes the token for each request.
- …
=> feat: Enable configuration of the OpenIdmetadata's refresh interval

libraries/botframework-schema/etc/botframework-schema.api.md, libraries/botframework-schema/src/index.ts
Fixes #4859
This PR marks as optional the `Activity` in the `ConversationParameters` interface as its documentation was describing.
- Added the ? symbol to the **_activity_** parameter to make it optional.
- The API declaration file was modified accordingly.
This image shows the unit tests passing after the change.
=> fix: [#4859] Inconsistent ConversationParameters interface

libraries/botframework-connector/package.json, package.json, testing/browser-functional/browser-echo-bot/crypto-shim.js, testing/browser-functional/browser-echo-bot/package.json, testing/browser-functional/browser-echo-bot/webpack.config.js, tsup/browser.config.ts, tsup/crypto-shim.js, yarn.lock
Fixes #4840
This pull request substitutes the `crypto-browserify` package in both tsup and webpack browser builds with the native Web Crypto API module. With these changes, the `hash.js` dependency causing policy violations is no longer used.
- Removed the `crypto-browserify` dependency from both the _root package.json_ and the _browser-echo-bot_.
- Updated `tsup` configuration to use `window.crypto` as the alias for the `crypto` module.
- Updated `webpack` configuration to use `window.crypto` as the alias for the `crypto` module.
These images show the **_browser-echo-bot_** working after the changes and the _**hash.js**_ package no longer installed.
=> fix: [#4840] The use of the package browserify-sign could violate Microsoft crypto policy

libraries/botframework-connector/src/connectorApi/models/mappers.ts
Fixes #4902
After migrating from _azure/core-http_ to _azure/core-client_ package, the _CompositeMapper_ changed its behavior regarding additional properties. Now, they must be defined in the model.
This PR fixes the issue of unmapped additional properties in the **Entity** by explicitly incorporating the object into the _Entity_ model.
- Updated `connectorApi/models/mappers` including the `additionalProperties` object in the _Entity_ model. Additionally, we removed it from the _entities_ array as it was redundant.
This image shows the informative streamInfo message being displayed after applying the fix.
=> fix: [#4902][onTurnError] unhandled error for informative streaming
