- samples/redux-bot-es6/app.js
- samples/redux-bot-es6/conversation.js
- samples/redux-bot-es6/package-lock.json
- samples/redux-bot-es6/package.json
- sample demonstrating how BotFramework can be usefully combined with other JavaScript frameworks
> Botframework redux es6

- samples/bot-handoff-es6/README.md
- samples/bot-handoff-es6/app.js
- samples/bot-handoff-es6/emulate-users.py
- samples/bot-handoff-es6/package.json
Sample code of bot-handoff as requested at bot hack. Thanks, Joe
> MS bothack 02-2018 samples

- samples/alarmbot-es6-botframework-webchat/package.json
- samples/alarmbot-es6-custom-webchat/package.json
- samples/alarmbot-es6/package.json
- samples/alarmbot-ts/package.json
- samples/bot-handoff-es6/package.json
- samples/dialogs/alarmbot-ts/package.json
- samples/dialogs/controls-ts/package.json
- samples/dialogs/echobot-ts/package.json
- samples/dialogs/inside-middleware-ts/package.json
- samples/dialogs/list-ts/package.json
- samples/dialogs/prompts-ts/package.json
- samples/echobot-console-ts/package.json
- samples/echobot-es6/package.json
- samples/echobot-ts/package.json
- samples/redux-bot-es6/package.json
This fixes the bad build:  https://travis-ci.org/Microsoft/botbuilder-js/builds/356114025
> Updated versions in the sameples to fix the build

- samples/redux-bot-es6/app.js
- samples/redux-bot-es6/conversation.js
- samples/redux-bot-es6/package-lock.json
- samples/redux-bot-es6/package.json
fix up the sample to work with the latest rev of sdk
> update redux sample to work with latest revs of sdk

- samples/luis-bot-es6/Reminders.json
- samples/luis-bot-es6/app.js
- samples/luis-bot-es6/botStateManager.js
- samples/luis-bot-es6/package.json
Largely based on the alarm bot sample, except using LUIS to identify add/delete/show. 
Used the Calendar prebuilt domain instead of alarm, because I can't seem to find the builtin alarm intents & entities in LUIS anymore. 
Left subId + key in for easy testing.
> Added LUIS es6 sample

- README.md
added preview to readme and remove experimental
> Update readme for preview

- samples/dialogs/echobot-ts/src/app.ts
Removing hardcoded appid in sample
> Removing hardcoded appid in sample

- libraries/botbuilder-core-extensions/tests/messageFactory.test.js
Addresses issue #241 
Travis CI Branch tests and local tests passing :)
> fix MessageFactory.suggestedActions() tests

- samples/dialogs/echobot-ts/lib/app.js
Crosslinking #354 
Note: This sample doesn't build with the packages in `master`, and I didn't bother fixing them since we're trying to keep the `master` samples pointing to the published packages.
> Remove app creds from dialogs/echobot-ts

- libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts
- libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts
- libraries/botbuilder-dialogs/tests/choicePrompt.test.js
- libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
Note: This bug doesn't look like it translated over to C#: ([ChoicePrompt](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs#L56-L59), [ConfirmPrompt](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs#L103-L106)).
> fix bug in Choice and ConfirmPrompt locale setting, add ChoicePrompt tests

- samples/2.echobot-with-counter/.env
- samples/2.echobot-with-counter/app.js
- samples/2.echobot-with-counter/dialogs/mainDialog/main.js
- samples/2.echobot-with-counter/dialogs/mainDialog/mainState.js
So, yesterday I committed directly into VK-samples (oops) https://github.com/Microsoft/botbuilder-js/commit/e2d3df529660ba61de7908387090bc813a49d783 and also one for the readme file https://github.com/Microsoft/botbuilder-js/commit/f941e6e9a8db3850a64ef831f37fd09511d4dd9f (oops again). 
So this PR request is somewhat redundant but you can take it for the record.
> update comments and minor code changes

- libraries/botframework-config/src/botConfiguration.ts
- libraries/botframework-config/src/botConfigurationBase.ts
- libraries/botframework-config/src/encrypt.ts
- libraries/botframework-config/src/index.ts
- libraries/botframework-config/src/models/appInsightsService.ts
- libraries/botframework-config/src/models/azureService.ts
- libraries/botframework-config/src/models/blobStorageService.ts
- libraries/botframework-config/src/models/botService.ts
- libraries/botframework-config/src/models/connectedService.ts
- libraries/botframework-config/src/models/cosmosDbService.ts
- libraries/botframework-config/src/models/endpointService.ts
- libraries/botframework-config/src/models/fileService.ts
- libraries/botframework-config/src/models/genericService.ts
- libraries/botframework-config/src/models/luisService.ts
- libraries/botframework-config/src/models/qnaMakerService.ts
- libraries/botframework-config/tests/encryption.test.js
Created BotConfigurationBase which has no node dependencies
Moved all file and crypto functionality to BotConfiguration which derives from BotConfigurationBase.
changed service.encrypt() to take in encrypt function as parameters to isolate them from nodejs crypto requirements
_Edit: Addresses #373_
> isolate nodejs functions 

- .travis.yml
- lerna.json
- package-lock.json
- package.json
- samples/dialogs/README.md
- tools/package-lock.json
Force `lerna@3.2.1` due to an issue with the license of future versions.
> Use lerna 3.2.1 as default

- package-lock.json
- package.json
add back in package-lock.json that was removed in #376
> add back in package-lock.json

- libraries/botframework-config/package.json
- libraries/botframework-config/src/botConfiguration.ts
- libraries/botframework-config/tests/export.test.js
unit test failed to find error on export of generic type.
Fixed bug and revamped unit test to catch the error
> fix generic export

- libraries/botframework-config/package-lock.json
- libraries/botframework-config/package.json
- libraries/botframework-config/src/botConfiguration.ts
- libraries/botframework-config/src/botConfigurationBase.ts
- libraries/botframework-config/src/botRecipe.ts
- libraries/botframework-config/src/models/appInsightsService.ts
- libraries/botframework-config/src/models/azureService.ts
- libraries/botframework-config/src/models/blobStorageService.ts
- libraries/botframework-config/src/models/botService.ts
- libraries/botframework-config/src/models/connectedService.ts
- libraries/botframework-config/src/models/cosmosDbService.ts
- libraries/botframework-config/src/models/dispatchService.ts
- libraries/botframework-config/src/models/endpointService.ts
- libraries/botframework-config/src/models/fileService.ts
- libraries/botframework-config/src/models/genericService.ts
- libraries/botframework-config/src/models/luisService.ts
- libraries/botframework-config/src/models/qnaMakerService.ts
- libraries/botframework-config/src/package.json
- libraries/botframework-config/src/schema.ts
- libraries/botframework-config/tests/export.test.js
- libraries/botframework-config/tests/loadAndSave.test.js
- libraries/botframework-config/tests/test.bot
add appId to bot record
change cosmosdb connectionstring to endpoint/key
add round trip of unknown properties
add migration path to load
update unit tests
> add appid to bot and connectionstring to endpoint/key for cosmosdb

- libraries/botbuilder-core/src/botState.ts
- libraries/botbuilder-core/src/index.ts
- libraries/botbuilder-core/src/propertyManager.ts
- libraries/botbuilder-dialogs/package-lock.json
implements DCR 933: Define IPropertyManager interface and make BotState implement it
> [DCR:933] add IPropertyManager interface to bot state

- libraries/botbuilder-core/src/testAdapter.ts
- libraries/botbuilder-dialogs/package.json
- libraries/botbuilder-dialogs/src/waterfallDialog.ts
- libraries/botbuilder-dialogs/tests/attachmentPrompt.test.js
- libraries/botbuilder-dialogs/tests/choicePrompt.test.js
- libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
- libraries/botbuilder-dialogs/tests/datetimePrompt.test.js
- libraries/botbuilder-dialogs/tests/dialog.test.js
- libraries/botbuilder-dialogs/tests/dialogContainer.test.js
- libraries/botbuilder-dialogs/tests/dialogSet.test.js
- libraries/botbuilder-dialogs/tests/numberPrompt.test.js
- libraries/botbuilder-dialogs/tests/textPrompt.test.js
- libraries/botbuilder-dialogs/tests/waterfallDialog.test.js
also discovered many unit tests which weren't awaiting the assertion test chain and so falsely succeeded.  Code was run, but output was not verified.
> add addStep, fix this pointer for steps 

- libraries/botbuilder-core/src/testAdapter.ts
- libraries/botbuilder-core/tests/botStatePropertyAccessor.test.js
- libraries/botbuilder-core/tests/testAdapter.test.js
- libraries/botbuilder-dialogs/tests/waterfallDialog.test.js
testAdapter didn't have the actual .startTest() method which returns a promise.
> fix more unittests

- libraries/botframework-config/src/botConfiguration.ts
- libraries/botframework-config/tests/loadAndSave.test.js
> Set BotConfiguration.internal as not enumerable

- libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts
- libraries/botbuilder-core/src/memoryTranscriptStore.ts
- libraries/botbuilder-core/src/transcriptLogger.ts
- libraries/botbuilder/src/fileTranscriptStore.ts
There is collision with new Transcript file in bot.schema
> rename ListTranscripts Transcript -> TranscriptInfo

- libraries/botbuilder-core/src/botAdapter.ts
- libraries/botbuilder-core/tests/botAdapter.test.js
> fix BotAdapter.onTurnError

- libraries/botframework-config/src/botConfiguration.ts
- libraries/botframework-config/src/botConfigurationBase.ts
- libraries/botframework-config/src/schema.ts
- libraries/botframework-config/tests/loadAndSave.test.js
rename secretKey to padlock
add backcompat mapping.
update unit tests to test it
> rename secretKey to padlock

- libraries/botbuilder-dialogs/src/componentDialog.ts
- libraries/botbuilder-dialogs/src/index.ts
- libraries/botbuilder-dialogs/src/mainDialog.ts
- libraries/botbuilder-dialogs/tests/dialogSet.test.js
- libraries/botbuilder-dialogs/tests/mainDialog.test.js
Still need to write the unit tests but this should work fine.
> Added new MainDialog class

- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botframework-connector/src/oAuthApiClient.ts
- libraries/botframework-connector/tests/connector.test.js
- libraries/botframework-schema/src/index.ts
Adding the OAuth API for the GetAadToken API which allows the user to get an access token to multiple Azure Active Directory resources.
> Add OAuth GetAadTokens API

- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botbuilder/tests/botFrameworkAdapter.test.js
for #388: **BotFrameworkAdapter does not work correctly with express 4.x**
> update WebResponse interface to match Express 4.x; #388

- libraries/botbuilder-ai/src/luisRecognizer.ts
- libraries/botbuilder-ai/tests/luisRecognizer.test.js
> add useful error messages based on response codes for LuisRecognizer

- libraries/botbuilder-ai/package.json
- libraries/botbuilder-azure/package.json
- libraries/botbuilder-core/package.json
- libraries/botbuilder-dialogs/package.json
- libraries/botbuilder-dialogs/src/dialogSet.ts
- libraries/botbuilder/package.json
- libraries/botframework-config/package.json
- libraries/botframework-connector/package.json
- libraries/botframework-schema/package.json
- package.json
Fixed dependencies to add ^ when building
> Updated committed dependencies and package.json to add ^${version}

- libraries/botframework-connector/package-lock.json
- libraries/botframework-connector/package.json
Updated request to 2.87.0 per https://snyk.io/node-js/request
> Fix npm package vulnerabilities in botframework-connector

- libraries/botframework-config/package-lock.json
Minor change to package version in package-lock.json.
> Use package-lock.json version

- libraries/botbuilder-azure/package-lock.json
We found botbuilder-azure/package-lock.json was missing. No vulnerabilities found for this library.
> Add missing botbuilder-azure/package-lock.json

- libraries/botbuilder-core/package-lock.json
We found botbuilder-core/package-lock.json was missing. No vulnerabilities found for this library.
> Add missing botbuilder-core/package-lock.json

- libraries/botbuilder-dialogs/package-lock.json
The only change in this PR is updating package-lock.json to use npmjs feed instead of myget
> Use npmjs instead of myget in package-lock.json

- libraries/botbuilder-ai/package.json
- libraries/botbuilder-dialogs/package.json
- libraries/botbuilder-dialogs/src/prompts/numberPrompt.ts
Updated recognizers dependencies to latest verison: 1.1.2
- @microsoft/recognizers-text-suite
- @microsoft/recognizers-text-choice
- @microsoft/recognizers-text-number
- @microsoft/recognizers-text-date-time
Replaces failing PR: https://github.com/Microsoft/botbuilder-js/pull/457 by updating only package.json file.
> Update recognizer dependencies to latest version ^1.1.2

- libraries/botbuilder-dialogs/src/choices/choiceFactory.ts
- libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts
- libraries/botbuilder-dialogs/tests/choicePrompt.test.js
- libraries/botbuilder-dialogs/tests/choices_choiceFactory.test.js
> update ChoiceFactory.toChoices to fill in partial Choice.actions

- libraries/botbuilder-dialogs/src/choices/channel.ts
Should fix missing confirm buttons in webchat
> updated supportsSuggestedActions() for directline & webchat

- libraries/botframework-connector/tests/auth.test.js
> temporarily disable AuthHeader tests to stop build breaks, #533

- .travis.yml
Update YAML file to pickup Travis environment variable to (hopefully) publish packages to myget.
> Enable MyGet Push with Travis Variable for API Key

- .travis.yml
Waiting on build + publish validations before merging.
> Update Travis Yaml file to pickup MyGet key from Travis variable

- libraries/botbuilder-ai/package-lock.json
- libraries/botbuilder-ai/package.json
- libraries/botbuilder-dialogs/package-lock.json
- libraries/botbuilder-dialogs/package.json
- package-lock.json
Fixes #N/A
Pin Recognizers-Text dependencies to 1.1.2
> pin recognizers-text dependencies to 1.1.2

- .travis.yml
Fixes #N/A
Remove explicit install of npm@5.6.0 to leave it at 6.4.1
> remove install npm@5.6.0 from .travis.yml

- libraries/swagger/model_fixes.js
- tools/scripts/each-service.js
- tools/scripts/executeCmds.js
- tools/scripts/filter-testresults.js
- tools/scripts/setup.js
- tools/scripts/teardown.js
- tools/scripts/unit-arm.js
- tools/scripts/unit-coverage.js
- tools/scripts/unit.js
Fixes #
Makes bug-tracking easier.  Better practice. 
- vars to consts
-
-
> Updating  required vars to consts

- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botframework-connector/src/auth/governmentConstants.ts
- libraries/botframework-connector/src/auth/jwtTokenValidation.ts
Cherrpick of @Jeffders Gov Constant changes to master from the 4.0 branch.
> Update US Gov constants

- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botframework-connector/src/auth/index.ts
- libraries/botframework-connector/src/auth/microsoftAppCredentials.ts
Cherry picking gov changes into master.
> Making bot code to work with prod gov

- libraries/botframework-config/src/models/luisService.ts
- libraries/botframework-config/tests/service.test.js
> update  getEndpoint() for us gov urls

- libraries/botbuilder-ai/src/languageGenerationResolver.ts
- libraries/botbuilder-ai/tests/languageGenerationResolver.test.js
- samples/04.simple-prompt/index.js
- samples/04.simple-prompt/languageGenerationMiddleware.js
- samples/13.basic-bot/index.js
- samples/13.basic-bot/languageGenerationMiddleware.js
- samples/51.cafe-bot/index.js
- samples/51.cafe-bot/languageGenerationMiddleware.js
- samples/53.book-table-bot/index.js
- samples/53.book-table-bot/languageGenerationMiddleware.js
- Use language generation production environment 
- Throw an exception in the middleware if the language resolution fails
> Use language generation production environment 

- package-lock.json
- tools/package-lock.json
- tools/package.json
> Mime: Update to 1.4.1 for security vulnerability

- libraries/botframework-connector/package-lock.json
- libraries/botframework-connector/package.json
- libraries/botframework-schema/package.json
- package-lock.json
Fixes #643 (In the 4.1.5 branch)
> cherry-pick to 4.1.5: pin ms-rest-js and ms-rest-azure-js in connector and schema

- libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts
- libraries/botbuilder-core/src/memoryTranscriptStore.ts
- libraries/botbuilder-core/src/transcriptLogger.ts
- libraries/botbuilder/src/fileTranscriptStore.ts
Fixes #474
Change PagedResult and TranscriptInfo classes to interfaces.
> [Breaking Change] change PagedResult and TranscriptInfo to interfaces

- .travis.yml
Add the new -appinsights package into the build process so the NPM publishes to MyGet. 
Fixes #674
> Add AppInsights package into build publish step

- libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts
This should fix the broken botbuilder-applicationinsights nightly build
> Fix require of cls-hooked

- libraries/botbuilder-ai/package.json
- package-lock.json
Fixes #793 against the 4.3 branch
> remove unused mstranslator from botbuilder-ai

- libraries/botbuilder-ai/package.json
- package-lock.json
Fixes: #793
Cherry pick removal of mstranslator from botbuilder-ai against master branch.
> Cherry-pick remove unused mstranslator from botbuilder-ai (#794)

- libraries/botbuilder-ai/tests/TestData/LuisSdk/Composite1.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/Composite2.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/Composite3.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/MultipleIntents_CompositeEntityModel.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/MultipleIntents_ListEntityWithMultiValues.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/MultipleIntents_ListEntityWithSingleValue.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/MultipleIntents_PrebuiltEntitiesWithMultiValues.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/MultipleIntents_PrebuiltEntity.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/Patterns.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/Prebuilt.json
- libraries/botbuilder-ai/tests/TestData/LuisSdk/SingleIntent_SimplyEntity.json
- libraries/botbuilder-ai/tests/luisSdk.test.js
SDK tests (ported oracle tests) based on recognizer tests..
We can augment with more.  Separate package we can supply to Autorest team.
Based on @chrimc62 oracle tests.
> Luis SDK tests (oracle)

- libraries/botbuilder-expression/src/expressionEvaluator.ts
- libraries/botbuilder-lg/src/getMethodExtensions.ts
> LG: Fix 'this' bind issue

- libraries/botbuilder/src/inspectionMiddleware.ts
- warning message when runtime fails to connect to sidecar emulator
- order of events - attempt to send state last
> warning message and order of state trace

- samples/10. sidecarDebugging/package.json
4.future isn't currently building. This fixes a sample preventing builds.
> fixed build break

- libraries/botbuilder/src/inspectionMiddleware.ts
> add 906 and 907 to master

- libraries/botbuilder-lg/src/errorListener.ts
- libraries/botbuilder-lg/src/staticChecker.ts
- libraries/botbuilder-lg/tests/mslgtool.test.js
> LG: Fix diagnostic error

- libraries/botbuilder-lg/src/analyzer.ts
- libraries/botbuilder-lg/src/evaluator.ts
- libraries/botbuilder-lg/src/expander.ts
- libraries/botbuilder-lg/src/extractor.ts
- libraries/botbuilder-lg/src/staticChecker.ts
Fixes #
fix format problems. 
fix some bugs in expander
fix format problems by TSLint
fix check the equality of two string array in expander
fix boolean expression of check whether a TerminalNode is undefined.
- 
-
-
> fix bugs and format

- libraries/botbuilder-expression-parser/tests/badExpression.test.js
- libraries/botbuilder-expression-parser/tests/expression.test.js
- libraries/botbuilder-expression/package.json
- libraries/botbuilder-expression/src/buildInFunction.ts
- libraries/botbuilder-expression/src/expressionType.ts
Add more expression functions including R1 and R2
> [Expression]add more functions

- libraries/botbuilder-expression-parser/tests/badExpression.test.js
- libraries/botbuilder-expression-parser/tests/expression.test.js
add more timestamp and dialog related tests
> add more tests

- libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts
> bring JS inline with C# for Teams invoke

- libraries/botbuilder-dialogs-adaptive/src/steps/cancelAllDialogs.ts
- libraries/botbuilder-dialogs-adaptive/src/steps/index.ts
- samples/50. todo-bot/src/addToDo/index.ts
- samples/50. todo-bot/src/deleteToDo/index.ts
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/1956
> Adaptive: rename CancelDialog -> CancelAllDialogs

- libraries/botbuilder-lg/src/templateEngine.ts
- libraries/botbuilder-lg/tests/lg.test.js
fixes https://github.com/microsoft/botbuilder-dotnet/issues/2100
> fix static checker issue in addFiles

- libraries/botbuilder-lg/src/templateEngine.ts
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2147
> expose expand function in templateEngine

- libraries/botbuilder-core/src/activityHandler.ts
- libraries/botbuilder-core/tests/ActivityHandler.test.js
Add MessageReaction to the Activities handler by the ActivityHandler.
This brings the JavaScript implementation in line with the C#.
> add MessageReaction to ActivityHandler

- lerna.json
- libraries/botbuilder/package.json
Fixed the build break due to package name change.
> Remove "-protocol" form the package name in lerna.json and package.json

- libraries/botbuilder-expression-parser/src/Expression.g4
- libraries/botbuilder-expression-parser/src/expressionEngine.ts
- libraries/botbuilder-expression-parser/src/generated/ExpressionListener.ts
- libraries/botbuilder-expression-parser/src/generated/ExpressionParser.ts
- libraries/botbuilder-expression-parser/src/generated/ExpressionVisitor.ts
- libraries/botbuilder-expression-parser/tests/badExpression.test.js
- libraries/botbuilder-expression-parser/tests/expression.test.js
- libraries/botbuilder-expression/src/buildInFunction.ts
- libraries/botbuilder-expression/src/expressionType.ts
- libraries/botbuilder-expression/src/extensions.ts
fix: https://github.com/microsoft/botbuilder-dotnet/issues/2186
C# version: https://github.com/microsoft/botbuilder-dotnet/pull/2195
> Support variable path shorthand

- libraries/botbuilder-lg/src/ImportResolver.ts
- libraries/botbuilder-lg/src/diagnostic.ts
- libraries/botbuilder-lg/src/errorListener.ts
- libraries/botbuilder-lg/src/index.ts
- libraries/botbuilder-lg/src/lgException.ts
- libraries/botbuilder-lg/src/lgParser.ts
- libraries/botbuilder-lg/src/lgResource.ts
- libraries/botbuilder-lg/src/mslgTool.ts
- libraries/botbuilder-lg/src/staticChecker.ts
- libraries/botbuilder-lg/src/templateEngine.ts
- libraries/botbuilder-lg/tests/mslgtool.test.js
- libraries/botbuilder-lg/tests/templateEngineThrowException.test.js
- package-lock.json
fix: https://github.com/microsoft/botbuilder-dotnet/issues/2188
C# version pr: https://github.com/microsoft/botbuilder-dotnet/pull/2191
> Refine static checker

- libraries/botbuilder-lg/src/lgTemplate.ts
> fix "lg parser unexpected output \r\n <EOF>"

- libraries/botbuilder-expression/src/TimeZoneConverter.ts
- libraries/botbuilder-expression/src/buildInFunction.ts
- libraries/botbuilder-expression/src/index.ts
- libraries/botbuilder-lg/src/index.ts
- libraries/botbuilder-lg/src/lgParser.ts
- libraries/botbuilder-lg/src/lgResource.ts
- libraries/botbuilder-lg/src/staticChecker.ts
- libraries/botbuilder-lg/src/templateEngine.ts
> Fix file not found bug

- libraries/botbuilder-dialogs/src/componentDialog.ts
- libraries/testbot/tests/dialogs/cancelAndHelpDialog.test.js
- libraries/testbot/tests/dialogs/testData/bookingDialogTestCases.js
Mirror #1068 changes in 4.5 branch
> Cherrypick reverted ComponentDialog changes into 4.5

- libraries/botbuilder-expression-parser/tests/badExpression.test.js
- libraries/botbuilder-expression-parser/tests/expression.test.js
- libraries/botbuilder-expression/src/buildInFunction.ts
- libraries/botbuilder-expression/src/expressionType.ts
- libraries/botbuilder-expression/src/extensions.ts
In Expression library of C# version, there is a SetPathToValue function used to set property path and value to dialog state in runtime, this PR is to add this function in js Expresssion library.
> [Expression] Add SetPathToValue function

- libraries/botbuilder-lg/src/mslgTool.ts
- libraries/botbuilder-lg/src/staticChecker.ts
- libraries/botbuilder-lg/src/templateEngine.ts
- libraries/botbuilder-lg/tests/mslgtool.test.js
> LG code Refine

- libraries/botbuilder-dialogs-declarative/tests/resources/12 - GithubIssueBot/show.lg
- libraries/botbuilder-expression-parser/src/expressionEngine.ts
- libraries/botbuilder-expression/src/builtInFunction.ts
- libraries/botbuilder-lg/src/analyzer.ts
- libraries/botbuilder-lg/src/evaluator.ts
- libraries/botbuilder-lg/src/expander.ts
- libraries/botbuilder-lg/src/getMethodExtensions.ts
- libraries/botbuilder-lg/src/staticChecker.ts
- libraries/botbuilder-lg/tests/lg.test.js
- libraries/botbuilder-lg/tests/testData/examples/6.lg
- libraries/botbuilder-lg/tests/testData/examples/8.lg
- libraries/botbuilder-lg/tests/testData/examples/Analyzer.lg
- libraries/botbuilder-lg/tests/testData/examples/BasicList.lg
- libraries/botbuilder-lg/tests/testData/examples/MultilineTextForAdaptiveCard.lg
- libraries/botbuilder-lg/tests/testData/examples/TemplateAsFunction.lg
- libraries/botbuilder-lg/tests/testData/examples/importExamples/1.lg
- libraries/botbuilder-lg/tests/testData/examples/lgTemplate.lg
- libraries/botbuilder-lg/tests/testData/exceptionExamples/LgTemplateFunctionError.lg
- libraries/botbuilder-lg/tests/testData/exceptionExamples/TemplateParamsNotMatchArgsNum.lg
- libraries/botbuilder-lg/tests/testData/mslgTool/ValidFile.lg
- package-lock.json
Fix: https://github.com/microsoft/botbuilder-dotnet/issues/2265
I inject every template as a function, so we will be able to use
{hello()} or {hello("world")} to call a template, i wonder if we should remove lgTemplate function
> Enable template reference in LG fully compatible with function

- libraries/botbuilder-ai/src/qnamaker-interfaces/index.ts
Fixes #1089
- fix path to lower camel case
> fix invalid module path

- libraries/botbuilder-expression-parser/tests/badExpression.test.js
- libraries/botbuilder-expression-parser/tests/expression.test.js
- libraries/botbuilder-expression/src/builtInFunction.ts
- libraries/botbuilder-lg/src/getMethodExtensions.ts
Fixes #
- join function in built-in function of Expression now works the same way as it is in LG
-
-
> [Expression] merge join function in LG method extension to expression

- libraries/botbuilder-lg/src/errorListener.ts
Fixes #
-  fix line number in errorListener. Line number should start from 1
-
-
> [LG] fix line number in errorListener

- libraries/botbuilder-ai/package.json
- libraries/botbuilder-applicationinsights/package.json
- libraries/botbuilder-azure/package.json
- libraries/botbuilder-core/package.json
- libraries/botbuilder-dialogs/package.json
- libraries/botbuilder-testing/package.json
- libraries/botbuilder/package.json
- libraries/botframework-config/package.json
- libraries/botframework-connector/package.json
- libraries/botframework-schema/package.json
- libraries/functional-tests/functionaltestbot/package.json
- libraries/testbot/package.json
- package.json
- tools/util/updateDependenciesInPackageJsons.js
- transcripts/package.json
Reverts microsoft/botbuilder-js#1085
> Revert "Changed library versions to "4.0.0-local""

- libraries/functional-tests/package.json
"lerna run test" command was failing.
removed broken test script from package.json
> lerna run test was failing

- libraries/botbuilder-ai/src/luisRecognizer.ts
Fixes #779 
Updates link in `LuisRecognizer` docstring to updated sample, `14.nlp-with-dispatch`.
> updated docstring in LuisRecognizer to newly reorg'd dispatch sample

- libraries/botbuilder-core/src/index.ts
- libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts
- libraries/botbuilder-core/src/turnContext.ts
- libraries/botbuilder-core/tests/mention.test.js
Fixes #2181
Added SkypeMentionNormalizeMiddleware to correct the Skype mention text so that TurnContext.removeMentionText operates correctly.
> Added SkypeMentionNormalizeMiddleware and tests

- libraries/botbuilder-dialogs-declarative/tests/fileResource.test.js
- libraries/botbuilder-dialogs-declarative/tests/resourceProvider.test.js
- libraries/botbuilder-lg/src/ImportResolver.ts
- libraries/botbuilder-lg/tests/lg.test.js
This reduces broken tests from 16 to 11 in build BotBuilder-JS-4.future-daily.
> Fix 5 tests in branch 4.future

- libraries/botbuilder-ai/src/qnamaker-interfaces/qnamakerOptions.ts
- libraries/botbuilder-ai/src/qnamaker-interfaces/qnamakerTraceInfo.ts
- libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts
- libraries/botbuilder-ai/tests/TestData/QnAMaker/should_return_answer_with_high_score_provided_id.json
- libraries/botbuilder-ai/tests/qnaMaker.test.js
Addition of a new optional parameter (qnaId) in GenerateAnswer body.
- Support for QnA Id added 
Test case added
> [QnA Maker] Multi-turn SDK support for QnAId

- libraries/botbuilder-ai/src/qnaMaker.ts
- libraries/botbuilder-ai/src/qnamaker-interfaces/qnamakerResults.ts
- libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts
- libraries/botbuilder-ai/tests/TestData/QnAMaker/should_return_answer_and_active_learning_flag.json
- libraries/botbuilder-ai/tests/qnaMaker.test.js
Added Active learning enabled flag support 
Tests added for that.
> [QnAMaker] GetAnswerRaw added

- libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/actionBasedMessagingExtensionBot.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/index.ts
Fixes #
Updated overridden method names/parameters, updated import statement in index.ts
- 
-
-
> updated sample bot to match signature of TeamsActivityHandler

- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/package.json
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/actionBasedMessagingExtensionFetchBot.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/adaptiveCardHelper.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/cardResponseHelpers.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/index.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/submitExampleData.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/tslint.json
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension/package.json
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/actionBasedMessagingExtensionBot.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/index.ts
- libraries/botbuilder/tests/teams/actionBasedMessagingExtension/tslint.json
- libraries/botbuilder/tests/teams/activityUpdateAndDelete/package.json
- libraries/botbuilder/tests/teams/activityUpdateAndDelete/src/activityUpdateAndDeleteBot.ts
- libraries/botbuilder/tests/teams/activityUpdateAndDelete/src/index.ts
- libraries/botbuilder/tests/teams/activityUpdateAndDelete/tslint.json
- libraries/botbuilder/tests/teams/adaptiveCards/package.json
- libraries/botbuilder/tests/teams/adaptiveCards/src/adaptiveCardsBot.ts
- libraries/botbuilder/tests/teams/adaptiveCards/src/index.ts
- libraries/botbuilder/tests/teams/adaptiveCards/tslint.json
- libraries/botbuilder/tests/teams/cardBotFramework/package.json
- libraries/botbuilder/tests/teams/cardBotFramework/src/cardsBot.ts
- libraries/botbuilder/tests/teams/cardBotFramework/src/index.ts
- libraries/botbuilder/tests/teams/cardBotFramework/tslint.json
Lint and refactor five of the Teams Scenarios in `botbuilder/tests/teams`
- Add tslint.json, tslint dev dependency and `"lint"` script to package.json for:
- actionBasedMessagingExtension
- actionBasedMessagingExtension-fetchTask
- activityUpdateAndDelete
- adaptiveCards
- cardBotframework
- The above samples have been linted
- The index.ts have been refactored to follow the layout of the core-bot sample
> [Teams] Lint Teams scenarios, minor refactor

- libraries/botbuilder/src/teamsActivityHandler.ts
- libraries/botbuilder/tests/teamsActivityHandler.test.js
- libraries/botbuilder/tests/teamsInfo.test.js
Test internal logic and add negative case for public method.
> [Teams] add more TeamsInfo tests

- libraries/botbuilder-lg/src/staticChecker.ts
- libraries/botbuilder-lg/tests/templateEngineThrowException.test.js
change severity of empty templatebody from error to warning
> change severity of empty templatebody

- libraries/botbuilder-lg/src/LGFileLexer.g4
- libraries/botbuilder-lg/tests/testData/examples/StructuredTemplate.lg
fix: https://github.com/microsoft/botbuilder-dotnet/issues/2712
> Add tab support in structuredd lg

- libraries/botbuilder/src/botFrameworkAdapter.ts
Fix to make sure the USER AGENT is sent as properly formatted JSON to in-proc Streaming requests for version information.
> Fix malformatted user agent JSON

- libraries/botbuilder-lg/src/analyzer.ts
- libraries/botbuilder-lg/src/evaluator.ts
- libraries/botbuilder-lg/src/expander.ts
- libraries/botbuilder-lg/src/staticChecker.ts
- libraries/botbuilder-lg/tests/lg.test.js
Fixes #
#1319 
Change lookbehind regex in LG.
In order to support more browsers for composer.
- 
-
-
> change lookbehind regex to lookahead regex. 

- libraries/botbuilder-lg/src/expander.ts
- libraries/botbuilder-lg/tests/mslgtool.test.js
> fix regex issue

- libraries/botbuilder/tests/teams/actionBasedMessagingExtension-fetchTask/src/actionBasedMessagingExtensionFetchBot.ts
- libraries/botbuilder/tests/teams/integrationBot/src/integrationBot.ts
- libraries/botbuilder/tests/teams/replyToChannel/src/replyToChannelBot.ts
> added local teamsCreateConversation helper

- libraries/botframework-expressions/package.json
- libraries/botframework-expressions/src/builtInFunction.ts
- libraries/botframework-expressions/src/expressionType.ts
- libraries/botframework-expressions/tests/badExpression.test.js
- libraries/botframework-expressions/tests/expression.test.js
Fixes #
- remove xPath and Xml builtin functions
-
-
> remove xPath and xml functions

- libraries/botbuilder-lg/tests/testData/examples/EvaluateOnce.lg
> fix test block

- libraries/botbuilder-core/src/transcriptLogger.ts
- libraries/botbuilder-core/tests/transcriptMiddleware.test.js
Fixes #1404
- Creates a pointer in TranscriptLoggerMiddleware's SendActivitiesHandler which ensures that the return value from the pipeline is continuously passed through
- If the return value is not an array, then create an array with the same number of empty ResourceResponses as there were outgoing activities.
- More tests
Add new tests for:
- An Adapter not returning the ResourceResponses to the TranscriptLoggerMiddleware (via TurnContext)
- Another SendActivitiesHandler before the TranscriptLoggerMiddleware does not return the value from `next()`
- Another SendActivitiesHandler before the TranscriptLoggerMiddleware returns a value that is not an Array.
- The actual return value from a SendActivitiesHandler before TranscriptLoggerMiddleware is pushed through the pipeline to any …
> [Fix #1404, Transcripts] Fix for TranscriptLoggerMiddleware not checking responses type

- libraries/botbuilder-lg/src/lgResource.ts
fix: https://github.com/microsoft/BotFramework-Composer/issues/1211
> fix template additional newline bug

- libraries/botframework-schema/package.json
Fixes #1405
This pull request adds the missing license into **botframework-schema** package.json file. Additionally, the file was updated to make it compliance with the format of the other libraries.
> [BotFramework-schema] Add License

- libraries/botbuilder-applicationinsights/README.md
> Remove dead links to unexisting AppInsights sample

- package.json
- tools/util/updateDependenciesInPackageJsons.js
* build: add preview package support
* build: tweak logging
* build: get preview version from argv
* build: handle previewVersion not being set
* build: streaming is GA now
(cherry picked from commit ac06ba27cb3ae8977b5b658515ffd670a1191fd7)
> build: add preview package support (#1490)

- libraries/botframework-streaming/src/interfaces/IStreamingTransportClient.ts
- libraries/botframework-streaming/src/interfaces/IStreamingTransportServer.ts
- libraries/botframework-streaming/src/requestHandler.ts
Fix more casing issues in relative imports in botframework-streaming
> fix more casing issues

- libraries/botbuilder-dialogs/package.json
- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botbuilder/src/botFrameworkHttpClient.ts
- libraries/botbuilder/src/skills/skillHandler.ts
- libraries/botbuilder/src/streaming/streamingHttpClient.ts
- libraries/botbuilder/tests/botFrameworkAdapter.test.js
- libraries/botframework-connector/src/auth/appCredentials.ts
- libraries/botframework-connector/src/auth/certificateAppCredentials.ts
- libraries/botframework-connector/src/auth/microsoftAppCredentials.ts
- libraries/botframework-connector/tests/appCredentials.test.js
- libraries/botframework-streaming/package.json
- libraries/botframework-streaming/src/interfaces/IStreamingTransportClient.ts
- libraries/botframework-streaming/src/interfaces/IStreamingTransportServer.ts
- libraries/botframework-streaming/src/namedPipe/namedPipeClient.ts
- libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts
- libraries/botframework-streaming/src/requestHandler.ts
- libraries/botframework-streaming/src/webSocket/webSocketServer.ts
Cherry-pick changes to master
#1498
#1496
#1495
#1494
#1493
> Cherry-pick commits from 4.7 branch to master

- libraries/botframework-expressions/src/expression.ts
- libraries/botframework-expressions/src/expressionType.ts
> Add Lambda Expression type

- libraries/botbuilder-ai/package-lock.json
- libraries/botbuilder-dialogs-declarative/src/factory/typeFactory.ts
- libraries/botbuilder-dialogs-declarative/src/pathUtil.ts
- libraries/botbuilder-dialogs-declarative/src/resources/fileResource.ts
- libraries/botbuilder-dialogs-declarative/src/resources/folderResoureProvider.ts
- libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts
- samples/50. todo-bot/src/showToDos/index.ts
Reverts microsoft/botbuilder-js#1531
> Revert "fix comments and add get fullName method in fileResource"

- libraries/botbuilder-dialogs-declarative/src/pathUtil.ts
- libraries/botbuilder-dialogs-declarative/src/resources/fileResource.ts
- libraries/botbuilder-dialogs-declarative/src/resources/folderResoureProvider.ts
- libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts
- libraries/botbuilder-dialogs-declarative/src/resources/resourceProvider.ts
https://github.com/microsoft/botbuilder-js/pull/1531
rewrite previous PR
> fix comments and add getFullname

- libraries/botframework-streaming/package.json
Cherry-pick #1547 to the 4.7 branch.
> Fix the value of typings in botframework-streaming

- libraries/browser-functional-tests/browser-tests-build-ci.yml
- libraries/browser-functional-tests/tests/message-handling-tests.js
- libraries/browser-functional-tests/tests/tests_pages/echoBotPage.js
Build Run-JS-Functional-Tests-BrowserBot-yaml was failing.
> Fix browser bot functional tests

- libraries/botbuilder-dialogs-adaptive-tests/package.json
- libraries/botbuilder-dialogs-adaptive-tests/resources/lg/test.de.lg
- libraries/botbuilder-dialogs-adaptive-tests/resources/lg/test.en-GB.lg
- libraries/botbuilder-dialogs-adaptive-tests/resources/lg/test.en-US.lg
- libraries/botbuilder-dialogs-adaptive-tests/resources/lg/test.en.lg
- libraries/botbuilder-dialogs-adaptive-tests/resources/lg/test.fr.lg
- libraries/botbuilder-dialogs-adaptive-tests/resources/lg/test.lg
- libraries/botbuilder-dialogs-adaptive-tests/src/actionScope.test.ts
- libraries/botbuilder-dialogs-adaptive-tests/src/actions.test.ts
- libraries/botbuilder-dialogs-adaptive-tests/src/conditions.test.ts
- libraries/botbuilder-dialogs-adaptive-tests/src/testScript.test.ts
- libraries/botbuilder-dialogs-adaptive-tests/src/testing/testRunner.ts
- libraries/botbuilder-dialogs-adaptive-tests/src/testing/testScript.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/sendActivity.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/updateActivity.ts
- libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
- libraries/botbuilder-dialogs-adaptive/src/languageGenerationMiddleware.ts
- libraries/botbuilder-dialogs-adaptive/src/resources/resourceExplorer.ts
- libraries/botbuilder-dialogs/src/configurable.ts
Fix a problem in lg generator middleware
Fix the initialization of ActivityTemplate
> Fix lg generator middleware and initialization of ActivityTemplate

- libraries/botbuilder-dialogs/src/choices/index.ts
- libraries/botbuilder-dialogs/tests/choices_channel.test.js
> fix export and update unit test import

- libraries/botbuilder-lg/src/evaluator.ts
- libraries/botbuilder-lg/tests/lg.test.js
- libraries/botbuilder-lg/tests/testData/examples/ReExecute.lg
> [Port] Forced re-execution expression within template

- libraries/botframework-schema/src/teams/index.ts
Fixes #1857 
Add the new fields.
> add memberCount and channelCount to TeamDetails

- libraries/adaptive-expressions/src/constant.ts
- libraries/adaptive-expressions/tests/expressionParser.test.js
closes https://github.com/microsoft/botbuilder-js/issues/1854
> [PORT] Update Constant Expression ToString method

- libraries/botbuilder-core/src/turnContext.ts
- libraries/botbuilder-dialogs/src/skillDialog.ts
- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botbuilder/tests/botFrameworkAdapter.test.js
- libraries/botframework-schema/src/index.ts
- libraries/testskills/skillparent/parentBot.js
need to add the response object
```
{
“activities”: [ // activities populated here]
}
```
> DONOTMERGE: Change DeliveryMode bufferedReplies to expectReplies

- libraries/botframework-streaming/src/payloadTransport/payloadSender.ts
- libraries/botframework-streaming/tests/PayloadSender.test.js
> apply PayloadSender fix from #1886 and add unit test

- libraries/botbuilder-dialogs/src/dialogHelper.ts
- libraries/botbuilder-dialogs/tests/dialogHelper.test.js
- libraries/botbuilder/src/botFrameworkHttpClient.ts
Fixes #1895,
Fixes #1897 against `master`
> [master, cherry-pick] fix runDialog helper, fix callerId

- .gitignore
- consumer-test/test.ts
- package.json
- run-consumer-test.js
Fixes #N/A
Adds a TypeScript consumer test to make sure different versions of TypeScript compile properly against our types.
- Adds consumer test runner which manages the different typescript versions and runs the compilation
- Adds consumer test file which touches all the publicly exported types (it doesn't catch unexported types - we need api-extractor or something equivalent to chase that problem)
- Adds `test:consumer` to package.json
It is a test! Yay!!!
> test: Add TypeScript consumer test

- libraries/botbuilder-core/src/activityFactory.ts
- libraries/botbuilder-lg/tests/ActivityFactory.test.js
> [PORT] [activityfactory] Improve missing type error

- libraries/adaptive-expressions/src/memory/simpleObjectMemory.ts
- libraries/adaptive-expressions/tests/expressionParser.test.js
Fixes  https://github.com/microsoft/botbuilder-js/issues/1929
> [PORT] Remove unnecessary restrication on memory path

- libraries/adaptive-expressions/src/constant.ts
- libraries/adaptive-expressions/src/expression.ts
- libraries/adaptive-expressions/src/expressionFunctions.ts
> [PORT]Add array return type

- libraries/botbuilder-lg/src/templateErrors.ts
fix the description for error template name in LG
> fix LG error message for template name

- libraries/botbuilder-core/src/telemetryConstants.ts
- libraries/botbuilder-core/src/telemetryLoggerMiddleware.ts
Addresses #1574 
Logs attachments on outgoing activities in telemetry, if the LogPersonalInformation flag is set to true.
> Add attachments to telemetry

- libraries/botbuilder-lg/src/templateExtensions.ts
Adjust the offset of diagnostic to make sure the line number of error is correct.
> Fix the offset issue of diagnostic

- libraries/botbuilder-lg/src/templatesParser.ts
- libraries/botbuilder-lg/tests/lgDiagnostic.test.js
- libraries/botbuilder-lg/tests/testData/exceptionExamples/EmptyLGFile.lg
close: #2110
ref: https://github.com/microsoft/botbuilder-dotnet/issues/3809
> [PORT] Support empty lg file.

- libraries/botbuilder-core/src/activityHandler.ts
- libraries/botbuilder-core/tests/ActivityHandler.test.js
- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botbuilder/src/teamsActivityHandler.ts
- libraries/botbuilder/tests/botFrameworkAdapter.test.js
- libraries/botframework-schema/src/healthCheck.ts
- libraries/botframework-schema/src/index.ts
> Add HealthCheck Invoke handling

- libraries/botbuilder-dialogs-adaptive/src/actions/index.ts
While working on samples for adaptive we found that we were missing some exports.
> Added missing adaptive dialog exports

- libraries/botframework-connector/src/teams/models/mappers.ts
- libraries/botframework-schema/etc/botframework-schema.api.md
- libraries/botframework-schema/src/teams/index.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/2157
> Add tenantId and userRole to TeamsChannelAccount

- libraries/botbuilder-ai/src/qnaMakerDialog.ts
> [QnA Maker] ActiveLearningDisable bug fix

- libraries/botbuilder-dialogs-adaptive/src/skills/adaptiveSkillDialog.ts
- libraries/botbuilder-dialogs-adaptive/tests/adaptiveSkillDialog.test.js
- libraries/botbuilder-dialogs/src/dialogManager.ts
Fixes #2195
Added basic unit tests and resolved detected issues.
> Fixed issues with AdaptiveSkillDialog

- libraries/botbuilder-dialogs-adaptive/src/actions/beginSkillDialog.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/index.ts
- libraries/botbuilder-dialogs-adaptive/src/adaptiveDialogComponentRegistration.ts
- libraries/botbuilder-dialogs-adaptive/src/index.ts
- libraries/botbuilder-dialogs-adaptive/src/skills/index.ts
- libraries/botbuilder-dialogs-adaptive/tests/beginSkillDialog.test.js
- Rename $kind Microsoft.SkillDialog => Microsoft.BeginSkillDialog
- Rename class AdaptiveSkillDialog => BeginSkillDialog
- Move files into actions folders
- Updated unit tests
> Renamed AdaptiveSkillDialog to BeginSkillDialog

- libraries/botbuilder/src/teamsActivityHandler.ts
- libraries/botbuilder/tests/teamsActivityHandler.test.js
Fixes: https://github.com/microsoft/botbuilder-js/issues/2233
> Do NOT call TeamsInfo.getMember for the bot: cherry pick from 4.9 (#2237)

- libraries/botbuilder/src/teamsActivityHandler.ts
> [Cherry-pick to 4.9] Missing break/return statements.

- libraries/botbuilder-ai/package.json
- libraries/botbuilder-core/src/coreAppCredentials.ts
- libraries/botbuilder/package.json
- libraries/botframework-connector/package.json
- package.json
Fixes https://github.com/microsoft/botbuilder-js/issues/2018
> Upgrade ms-rest-js to 1.8.15

- libraries/adaptive-expressions/src/expressionFunctions.ts
> Fix Missing break in flatten function

- libraries/browser-functional-tests/package.json
> Port #2279 chromedriver fix to 4.9 branch

- libraries/adaptive-expressions/src/parser/expressionParser.ts
issue link: https://github.com/microsoft/botbuilder-dotnet/issues/4005
close: #2312
Add cache for expression antlr parsing result.
> Cache Expression parsing result

- README.md
Fixes #2403 (part of SDK tracking issue https://github.com/microsoft/botframework-sdk/issues/5898)
Updates the readme in line with previous updates to .NET / Python readmes, following the docs pillar review.  Brings standardization to readmes, adds missing packages and also brings in the content regarding building the SDK in from the wiki (which will be removed following the merge of this PR).
> Updated readme from docs pillar review

- libraries/botframework-connector/src/connectorApi/models/mappers.ts
- libraries/botframework-schema/etc/botframework-schema.api.md
- libraries/botframework-schema/src/index.ts
> Add imageAltText to CardAction

- libraries/browser-functional-tests/browser-tests-build-ci.yml
> Fix browser build yaml

- libraries/botframework-connector/src/teams/models/mappers.ts
- libraries/botframework-schema/etc/botframework-schema.api.md
- libraries/botframework-schema/src/teams/index.ts
add linkToMessage to teams model mapper.ts and botframework-schema.api.md
add aadGroupId to teams index.ts
> Ensure fields from recent PRs are fully implemented

- libraries/botbuilder-dialogs-adaptive/src/adaptiveDialogComponentRegistration.ts
- libraries/botbuilder-dialogs-adaptive/src/input/ask.ts
- libraries/botbuilder-dialogs-adaptive/src/input/index.ts
Fixes #1560 
Added Microsoft.Ask component.
- Added Microsoft.Ask
- Registered Ask with Microsoft.Ask in component registration
-
> Added Microsoft.Ask

- libraries/botframework-streaming/src/interfaces/INodeSocket.ts
https://github.com/microsoft/botbuilder-js/pull/2515, but for 4.9 branch
> 4.9 Build Fix

- .github/CODEOWNERS
Adds appropriate Bot Framework SDK GitHub Teams as code owners
> [Engineering] update CODEOWNERS

- libraries/botbuilder-dialogs/src/choices/channel.ts
Fixes #2453
See https://github.com/microsoft/botbuilder-dotnet/issues/2291 for more information
- Remove Slack from helper function `supportsSuggestedActions()`
> Remove Slack from the list of channels that support Suggested Actions

- build/yaml/js-analysis-steps.yml
- build/yaml/js-build-steps.yml
> add eslint-plugin-jsdoc to build-steps.yml

- libraries/botbuilder-dialogs-adaptive-testing/tests/adaptiveDialog.test.js
Addresses #2338
Removed a duplicated test in the **BotBuilder-dialogs-adaptive-testing** tests.
Removed duplicated test `EmitEventActivityReceived` in the file `adaptiveDialog.test.js` and added missing end of file line.
This change does not reduce code coverage.
As you can see the time would be reduced approximately 15ms, which is the time that was taking the duplicated test.
> [Engineering] Lower time for botbuilder-dialogs-adaptive-testing tests

- libraries/botframework-connector/src/connectorApi/models/mappers.ts
- libraries/botframework-schema/src/index.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/2561
> Add additionalProperties to Entity

- libraries/botbuilder-testing/package.json
- libraries/botbuilder-testing/src/dialogTestLogger.ts
> Removed dependency on mocha-logger.  Defaulting to console.

- libraries/botbuilder-dialogs-adaptive/src/qnaMaker/qnaMakerRecognizer.ts
- libraries/botbuilder-dialogs-adaptive/tests/qnaMakerRecognizer.test.js
Fixes #2566 
Set startIndex/endIndex to the answer of qna maker recognizer.
- Set startIndex and endIndex to the answer of qna maker recognizer.
-
-
Updated test case.
> Set start/end index in qna maker recognizer

- libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
Fixes #2608
This ports the relevant dotnet fix.
- Port MS teams signin link handling fix (specifically for OauthInput) from dotnet SDK
> Add Teams oauth signin link handling to OauthInput

- libraries/botframework-config/src/models/luisService.ts
Fixes #2436
Port deprecation notice.
- Mark LuisService class deprecated
Not necessary
> Mark LuisService class deprecated

- libraries/botbuilder-dialogs-adaptive/src/actions/getConversationMembers.ts
Fixes improper method lookup on adapter.
> Fix bug in get conversation members action

- libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/logAction.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/sendActivity.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/updateActivity.ts
- libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts
- libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts
- libraries/botbuilder-dialogs-adaptive/src/generators/resourceMultiLanguageGenerator.ts
- libraries/botbuilder-dialogs-adaptive/src/generators/templateEngineLanguageGenerator.ts
- libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
- libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts
- libraries/botbuilder-dialogs-adaptive/src/template.ts
- libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts
- libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts
Adds some type parameters to `hond/extensions` fix.
> Better typing on extensions

- libraries/README.md
Decreases tribal knowledge of state of packages in `libraries/` by checking it in.
- Adds `libraries/README.md` which lists published and private packages. 
- Private packages have descriptions of what they're used for.
> add libraries/README.md

- libraries/botframework-connector/src/teams/models/mappers.ts
- libraries/botframework-schema/src/teams/index.ts
Fixes #2905
Note: quite a bit of the diff on the schema file was from code formatting. I left comments highlighting the actual changes I made.
> Add cache info to various teams responses

- build/yaml/botbuilder-js-api-check.yaml
- build/yaml/botbuilder-js-ci-node12.yml
- build/yaml/botbuilder-js-ci.yml
- build/yaml/botbuilder-js-daily.yml
- build/yaml/js-build-steps.yml
Changed vmImage from macOS-10.15 to ubuntu-18.04 for all JS pipelines.
> Change vmImage to ubuntu for all JS pipelines

- lerna.json
- libraries/botbuilder-azure-blobs/.gitignore
- libraries/botbuilder-azure-blobs/package.json
- libraries/botbuilder-azure-blobs/src/assert.ts
- libraries/botbuilder-azure-blobs/src/blobsStorage.ts
- libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts
- libraries/botbuilder-azure-blobs/src/ignoreError.ts
- libraries/botbuilder-azure-blobs/src/index.ts
- libraries/botbuilder-azure-blobs/src/maybeCast.ts
- libraries/botbuilder-azure-blobs/src/sanitizeBlobKey.ts
- libraries/botbuilder-azure-blobs/tests/blobsStorage.test.js
- libraries/botbuilder-azure-blobs/tests/blobsTranscriptStore.test.js
- libraries/botbuilder-azure-blobs/tests/ignoreError.test.js
- libraries/botbuilder-azure-blobs/tests/maybeCast.test.js
- libraries/botbuilder-azure-blobs/tsconfig.json
- libraries/botbuilder-core/src/storage.ts
- libraries/botbuilder-core/src/transcriptLogger.ts
- Port BlobsStorage class
- Port BlobsTranscriptStore class
Note: I renamed the branch hence the fresh PR. See https://github.com/microsoft/botbuilder-js/pull/2892 for extra context.
> port: botbuilder-azure-blobs package

- libraries/botbuilder-dialogs-adaptive-testing/src/testRunner.ts
Replaces https://github.com/microsoft/botbuilder-js/pull/2699
> fix: resource explorer event listener leak

- build/yaml/botbuilder-js-daily.yml
- lerna.json
Missed this in adding that new package.
> fix: add adaptive-expressions-ie11 to lerna.json

- build/yaml/botbuilder-js-daily.yml
- lerna.json
* Add adaptive-expressions-ie11 to lerna.json
* Add PKG18 to daily build pipeline
> cherry pick: add adaptive-expressions-ie11 to lerna.json (#2958)

- libraries/botbuilder-core/src/skills/botFrameworkClient.ts
- libraries/botbuilder-core/src/turnContext.ts
- libraries/botbuilder-dialogs/src/skillDialog.ts
- libraries/botframework-schema/src/index.ts
Also includes some small cleanup/formatting changes.
Fixes #2962
> cherry pick: PR #2962

- libraries/botbuilder-ai/src/qnaMakerDialog.ts
> fix: QnaMakerDialog constructor

- libraries/botframework-connector/package.json
> fix: move jsonwebtoken to deps

- libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts
- testing/consumer-test/run.ts
- testing/consumer-test/tsconfig-test.json
Should help catch even more bugs!
> fix: test-consumer strict mode

- libraries/botbuilder-ai/src/qnaMakerDialog.ts
- libraries/botframework-connector/package.json
Fixes #2975 and Fixes #2974 in the 4.11 branch.
> Cherry-pick fix: move jsonwebtoken to deps (#2976) & fix: QnaMakerDialog constructor (#2977)

- build/yaml/botbuilder-js-daily.yml
- build/yaml/js-build-steps.yml
- build/yaml/js-daily-build-steps.yml
* add js-daily-build-steps.yml for daily pipeline
* remove unused step in js-build-steps.yml
> add botbuilder-js-daily.yml pipeline to 4.10 branch

- libraries/botbuilder-core/src/botAdapter.ts
- libraries/botbuilder-core/src/testAdapter.ts
- libraries/botbuilder-core/src/turnContext.ts
- libraries/botbuilder-core/tests/testAdapter.test.js
- libraries/botbuilder-dialogs/tests/numberPrompt.test.js
- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botbuilder/src/skills/skillHandler.ts
- libraries/botbuilder/tests/botFrameworkAdapter.test.js
Includes some assorted cleanup and fixes as well.
Fixes #2937
> fix: turnContext updateActivity signature

- libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts
> fix: bug in Error when resource not found

- libraries/botbuilder-ai-orchestrator/src/orchestratorAdaptiveRecognizer.ts
- libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts
Fixes #
#4969
Documentation update for ModelPath and DisambiguationScoreThreshold
> minor documentation update to OrchestratorRecognizer

- libraries/botbuilder-core/src/activityHandlerBase.ts
- libraries/botbuilder-core/tests/activityHandlerBase.test.js
By coincidence found a grammatical typo.
- it's should be its
Changes the test and code together.
> Grammatical typo

- libraries/botbuilder/src/botFrameworkAdapter.ts
* Add support for `immediateAccept` option
Fixes https://github.com/microsoft/botframework-sdk/issues/6005
* strict boolean coercion
> cherry pick: immediate accept (#2950)

- libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts
> fix: support cosmos token provider option

- libraries/botbuilder/src/botFrameworkAdapter.ts
Reverts microsoft/botbuilder-js#3071
> Revert "cherry pick: immediate accept (#2950)"

- libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ConditionalsTests/ConditionalsTests_OnActivityTypes.test.dialog
- libraries/botbuilder-dialogs-adaptive/src/adaptiveComponentRegistration.ts
- libraries/botbuilder-dialogs-adaptive/src/conditions/index.ts
- libraries/botbuilder-dialogs-adaptive/src/conditions/onInstallationUpdateActivity.ts
Fixes #3024 
Added action: `OnInstallationUpdateActivity`.
- Added action
-
-
Updated tests for the new action.
> New action: OnInstallationUpdateActivity

- build/yaml/botbuilder-js-ci.yml
- build/yaml/botbuilder-js-daily.yml
- build/yaml/js-build-steps.yml
- build/yaml/js-daily-build-steps.yml
- libraries/botbuilder/tests/streaming/tokenResolver.test.js
- libraries/botframework-connector/src/auth/jwtTokenValidation.ts
- libraries/botframework-streaming/src/interfaces/INodeSocket.ts
* add .yaml-based Azure DevOps pipelines to 4.8 branch
* add readableFlowing property to INodeSocket (#2515)
* fix cherry-pick 8d9a3e3
Co-authored-by: Michael Richardson <40401643+mdrichardson@users.noreply.github.com>
And fix merge conflicts.
> cherry-pick (#3075) to 4.7 (add .yaml-based DevOps pipelines)

- .github/workflows/create-parity-issue.yml
PR descriptions can be multiline.
> fix: parity issue template

- .github/workflows/create-parity-issue.yml
> fix: add "needs-triage" label to parity issues

- libraries/botbuilder-core/src/botAdapter.ts
- libraries/botbuilder-core/src/middlewareSet.ts
- libraries/botbuilder-core/src/showTypingMiddleware.ts
- libraries/botbuilder-core/tests/botAdapter.test.js
- libraries/botbuilder-core/tests/middlewareSet.test.js
Cherry picks a fix from `main`.
> cherry pick: middleware handling (#2951)

- libraries/botbuilder-dialogs-adaptive/schemas/TriggerConditions/Microsoft.OnChooseEntity.uischema
> fix: port uischema for OnChooseEntity

- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.LogAction.schema
> fix: port LogAction change

- .github/CODEOWNERS
Simplified based on the Dotnet code owners file.
> fix: clean up codeowners file

- docs/SkillClaimsValidation.md
> fix: port skill claims how-to doc

- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.DeleteActivity.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.GetActivityMembers.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.UpdateActivity.schema
> fix: port schema example changes

- libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
> fix: port oauth input isMessage filters

- libraries/botbuilder-dialogs-adaptive-teams/schemas/Actions/Teams.SendAppBasedLinkQueryResponse.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/Actions/Teams.SendMessagingExtensionActionResponse.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/Actions/Teams.SendMessagingExtensionConfigQuerySettingUrlResponse.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/Actions/Teams.SendTaskModuleCardResponse.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/Actions/Teams.SendTaskModuleMessageResponse.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/Actions/Teams.SendTaskModuleUrlResponse.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/TriggerConditions/Teams.OnAppBasedLinkQuery.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/TriggerConditions/Teams.OnMessagingExtensionConfigurationQuerySettingUrl.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/TriggerConditions/Teams.OnMessagingExtensionConfigurationSetting.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/TriggerConditions/Teams.OnMessagingExtensionFetchTask.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/TriggerConditions/Teams.OnMessagingExtensionSubmitAction.schema
- libraries/botbuilder-dialogs-adaptive-teams/schemas/TriggerConditions/Teams.OnTaskModuleFetch.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.BreakLoop.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.CancelAllDialogs.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.CancelDialog.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.ContinueLoop.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.EndDialog.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.GotoAction.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.RepeatDialog.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.ReplaceDialog.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.ThrowException.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.Ask.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.AttachmentInput.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.ChoiceInput.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.ConfirmInput.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.DateTimeInput.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.NumberInput.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.OAuthInput.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.TextInput.schema
- libraries/botbuilder-dialogs-adaptive/schemas/TriggerConditions/Microsoft.OnEndOfConversationActivity.schema
> port: add action policies to .schema

- README.md
twitter account name changed to @msbotframework
Fixes #3299 
Changed the twitter account name as @msbotframework
- 
-
-
> Updated twitter account name

- libraries/adaptive-expressions/package.json
- yarn.lock
Resolves https://github.com/microsoft/botbuilder-js/security/dependabot/libraries/adaptive-expressions/package.json/xmldom/open
> fix: bump xmldom

- libraries/botbuilder-runtime/package.json
- libraries/botbuilder-runtime/src/configuration.ts
- libraries/botbuilder-runtime/src/index.ts
- libraries/botbuilder-runtime/test/configuration.test.ts
- libraries/botbuilder-runtime/test/index.test.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/3411
> fix: runtime parity

- libraries/botbuilder-dialogs-declarative/tests/schemaMergeTest.js
Fixes a schema:merge issue that can occur locally.
> Allow spaces in merge path

- .github/workflows/tests.yml
- README.md
- package.json
> bump: 4.13

- build/yaml/botbuilder-js-daily.yml
- libraries/botbuilder-repo-utils/src/updateVersions.ts
- libraries/botbuilder-repo-utils/tests/updateVersions.test.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/3489
> fix: semver formatting

- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
- libraries/botbuilder/src/setSpeakMiddleware.ts
- libraries/botbuilder/tests/setSpeakMiddleware.test.js
> port: remove lang from set speak middleware

- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.HttpRequest.schema
- libraries/botbuilder-dialogs-adaptive/schemas/Dialogs/Microsoft.OAuthInput.schema
- libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts
- libraries/botbuilder-dialogs/src/dialogHelper.ts
- libraries/botbuilder-dialogs/src/dialogManager.ts
- libraries/botbuilder-dialogs/src/memory/scopes/turnMemoryScope.ts
- libraries/botbuilder-dialogs/tests/dialogManager.test.js
- libraries/tests.schema
* port: pass through dialog state manager config
Fixes #3538
* port: turn memory scope exclude from snapshot
Fixes #3539
* port: update default property path for oauth input
Fixes #3536
* port: update http request default result property
Fixes #3537
> port: several parity issues (#3540)

- .github/workflows/pr-style.yml
> feat: add pr style check

- yarn.lock
> chore: update browserlist db

- libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts
- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
Fixes https://github.com/microsoft/botbuilder-js/issues/3550
> port: app insights connection string

- libraries/botbuilder-dialogs-adaptive-runtime/generated/luis.settings.mocha.westus.json
- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime/test/appsettings.json
- libraries/botbuilder-dialogs-adaptive-runtime/test/index.test.ts
* fix: merge generated config into runtime config
Fixes #3558
* fix: pr comments
> cherrypick: merge generated config into runtime config (#3561)

- libraries/adaptive-expressions/tests/triggerTree.test.js
#minor
This test is super annoying - let's skip it in CI until https://github.com/microsoft/botbuilder-js/issues/3506 is resolved.
> chore: skip flaky test until we resolve failures

- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/package.json
- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts
- yarn.lock
> feat: runtime serve static public files

- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/package.json
- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts
> feat: implement custom adapter lookup for functions

- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
Following https://github.com/microsoft/botframework-components/pull/893
#minor
> fix: lowercase en-us

- libraries/botbuilder-ai-orchestrator/package.json
- yarn.lock
Fixes #3579
Update orchestrator-core to point at GA 4.13.0
> feat: Update to orchestrator-core GA 4.13.0

- libraries/botbuilder-ai-orchestrator/package.json
- yarn.lock
Fixes #3479 
Updates orchestrator recognizer to point at orchestrator-core 4.13.0 GA
> feat: Update package reference for orchestrator-core to GA

- libraries/botbuilder/src/teams/teamsSSOTokenExchangeMiddleware.ts
- libraries/botbuilder/tests/teams/teamsSSOTokenExchangeMiddleware.test.js
> port: teams sso middleware tests

- libraries/botbuilder-ai-luis/.eslintrc.json
- libraries/botbuilder-ai-luis/.gitignore
- libraries/botbuilder-ai-luis/README.md
- libraries/botbuilder-ai-luis/package.json
- libraries/botbuilder-ai-luis/src/index.ts
- libraries/botbuilder-ai-luis/tsconfig.json
- libraries/botbuilder-ai-qna/.eslintrc.json
- libraries/botbuilder-ai-qna/.gitignore
- libraries/botbuilder-ai-qna/README.md
- libraries/botbuilder-ai-qna/package.json
- libraries/botbuilder-ai-qna/src/index.ts
- libraries/botbuilder-ai-qna/tsconfig.json
- libraries/botbuilder-dialogs-adaptive-runtime/package.json
- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
> cherrypick: export ai components for runtime consumption (#3586)

- libraries/browser-functional-tests/nightwatch.conf.js
- libraries/browser-functional-tests/package.json
- yarn.lock
Should resolve some recurring issues we've been having with the nightwatch browser tests.
#minor
> chore: bump nightwatch, add retries

- libraries/botbuilder-ai-orchestrator/package.json
- libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts
- yarn.lock
> bump: orchestrator-core package to 4.13.1

- libraries/adaptive-expressions/tests/triggerTree.test.js
- libraries/botbuilder-ai-orchestrator/package.json
- libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts
- yarn.lock
* Update orchestrator-core package to 4.13.1
* updated yarn lock file and log model path in failed model load exception
* Update orchestratorRecognizer.ts
> cherrypick: bump orchestrator-core package to 4.13.1 (#3608)

- libraries/botbuilder-lg/src/analyzer.ts
- libraries/botbuilder-lg/tests/lg.test.js
- libraries/botbuilder-lg/tests/lgDiagnostic.test.js
- libraries/botbuilder-lg/tests/testData/examples/Analyzer.lg
Fixes #3620
Support analyze recursive functions in `AnalyzeTemplate` API.
> port:[LG] Fix recursive functions error in analyzer

- libraries/botbuilder-ai-orchestrator/package.json
Fixes #3630 
Removed preview tag from botbuilder-ai-orchestrator package
> fix: remove preview tag from botbuilder-ai-orchestrator package

- libraries/botbuilder-ai-orchestrator/package.json
Removed preview tag from botbuilder-ai-orchestrator package
> Update package.json (#3629)

- tools/package.json
- yarn.lock
> chore: bump underscore

- libraries/adaptive-expressions/src/builtinFunctions/equal.ts
- libraries/adaptive-expressions/src/builtinFunctions/notEqual.ts
- libraries/adaptive-expressions/src/functionUtils.internal.ts
- libraries/adaptive-expressions/src/functionUtils.ts
- libraries/botbuilder-lg/src/evaluator.ts
- libraries/botbuilder-lg/src/expander.ts
Fixes #3622
Unify the comparison mechanism of LG and expression. Apply the equal function of Expression in LG library.
In C# this is a fix, but in js, this is a refinement.
> port: Apply Expression equal function in LG library

- libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
> port: save conversation state before sending card

- libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
> cherrypick: save conversation state before sending card (#3635)

- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime/test/index.test.ts
> cherrypick: cosmos db endpoint typo (#3641)

- README.md
> fix: update readme packages, formatting

- libraries/botbuilder-dialogs-adaptive-runtime/generated/luis.settings.mocha.westus.json
- libraries/botbuilder-dialogs-adaptive-runtime/package.json
- libraries/botbuilder-dialogs-adaptive-runtime/src/configuration.ts
- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime/test/appsettings.json
- libraries/botbuilder-dialogs-adaptive-runtime/test/index.test.ts
- yarn.lock
> fix: config file overrides

- libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts
- libraries/botbuilder-azure/src/blobStorage.ts
> fix: mark azure types deprecated

- libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
> fix: several skills-related runtime issues

- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts
> fix: json parse in azure function skill endpoint

- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
> cherrypick: skills fixes

- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts
> feat: configure static directory, default wwwroot

- libraries/botbuilder-dialogs-adaptive-runtime-integration-azure-functions/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-express/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime-integration-restify/src/index.ts
> cherrypick: configure static directory, default wwwroot (#3682)

- libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts
- libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts
See https://github.com/microsoft/BotFramework-Composer/issues/7854 for more details.
#minor
> fix: json serialization cycles

- libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts
> fix: two typos

- libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts
- libraries/botbuilder-stdlib/src/index.ts
- libraries/botbuilder-stdlib/src/retry.ts
- libraries/botbuilder-stdlib/tests/retry.test.js
- libraries/botbuilder/src/botFrameworkAdapter.ts
- libraries/botframework-connector/package.json
- libraries/botframework-streaming/package.json
- libraries/botframework-streaming/src/interfaces/IStreamingTransportServer.ts
- libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts
- libraries/botframework-streaming/src/payloadTransport/payloadReceiver.ts
- libraries/botframework-streaming/src/payloadTransport/payloadSender.ts
- libraries/botframework-streaming/src/utilities/createNodeServer.ts
- libraries/botframework-streaming/tests/NamedPipe.test.js
- libraries/botframework-streaming/tests/PayloadSender.test.js
- libraries/botframework-streaming/tests/ProtocolAdapter.test.js
- yarn.lock
> cherrypick: changes for 4.13.5

- libraries/streaming-e2e-tests/bot/package.json
#minor
Bump deps for the streaming bot to resolve test issues.
> chore: bump streaming bot deps

- libraries/botbuilder-core/src/activityFactory.ts
- libraries/botbuilder-dialogs-adaptive-tests/resources/ActionTests/Action_SetProperty.test.dialog
- libraries/botbuilder-dialogs-adaptive-tests/resources/SettingsStateTests/SettingsStateTests_SettingsTest.test.dialog
- libraries/botbuilder-dialogs-adaptive-tests/src/settingsState.test.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts
- libraries/botbuilder-dialogs-adaptive/src/actions/setProperty.ts
- libraries/botbuilder-dialogs/src/memory/scopes/settingsMemoryScope.ts
- libraries/botbuilder-dialogs/tests/memory_memoryScopes.test.js
Fix double evaluation and filter sensitive settings
> cherry-pick (4.9): Fix double evaluation and filter sensitive settings

- libraries/botbuilder-ai-orchestrator/README.md
> chore: README for Orchestrator package library folder

- libraries/botbuilder-dialogs-adaptive-testing/tests/adaptiveDialog.test.js
- libraries/botbuilder-dialogs-adaptive-testing/tests/resources/AdaptiveDialogTests/AdaptiveDialog_AllowInterruptionWithMaxCount.test.dialog
- libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
Fixes #3773
The turn count would increase only `turn.interrupte` is set to false.
> port: Maxturn count increase while interruption in composer prompts

- libraries/botbuilder-dialogs/src/memory/scopes/turnMemoryScope.ts
> port: turn memory scope in snapshot

- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
> fix: warning on component load failure

- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
- libraries/botbuilder-dialogs-adaptive-runtime/test/index.test.ts
> port: allowed caller runtime configuration

- libraries/botbuilder/package.json
- libraries/botbuilder/src/botFrameworkHttpClient.ts
- libraries/botbuilder/tests/botFrameworkHttpClient.test.js
- libraries/botframework-connector/src/auth/botFrameworkClientImpl.ts
- libraries/botframework-connector/src/connectorApi/operations/conversations.ts
- libraries/botframework-connector/src/conversationConstants.ts
- libraries/botframework-connector/src/index.ts
- libraries/botframework-connector/tests/recordings/Bot_Framework_Connector_SDK_Conversations_ReplyToActivity_should_fail_with_invalid_conversationId.nock.js
- libraries/botframework-connector/tests/recordings/Bot_Framework_Connector_SDK_Conversations_ReplyToActivity_should_return_a_valid_activityId.nock.js
> port: conversation ID header

- libraries/botbuilder-ai-orchestrator/package.json
- libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts
- yarn.lock
> fix: Update OrchestratorRecognizer to 4.14.0 orchestrator-core

- libraries/botbuilder/etc/botbuilder.api.md
- libraries/botbuilder/src/teamsInfo.ts
- libraries/botbuilder/tests/teamsInfo.test.js
> port: update TeamsInfo to support CloudAdapter

- libraries/botbuilder-ai-orchestrator/package.json
> port: orchestrator package changes

- .github/workflows/depcheck.yml
- .github/workflows/lint.yml
- .github/workflows/test-compat.yml
- .github/workflows/test-consumer.yml
- .github/workflows/test-repoutils.yml
- .github/workflows/test-schemas.yml
- .github/workflows/tests.yml
- libraries/botbuilder-ai-orchestrator/package.json
- libraries/botbuilder-core/src/cloudAdapterBase.ts
- libraries/botbuilder-core/tests/cloudAdapterBase.test.js
- libraries/botbuilder/package.json
- libraries/botbuilder/src/teamsInfo.ts
- libraries/botbuilder/tests/cloudAdapter.test.js
- libraries/botbuilder/tests/teamsInfo.test.js
- yarn.lock
See commit log for changes.
#minor
> feat: changes for rc1

- libraries/botbuilder-dialogs-adaptive-runtime/src/configuration.ts
- libraries/botbuilder-dialogs-adaptive-runtime/test/index.test.ts
> port: runtime feature tests

- libraries/botframework-connector/src/auth/appCredentials.ts
- libraries/botframework-connector/src/auth/credentialProvider.ts
- libraries/botframework-connector/src/auth/passwordServiceClientCredentialFactory.ts
- libraries/botframework-connector/src/tokenApi/tokenApiClientContext.ts
> fix: toJSON overrides

- libraries/adaptive-expressions/tests/badExpression.test.js
> port: Remove duplicate tests in adaptive expressions.

- libraries/botbuilder-core/src/recognizerResult.ts
- libraries/botbuilder-core/tests/getTopScoringIntent.test.js
- libraries/botbuilder-dialogs-adaptive/schemas/Actions/Microsoft.BeginSkill.uischema
- libraries/botbuilder-dialogs-adaptive/src/recognizers/crossTrainedRecognizerSet.ts
- libraries/tests.uischema
Cherrypicks two small fixes for a 4.14.1 patch.
#minor
> chore: cherrypick changes for 4.14.1

- libraries/botbuilder-lg/README.MD
> fix: remove preview from LG readme

- libraries/botbuilder-dialogs-adaptive/schemas/Microsoft.AdaptiveDialog.uischema
- testing/browser-functional/package.json
- yarn.lock
> port: hide dialogs property

- README.md
Fixes #3902
URL updated in README.md
> fix: URL for new dependency graph

- libraries/botbuilder-azure-blobs/package.json
This package has been published for quite a while, no reason to continue with the `-preview` tag.
#minor
> chore: make blobs a GA package

- .github/CODEOWNERS
Fixes: #minor
Addresses https://github.com/microsoft/botframework-sdk/issues/6401
Updated code owners file to only reference the @microsoft/botframework-sdk team
> chore: Updates code owners

- libraries/botbuilder-ai/tests/luisSdk.test.js
> fix: LUIS sdk test update

- build/yaml/botbuilder-js-daily.yml
Fixes #minor
Need "software bill of materials" for our public facing products, per Presidential Executive Order.
Task 'Generate Software Bill of Materials' added to nightly packaging build.
> chore: Add Software Bill of Materials task for JS

- build/yaml/botbuilder-js-daily.yml
Fixes #minor
failOnAlert set to false.
Task 'Delete files from ' just before the CD task disabled.
> fix: Set Component Detection task in JS daily pipeline to warn only

- build/yaml/botbuilder-js-daily.yml
> chore: Update botbuilder-js-daily.yml

- build/scripts/rebaseYarnLock.js
> chore: Add script to modify yarn.lock

- yarn.lock
Fixes #minor
PR #4093 did not contain an updated yarn.lock file to match the changes in the package.json files.
This PR fixes that.
> fix: Update yarn.lock to match main branch

- libraries/botbuilder-azure-blobs/etc/botbuilder-azure-blobs.api.md
- libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts
- libraries/botbuilder-azure-blobs/src/sanitizeBlobKey.ts
- libraries/botbuilder-azure-blobs/tests/blobsTranscriptStore.test.js
- libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts
- libraries/botbuilder-repo-utils/package.json
- libraries/botbuilder-repo-utils/src/package.ts
- libraries/botbuilder-repo-utils/src/updateVersions.ts
- testing/browser-functional/browser-echo-bot/yarn.lock
- testing/consumer-test/package.json
- yarn.lock
#minor
Cherry picks of security updates and telemetry fix.
> fix: Cherry picks of security updates and telemetry fix.

- generators/generator-botbuilder/generators/app/templates/core/deploymentTemplates/DeployUseExistResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/core/deploymentTemplates/DeployWithNewResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/DeployUseExistResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/DeployWithNewResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/DeployUseExistResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/DeployWithNewResourceGroup/readme.md
> chore: Reasonable ARM Template readme formatting

- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployUseExistResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployWithNewResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json
- generators/generator-botbuilder/generators/app/templates/echo/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployUseExistResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployWithNewResourceGroup/readme.md
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json
- generators/generator-botbuilder/generators/app/templates/empty/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json
> chore: Folder casing (again) - 2

- generators/generator-botbuilder/components/commonFilesWriter.js
> fix: Updated generator top copy new ARM template structure

- generators/generator-botbuilder/generators/app/index.js
- generators/generator-botbuilder/package.json
Fixes #4294
This PR updates `yeoman-generator` dependency in the `generators` folder, and also fixes the breaking changes issues.
- Updated `yeoman-generator` from `4.13.0` to `5.6.1`.
- Added `install` file to extend the `Generator` class from the library, as suggested in this [release](https://github.com/yeoman/generator/releases/tag/v5.0.0).
The following image shows the generator continues to work after fixing the breaking change.
> bump: [#4294] Update yeoman-generator to 5.6.1

- codeql3000.yml
Fixes #minor
This file allows CodeQL analysis to run in YAML pipelines, per new security requirements. 
See: [BAP Global Static Code Analysis](https://microsoft.sharepoint.com/:p:/t/BAGFundamentals/EXgAspg49xlMgdzRwAf_qFYB77t52eymYMofUHjtWfgt6g?e=fkZVHT&isSPOFile=1&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cv-brucehaley%40microsoft.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA5MDQwMDcwNyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)
> chore: Add codeql3000.yml file for JS

- package.json
- yarn.lock
> fix: Compliance issues

- codeql3000.yml
> chore: Enabled TSA

- .config/tsaoptions.json
> chore: Added tsaoptions.json

- codeql3000.yml
> chore: Corrected TSAEnabled key casing

- .github/workflows/tests.yml
> Dropped Node 12 from builds

- libraries/botbuilder/src/teams/teamsSSOTokenExchangeMiddleware.ts
#minor
it seems that the adapter has exchangeToken interface, the parameter is different with `botFrameworkAdapter`'s `exchangeToken` interface
- 
-
-
> fix: fix the exchange token interface prarameter

- libraries/botbuilder-azure-blobs/src/blobsStorage.ts
Fixes #4586
Add content type header to uploaded blobs
> fix: add content type header

- generators/generator-botbuilder/generators/app/templates/core/bots/dialogAndWelcomeBot.js
- generators/generator-botbuilder/generators/app/templates/core/bots/dialogAndWelcomeBot.ts
- generators/generator-botbuilder/generators/app/templates/core/bots/dialogBot.js
- generators/generator-botbuilder/generators/app/templates/core/bots/dialogBot.ts
- generators/generator-botbuilder/generators/app/templates/core/index.js
- generators/generator-botbuilder/generators/app/templates/core/index.ts
- generators/generator-botbuilder/generators/app/templates/core/tests/bots/dialogAndWelcomeBot.test.js
- generators/generator-botbuilder/generators/app/templates/core/tests/bots/dialogAndWelcomeBot.test.ts
- generators/generator-botbuilder/generators/app/templates/echo/bot.js
- generators/generator-botbuilder/generators/app/templates/echo/bot.ts
- generators/generator-botbuilder/generators/app/templates/echo/index.js
- generators/generator-botbuilder/generators/app/templates/echo/index.ts
- generators/generator-botbuilder/generators/app/templates/empty/bot.js
- generators/generator-botbuilder/generators/app/templates/empty/bot.ts
- generators/generator-botbuilder/generators/app/templates/empty/index.js
- generators/generator-botbuilder/generators/app/templates/empty/index.ts
#minor
https://github.com/microsoft/BotBuilder-Samples/issues/2625
> fix: Removed Copyright from generated code

- generators/generator-botbuilder/generators/app/templates/core/package-with-tests.json.js
- generators/generator-botbuilder/generators/app/templates/core/package-with-tests.json.ts
- generators/generator-botbuilder/generators/app/templates/core/package.json.js
- generators/generator-botbuilder/generators/app/templates/core/package.json.ts
- generators/generator-botbuilder/generators/app/templates/echo/package.json.js
- generators/generator-botbuilder/generators/app/templates/echo/package.json.ts
- generators/generator-botbuilder/generators/app/templates/empty/package.json.js
- generators/generator-botbuilder/generators/app/templates/empty/package.json.ts
> Generators to SDK 4.22.1

- package.json
- yarn.lock
> bump: tar to 6.1.9

- package.json
> bump: axios to 0.21.2

- package.json
- yarn.lock
> bump: axios and ws

- libraries/botbuilder/src/channelServiceRoutes.ts
> fix: SM03944 suppression

- libraries/botbuilder-lg/src/evaluationOptions.ts
> fix: SM04509 suppression

- libraries/botbuilder-repo-utils/package.json
- yarn.lock
#minor
Updates `ts-node` to a newer version to solve an issue in updateVersions command.
The following image shows the command working.
> fix: [#4684] Update versions command

- libraries/botframework-schema/etc/botframework-schema.api.md
- libraries/botframework-schema/src/sharepoint/cardView/cardViewParameters.ts
#minor
See title. Need this additional cardViewType to achieve symmetry with [documentation for .NET SDK](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/viva/bot-powered/authn-and-authz-in-bot-powered-aces-entra#implementing-the-sign-in-card-view-with-single-sign-on)
- See title
> fix: Add signInSso cardviewType to SignInCardViewParameters
